import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { JsonStore } from '../packages/platform/src/json-store.js';
import { MediaDestinationService } from '../packages/platform/src/media-destination-service.js';

const fixture=async()=>{const directory=await mkdtemp(join(tmpdir(),'vynodearr-destinations-')),store=new JsonStore(join(directory,'destinations.json'),{version:2,initialized:false,destinations:[]}),service=new MediaDestinationService(store);return{directory,store,service};};
const movieContext={roots:[{id:1,path:'/movies',accessible:true},{id:2,path:'/movies-4k',accessible:false}],profiles:[{id:1,name:'HD'},{id:2,name:'Ultra HD'}],plexLibraries:[{key:'10',type:'movie',title:'Movies',locations:['/movies']},{key:'11',type:'movie',title:'Movies 4K',locations:['/plex/movies-4k']}]};

test('existing single-folder installations receive safe discovered destinations without migration',async()=>{const value=await fixture();try{const destinations=await value.service.context('movie',movieContext);assert.equal(destinations.length,2);assert.equal(destinations[0].name,'Movies');assert.equal(destinations[0].isDefault,true);assert.equal(destinations[0].ready,true);assert.equal(destinations[0].suggestedPlexLibrary.title,'Movies');assert.equal(destinations[1].restartRequired,true);assert.equal((await value.store.read()).initialized,false);}finally{await rm(value.directory,{recursive:true,force:true});}});

test('configured destinations keep one default and apply folder, profile, tags, and television defaults',async()=>{const value=await fixture();try{const standard=await value.service.save({domain:'movie',name:'Standard Movies',rootFolderPath:'/movies',qualityProfileId:1,isDefault:true,plexLibraryKey:'10',tags:[4]},movieContext),imported=(await value.service.context('movie',movieContext)).find(item=>item.rootFolderPath==='/movies-4k'),ultra=await value.service.save({...imported,name:'4K Movies',qualityProfileId:2,isDefault:true,administratorOnly:true,plexLibraryKey:'11'},movieContext),destinations=await value.service.context('movie',movieContext);assert.equal(destinations.find(item=>item.id===standard.id).isDefault,false);assert.equal(destinations.find(item=>item.id===ultra.id).isDefault,true);assert.equal((await value.service.context('movie',{...movieContext,administrator:false})).some(item=>item.id===ultra.id),false);assert.deepEqual(value.service.apply({title:'Film',tags:[3]},destinations.find(item=>item.id===standard.id)),{title:'Film',tags:[3,4],mediaDestinationId:standard.id,rootFolderPath:'/movies',qualityProfileId:1,minimumAvailability:'announced'});
const tvContext={roots:[{id:1,path:'/anime',accessible:true}],profiles:[{id:8,name:'Anime'}],plexLibraries:[]},anime=await value.service.save({domain:'tv',name:'Anime',rootFolderPath:'/anime',qualityProfileId:8,isDefault:true,monitor:'future',seriesType:'anime'},tvContext),applied=value.service.apply({addOptions:{searchForMissingEpisodes:true}},(await value.service.context('tv',tvContext)).find(item=>item.id===anime.id));assert.equal(applied.rootFolderPath,'/anime');assert.equal(applied.qualityProfileId,8);assert.equal(applied.seriesType,'anime');assert.equal(applied.monitored,true);assert.equal(applied.addOptions.monitor,'future');assert.equal(applied.addOptions.searchForMissingEpisodes,true);}finally{await rm(value.directory,{recursive:true,force:true});}});

test('destination edits reject unknown engine folders, profiles, and Plex libraries',async()=>{const value=await fixture();try{await assert.rejects(()=>value.service.save({domain:'movie',name:'Bad root',rootFolderPath:'/outside',qualityProfileId:1},movieContext),/root folder/);await assert.rejects(()=>value.service.save({domain:'movie',name:'Bad profile',rootFolderPath:'/movies',qualityProfileId:99},movieContext),/quality profile/);await assert.rejects(()=>value.service.save({domain:'movie',name:'Bad Plex',rootFolderPath:'/movies',qualityProfileId:1,plexLibraryKey:'missing'},movieContext),/Plex library/);}finally{await rm(value.directory,{recursive:true,force:true});}});
