import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,rm } from 'node:fs/promises';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { JsonStore } from '../packages/platform/src/json-store.js';
import { MediaDestinationService } from '../packages/platform/src/media-destination-service.js';

const fixture=async()=>{const directory=await mkdtemp(join(tmpdir(),'vynodearr-destinations-')),store=new JsonStore(join(directory,'destinations.json'),{version:2,initialized:false,destinations:[]}),service=new MediaDestinationService(store);return{directory,store,service};};
const movieContext={roots:[{id:1,path:'/movies',accessible:true},{id:2,path:'/movies-4k',accessible:false}],profiles:[{id:1,name:'HD'},{id:2,name:'Ultra HD'}],plexLibraries:[{key:'10',type:'movie',title:'Movies',locations:['/movies']},{key:'11',type:'movie',title:'Movies 4K',locations:['/plex/movies-4k']}]};

test('existing single-folder installations receive safe discovered destinations without migration',async()=>{const value=await fixture();try{const destinations=await value.service.context('movie',movieContext);assert.equal(destinations.length,2);assert.equal(destinations[0].name,'Movies');assert.equal(destinations[0].isDefault,true);assert.equal(destinations[0].ready,true);assert.equal(destinations[0].suggestedPlexLibrary.title,'Movies');assert.equal(destinations[1].restartRequired,true);assert.equal((await value.store.read()).initialized,false);}finally{await rm(value.directory,{recursive:true,force:true});}});

test('configured destinations keep one default and apply folder, profile, tags, and television defaults',async()=>{const value=await fixture();try{const standard=await value.service.save({domain:'movie',name:'Standard Movies',rootFolderPath:'/movies',qualityProfileId:1,isDefault:true,plexLibraryKey:'10',tags:[4]},movieContext),imported=(await value.service.context('movie',movieContext)).find(item=>item.rootFolderPath==='/movies-4k'),ultra=await value.service.save({...imported,name:'4K Movies',qualityProfileId:2,isDefault:true,administratorOnly:true,plexLibraryKey:'11'},movieContext),destinations=await value.service.context('movie',movieContext);assert.equal(destinations.find(item=>item.id===standard.id).isDefault,false);assert.equal(destinations.find(item=>item.id===ultra.id).isDefault,true);assert.equal((await value.service.context('movie',{...movieContext,administrator:false})).some(item=>item.id===ultra.id),false);assert.deepEqual(value.service.apply({title:'Film',tags:[3]},destinations.find(item=>item.id===standard.id)),{title:'Film',tags:[3,4],mediaDestinationId:standard.id,rootFolderPath:'/movies',qualityProfileId:1,minimumAvailability:'announced'});
const tvContext={roots:[{id:1,path:'/anime',accessible:true}],profiles:[{id:8,name:'Anime'}],plexLibraries:[]},anime=await value.service.save({domain:'tv',name:'Anime',rootFolderPath:'/anime',qualityProfileId:8,isDefault:true,monitor:'future',seriesType:'anime'},tvContext),applied=value.service.apply({addOptions:{searchForMissingEpisodes:true}},(await value.service.context('tv',tvContext)).find(item=>item.id===anime.id));assert.equal(applied.rootFolderPath,'/anime');assert.equal(applied.qualityProfileId,8);assert.equal(applied.seriesType,'anime');assert.equal(applied.monitored,true);assert.equal(applied.addOptions.monitor,'future');assert.equal(applied.addOptions.searchForMissingEpisodes,true);}finally{await rm(value.directory,{recursive:true,force:true});}});

test('destination edits reject unknown engine folders, profiles, and Plex libraries',async()=>{const value=await fixture();try{await assert.rejects(()=>value.service.save({domain:'movie',name:'Bad root',rootFolderPath:'/outside',qualityProfileId:1},movieContext),/root folder/);await assert.rejects(()=>value.service.save({domain:'movie',name:'Bad profile',rootFolderPath:'/movies',qualityProfileId:99},movieContext),/quality profile/);await assert.rejects(()=>value.service.save({domain:'movie',name:'Bad Plex',rootFolderPath:'/movies',qualityProfileId:1,plexLibraryKey:'missing'},movieContext),/Plex library/);}finally{await rm(value.directory,{recursive:true,force:true});}});

test('new engine roots remain selectable after destinations were initialized',async()=>{const value=await fixture();try{await value.service.save({domain:'movie',name:'Movies',rootFolderPath:'/movies',qualityProfileId:1,isDefault:true},movieContext);const expanded={...movieContext,roots:[...movieContext.roots,{id:3,path:'/movies-anime',accessible:true}]},destinations=await value.service.context('movie',expanded),anime=destinations.find(item=>item.rootFolderPath==='/movies-anime');assert.ok(anime);assert.equal(anime.discovered,true);assert.equal(anime.ready,true);assert.equal(anime.isDefault,false);}finally{await rm(value.directory,{recursive:true,force:true});}});

test('unchecked movie and television destinations are not promoted to defaults',async()=>{const value=await fixture();try{const movie=await value.service.save({domain:'movie',name:'Movies',rootFolderPath:'/movies',qualityProfileId:1,isDefault:false},movieContext),tvContext={roots:[{id:1,path:'/shows',accessible:true}],profiles:[{id:8,name:'Television'}],plexLibraries:[]},tv=await value.service.save({domain:'tv',name:'Shows',rootFolderPath:'/shows',qualityProfileId:8,isDefault:false},tvContext),movies=await value.service.context('movie',movieContext),shows=await value.service.context('tv',tvContext);assert.equal(movie.isDefault,false);assert.equal(tv.isDefault,false);assert.equal(movies.find(item=>item.id===movie.id)?.isDefault,false);assert.equal(shows.find(item=>item.id===tv.id)?.isDefault,false);}finally{await rm(value.directory,{recursive:true,force:true});}});

test('separate engine instances may use the same destination name and root with independent defaults',async()=>{const value=await fixture();try{const first=await value.service.save({domain:'movie',engineInstanceId:'radarr-hd',name:'Movies',rootFolderPath:'/movies',qualityProfileId:1,isDefault:true},movieContext),second=await value.service.save({domain:'movie',engineInstanceId:'radarr-4k',name:'Movies',rootFolderPath:'/movies',qualityProfileId:2,isDefault:true},movieContext),hd=await value.service.context('movie',{...movieContext,engineInstanceId:'radarr-hd'}),ultra=await value.service.context('movie',{...movieContext,engineInstanceId:'radarr-4k'});assert.equal(hd.find(item=>item.id===first.id)?.isDefault,true);assert.equal(ultra.find(item=>item.id===second.id)?.isDefault,true);assert.equal(hd.some(item=>item.id===second.id),false);assert.equal(ultra.some(item=>item.id===first.id),false);}finally{await rm(value.directory,{recursive:true,force:true});}});

test('legacy destinations belong only to the default instance context',async()=>{const value=await fixture();try{await value.service.save({domain:'movie',name:'Legacy',rootFolderPath:'/movies',qualityProfileId:1,isDefault:true},movieContext);const primary=await value.service.context('movie',{...movieContext,engineInstanceId:'primary',includeLegacy:true}),secondary=await value.service.context('movie',{...movieContext,engineInstanceId:'secondary',includeLegacy:false});assert.equal(primary.some(item=>item.name==='Legacy'&&item.engineInstanceId==='primary'),true);assert.equal(secondary.some(item=>item.name==='Legacy'),false);}finally{await rm(value.directory,{recursive:true,force:true});}});

test('one Plex library cannot be ambiguously mapped across engine instances',async()=>{const value=await fixture();try{await value.service.save({domain:'movie',engineInstanceId:'radarr-hd',name:'HD',rootFolderPath:'/movies',qualityProfileId:1,plexLibraryKey:'10'},movieContext);await assert.rejects(()=>value.service.save({domain:'movie',engineInstanceId:'radarr-4k',name:'4K',rootFolderPath:'/movies-4k',qualityProfileId:2,plexLibraryKey:'10'},movieContext),/already mapped to another engine instance/);await value.service.save({domain:'movie',engineInstanceId:'radarr-4k',name:'4K',rootFolderPath:'/movies-4k',qualityProfileId:2,plexLibraryKey:'11'},movieContext);}finally{await rm(value.directory,{recursive:true,force:true});}});
