import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {mkdtemp,access,unlink,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {PassThrough} from 'node:stream';
import test from 'node:test';
import {TrailerDownloadService,sanitizeTrailerUrl} from '../packages/platform/src/trailer-download-service.js';

const fakeSpawn=(calls,output='/movies/Movie/Movie - Trailer.mp4')=>(binary,args)=>{calls.push({binary,args});const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.kill=()=>{};queueMicrotask(()=>{child.stdout.end(args[0]==='--version'?'2026.08.01\n':`${output}\n`);child.stderr.end();child.emit('close',0)});return child;};

test('trailer downloader reports yt-dlp and builds a bounded official trailer command',async()=>{const calls=[],root=await mkdtemp(join(tmpdir(),'vynodearr-movies-')),output=join(root,'A Movie (2026) [tmdb-42]','A Movie (2026).mp4'),service=new TrailerDownloadService({root,spawnImpl:fakeSpawn(calls,output)}),status=await service.status(),result=await service.download({url:'https://www.youtube.com/watch?v=abc',title:'A Movie',year:2026,domain:'movie',tmdbId:42});assert.equal(status.available,true);assert.equal(status.version,'2026.08.01');assert.equal(result.tmdbId,42);assert.match(result.folder,/A Movie \(2026\) \[tmdb-42\]$/);assert.deepEqual(calls[1].args.slice(0,4),['--no-playlist','--no-overwrites','--max-filesize','1G']);assert.ok(calls[1].args.includes('bv*[height<=1080]+ba/b[height<=1080]'));assert.match(calls[1].args[calls[1].args.indexOf('--output')+1],/A Movie \(2026\)\.%\(ext\)s$/);assert.equal(calls[1].args.at(-1),'https://www.youtube.com/watch?v=abc');});
test('trailer downloader accepts a mapped host folder only inside its configured library root',async()=>{const calls=[],root=await mkdtemp(join(tmpdir(),'vynodearr-mapped-')),mapped=join(root,'Plex Movies'),output=join(mapped,'Mapped Movie (2026) [tmdb-7]','Mapped Movie (2026).mp4'),service=new TrailerDownloadService({root,spawnImpl:fakeSpawn(calls,output)}),result=await service.download({url:'https://youtu.be/abc',title:'Mapped Movie',year:2026,domain:'movie',tmdbId:7,root:mapped});assert.equal(result.folder,join(mapped,'Mapped Movie (2026) [tmdb-7]'));await assert.rejects(service.download({url:'https://youtu.be/abc',title:'Outside',domain:'movie',root:join(root,'..','outside')}),/outside the configured library root/);});
test('trailer downloader rejects untrusted and non-HTTPS sources',()=>{assert.throws(()=>sanitizeTrailerUrl('http://youtube.com/watch?v=x'),/trusted/);assert.throws(()=>sanitizeTrailerUrl('https://example.com/video'),/trusted/);});
test('trailer cleanup removes only the managed trailer and preserves real movie files',async()=>{const root=await mkdtemp(join(tmpdir(),'vynodearr-movies-')),service=new TrailerDownloadService({root}),folder=join(root,'Managed Trailer'),trailer=join(folder,'Managed Trailer - Trailer.mp4'),movie=join(folder,'Managed Trailer.mkv');await (await import('node:fs/promises')).mkdir(folder);await writeFile(trailer,'trailer');await writeFile(movie,'movie');await service.remove({folder,path:trailer});await assert.rejects(access(trailer));await access(movie);await assert.rejects(service.remove({folder:join(root,'..','outside'),path:join(root,'..','outside','Trailer.mp4')}),/outside/);});
test('managed trailer existence detects files deleted outside VynodeArr',async()=>{const root=await mkdtemp(join(tmpdir(),'vynodearr-movies-')),service=new TrailerDownloadService({root}),folder=join(root,'Externally Deleted'),trailer=join(folder,'Externally Deleted.mp4');await (await import('node:fs/promises')).mkdir(folder);await writeFile(trailer,'trailer');assert.equal(await service.exists({folder,path:trailer}),true);await unlink(trailer);assert.equal(await service.exists({folder,path:trailer}),false);await assert.rejects(service.exists({folder:join(root,'..','outside'),path:join(root,'..','outside','Trailer.mp4')}),/outside/);});
test('managed movie trailers become retained Plex extras when real media arrives',async()=>{const root=await mkdtemp(join(tmpdir(),'vynodearr-promote-')),service=new TrailerDownloadService({root}),placeholder=join(root,'Movie (2026) [tmdb-42]'),source=join(placeholder,'Movie (2026).mp4'),realFolder=join(root,'Movie (2026)'),real=join(realFolder,'Movie (2026).mkv');await (await import('node:fs/promises')).mkdir(placeholder);await (await import('node:fs/promises')).mkdir(realFolder);await writeFile(source,'trailer');await writeFile(real,'movie');const promoted=await service.promote({folder:placeholder,path:source,domain:'movie',tmdbId:42},{realFile:'/media/Movies/Movie (2026)/Movie (2026).mkv',libraryRoot:'/media/Movies',localRoot:root});assert.equal(promoted.state,'extra');assert.equal(promoted.path,join(realFolder,'Official Trailer-trailer.mp4'));await access(promoted.path);await assert.rejects(access(source));});
test('managed television trailers become show-level Plex extras',async()=>{const root=await mkdtemp(join(tmpdir(),'vynodearr-tv-promote-')),service=new TrailerDownloadService({movieRoot:root,tvRoot:root}),placeholder=join(root,'Series (2026) [tmdb-7]'),source=join(placeholder,'Series (2026).mp4'),season=join(root,'Series (2026)','Season 01'),episode=join(season,'Series - S01E01.mkv');await (await import('node:fs/promises')).mkdir(placeholder);await (await import('node:fs/promises')).mkdir(season,{recursive:true});await writeFile(source,'trailer');await writeFile(episode,'episode');const promoted=await service.promote({folder:placeholder,path:source,domain:'tv',tmdbId:7},{realFile:'/media/TV/Series (2026)/Season 01/Series - S01E01.mkv',libraryRoot:'/media/TV',localRoot:root});assert.equal(promoted.path,join(root,'Series (2026)','Trailers','Official Trailer-trailer.mp4'));await access(promoted.path);});
