import assert from 'node:assert/strict';
import {EventEmitter} from 'node:events';
import {mkdtemp,access,unlink,writeFile} from 'node:fs/promises';
import {join} from 'node:path';
import {tmpdir} from 'node:os';
import {PassThrough} from 'node:stream';
import test from 'node:test';
import {TrailerDownloadService,sanitizeTrailerUrl} from '../packages/platform/src/trailer-download-service.js';

const fakeSpawn=(calls,output='/movies/Movie/Movie - Trailer.mp4')=>(binary,args)=>{calls.push({binary,args});const child=new EventEmitter();child.stdout=new PassThrough();child.stderr=new PassThrough();child.kill=()=>{};queueMicrotask(()=>{child.stdout.end(args[0]==='--version'?'2026.08.01\n':`${output}\n`);child.stderr.end();child.emit('close',0)});return child;};

test('trailer downloader reports yt-dlp and builds a bounded official trailer command',async()=>{const calls=[],root=await mkdtemp(join(tmpdir(),'vynodearr-movies-')),output=join(root,'A Movie (2026) [tmdb-42]','A Movie (2026).mp4'),service=new TrailerDownloadService({root,spawnImpl:fakeSpawn(calls,output)}),status=await service.status(),result=await service.download({url:'https://www.youtube.com/watch?v=abc',title:'A Movie',year:2026,domain:'movie',tmdbId:42});assert.equal(status.available,true);assert.equal(status.version,'2026.08.01');assert.equal(result.tmdbId,42);assert.match(result.folder,/A Movie \(2026\) \[tmdb-42\]$/);assert.deepEqual(calls[1].args.slice(0,4),['--no-playlist','--no-overwrites','--max-filesize','1G']);assert.ok(calls[1].args.includes('bv*[height<=1080]+ba/b[height<=1080]'));assert.match(calls[1].args[calls[1].args.indexOf('--output')+1],/A Movie \(2026\)\.%\(ext\)s$/);assert.equal(calls[1].args.at(-1),'https://www.youtube.com/watch?v=abc');});
test('trailer downloader rejects untrusted and non-HTTPS sources',()=>{assert.throws(()=>sanitizeTrailerUrl('http://youtube.com/watch?v=x'),/trusted/);assert.throws(()=>sanitizeTrailerUrl('https://example.com/video'),/trusted/);});
test('trailer cleanup removes only the managed trailer and preserves real movie files',async()=>{const root=await mkdtemp(join(tmpdir(),'vynodearr-movies-')),service=new TrailerDownloadService({root}),folder=join(root,'Managed Trailer'),trailer=join(folder,'Managed Trailer - Trailer.mp4'),movie=join(folder,'Managed Trailer.mkv');await (await import('node:fs/promises')).mkdir(folder);await writeFile(trailer,'trailer');await writeFile(movie,'movie');await service.remove({folder,path:trailer});await assert.rejects(access(trailer));await access(movie);await assert.rejects(service.remove({folder:join(root,'..','outside'),path:join(root,'..','outside','Trailer.mp4')}),/outside/);});
test('managed trailer existence detects files deleted outside VynodeArr',async()=>{const root=await mkdtemp(join(tmpdir(),'vynodearr-movies-')),service=new TrailerDownloadService({root}),folder=join(root,'Externally Deleted'),trailer=join(folder,'Externally Deleted.mp4');await (await import('node:fs/promises')).mkdir(folder);await writeFile(trailer,'trailer');assert.equal(await service.exists({folder,path:trailer}),true);await unlink(trailer);assert.equal(await service.exists({folder,path:trailer}),false);await assert.rejects(service.exists({folder:join(root,'..','outside'),path:join(root,'..','outside','Trailer.mp4')}),/outside/);});
