import {useMemo,useState,type FormEvent} from 'react';
import type {AuthenticationMountOptions,AuthResult} from './authentication-types';
import {errorMessage} from './shell-utils';

const message=(reason:unknown)=>errorMessage(reason,'VynodeArr could not complete authentication.');
const scorePassword=(value:string)=>[value.length>=12,/[a-z]/.test(value)&&/[A-Z]/.test(value),/\d/.test(value),/[^A-Za-z0-9]/.test(value)].filter(Boolean).length;

export function SetupView({options}:{options:AuthenticationMountOptions}){
 const [password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),score=useMemo(()=>scorePassword(password),[password]);
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError('');setBusy(true);const data=Object.fromEntries(new FormData(event.currentTarget));try{if(data.password!==data.confirmPassword)throw new Error('Passwords do not match.');const result=await options.request<AuthResult>('/api/auth/setup',{method:'POST',body:JSON.stringify(data)});options.onAuthenticated(result,true);}catch(reason){setError(message(reason));}finally{setBusy(false);}};
 return <div className="wizard-panel"><div className="wizard-aside"><div className="brand"><img className="brand-mark" src="/art/vynodearr-icon.png" alt=""/><span>VynodeArr</span></div><span className="eyebrow">WELCOME TO VYNODEARR</span><h1>Your media starts here.</h1><p>Create the administrator who will own this VynodeArr installation.</p><ol><li className="complete">Welcome</li><li className="active">Create Administrator</li><li>Connect Engines</li></ol></div><div className="wizard-form"><span className="step-count">STEP 1 OF 2</span><h2>Create Administrator</h2><p>Use a strong password. Your account stays local to this installation.</p>
  <form onSubmit={event=>void submit(event)}><div className="form-grid"><label>Display name<input name="name" autoComplete="name" required minLength={2}/></label><label>Username<input name="username" autoComplete="username" required minLength={3}/></label></div><label>Email<input name="email" type="email" autoComplete="email" required/></label><div className="form-grid"><label>Password<input name="password" type="password" autoComplete="new-password" required minLength={12} value={password} onChange={event=>setPassword(event.target.value)}/><span className="strength" data-score={score}>{['Too short','Add mixed case and a number','Fair','Strong','Excellent'][score]}</span></label><label>Confirm password<input name="confirmPassword" type="password" autoComplete="new-password" required minLength={12}/></label></div><p className="form-error" role="alert">{error}</p><button className="primary" disabled={busy} type="submit">{busy?'Creating administrator…':'Create administrator and continue'}</button></form>
 </div></div>;
}

export function SignInView({options}:{options:AuthenticationMountOptions}){
 const [error,setError]=useState(options.sessionMessage()),[busy,setBusy]=useState(false);
 const submit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();setError('');setBusy(true);const values=Object.fromEntries(new FormData(event.currentTarget)),data={identifier:String(values.identifier||''),password:String(values.password||''),remember:values.remember==='on'};try{const result=await options.request<AuthResult>('/api/auth/login',{method:'POST',body:JSON.stringify(data)});options.onAuthenticated(result,false);}catch(reason){setError(message(reason));}finally{setBusy(false);}};
 return <div className="auth-panel"><div className="brand"><img className="brand-mark" src="/art/vynodearr-icon.png" alt=""/><span>VynodeArr</span></div><span className="eyebrow">WELCOME BACK</span><h1>Sign in</h1><p>Continue to your unified Movies and TV library.</p><form onSubmit={event=>void submit(event)}><label>Username or email<input name="identifier" autoComplete="username" required/></label><label>Password<input name="password" type="password" autoComplete="current-password" required/></label><div className="login-options"><label className="check"><input name="remember" type="checkbox"/> Remember me</label><button type="button" className="text-button" onClick={()=>setError('Password recovery will be available in a future release. Contact your administrator.')}>Forgot password?</button></div><p className="form-error" role="alert">{error}</p><button className="primary" disabled={busy} type="submit">{busy?'Signing in…':'Sign in'}</button></form></div>;
}
