import {useCallback,useEffect,useMemo,useState} from 'react';
import {ModalPortal} from './modal-portal';
import type {Catalog,CustomFormat,GuideTemplatesMountOptions,ResourceType,TemplateChangePlan,TemplateDetail,TemplateDomain,TemplateSummary} from './guide-templates-types';
import {addCustomFormatsToken,customFormatsToken,namingHasCustomFormatsToken,type NamingSettings} from './custom-format-naming';
import {ServiceTabs} from './service-tabs';
import {EngineInstanceSelect,useEngineInstance} from './engine-instance-control';
import './react-guide-templates.css';
import './react-guide-template-families.css';

const errorText=(value:unknown)=>value instanceof Error?value.message:'The guide catalog could not be loaded.';
const short=(value?:string)=>value?.slice(0,8)||'unknown';
const types:Array<[ResourceType,string,string]>=[['customFormat','Custom formats','Selection Rules'],['customFormatGroup','Format groups','Selection Rules'],['qualityProfile','Quality profiles','Quality Profiles'],['qualitySize','Quality size','Quality Profiles'],['naming','Naming','Media Management']];
const destination:Record<ResourceType,string>={customFormat:'#service/custom-formats',customFormatGroup:'#service/custom-formats',qualityProfile:'#service/profiles',qualitySize:'#service/profiles',naming:'#service/media-management'};
export function GuideTemplatesView({options}:{options:GuideTemplatesMountOptions}){
  const availableTypes=types.filter(([id])=>!options.initialTypes?.length||options.initialTypes.includes(id));
  const [catalog,setCatalog]=useState<Catalog|null>(null),[domain,setDomain]=useState<TemplateDomain>(options.initialDomain||'movie'),[type,setType]=useState<ResourceType>(options.initialTypes?.[0]||'customFormat'),[purpose,setPurpose]=useState('all'),[query,setQuery]=useState(''),[selected,setSelected]=useState<TemplateDetail|null>(null),[draft,setDraft]=useState<any>(null),[naming,setNaming]=useState<NamingSettings>({}),[profileIds,setProfileIds]=useState<number[]>([]),[scoreSet,setScoreSet]=useState('default'),[plan,setPlan]=useState<TemplateChangePlan|null>(null),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const engine=useEngineInstance(options.request,domain);
  const load=useCallback(async(refresh=false)=>{setLoading(true);setError('');try{setCatalog(await options.request<Catalog>(`/api/guide-templates/catalog${refresh?'?refresh=true':''}`));}catch(reason){setError(errorText(reason));}finally{setLoading(false);}},[options]);
  useEffect(()=>{void load();},[load]);
  const templates=useMemo(()=>{const needle=query.trim().toLowerCase();return(catalog?.templates||[]).filter(item=>item.domain===domain&&item.resourceType===type&&(purpose==='all'||item.purpose===purpose)&&(!needle||`${item.title} ${item.familyLabel}`.toLowerCase().includes(needle)));},[catalog,domain,type,purpose,query]);
  const open=async(item:TemplateSummary)=>{setBusy(true);try{const [detail,namingValue]=await Promise.all([options.request<TemplateDetail>(engine.route(`/api/guide-templates/templates/${item.id}`)),options.request<{result:NamingSettings}>(engine.route(`/api/manage/${item.domain}/naming`))]);setSelected(detail);setDraft(structuredClone(detail.format||detail.template||{}));setNaming(namingValue.result||{});setProfileIds([]);setPlan(null);setScoreSet(Object.keys(detail.scores||{})[0]||'default');}catch(reason){options.notify(errorText(reason),'error');}finally{setBusy(false);}};
  const ensureNamingToken=async()=>{if(!selected||!window.confirm(`Add ${customFormatsToken} to the active ${selected.domain==='movie'?'movie':'TV episode'} filename formats?`))return;setBusy(true);try{const updated=addCustomFormatsToken(selected.domain,naming);await options.request(engine.route(`/api/manage/${selected.domain}/naming`),{method:'PUT',body:JSON.stringify(updated)});setNaming(updated);options.notify(`${customFormatsToken} added to ${selected.domain==='movie'?'movie':'TV episode'} naming formats.`);}catch(reason){options.notify(errorText(reason),'error');}finally{setBusy(false);}};
  const decisionBody=(decision:'implement'|'reject')=>{const body:any={decision,profileIds,scoreSet,engineInstanceId:engine.instanceId||undefined};if(selected?.resourceType==='customFormat')body.format=draft;else if(selected?.resourceType==='qualitySize')body.qualities=draft.qualities;else if(selected?.resourceType==='customFormatGroup')body.customFormatIds=(draft.custom_formats||[]).filter((item:any)=>item.selected??item.required??item.default).map((item:any)=>item.trash_id);else body.reviewed=draft;return body;};
  const apply=async(decision:'implement'|'reject',confirmed=false)=>{if(!selected)return;setBusy(true);try{const body=decisionBody(decision);if(decision==='implement'&&!confirmed){body.preview=true;const result=await options.request<{plan:TemplateChangePlan}>(`/api/guide-templates/templates/${selected.id}/decision`,{method:'POST',body:JSON.stringify(body)});setPlan(result.plan);return;}if(confirmed)body.confirmOverwrite=true;const result=await options.request<{message:string}>(`/api/guide-templates/templates/${selected.id}/decision`,{method:'POST',body:JSON.stringify(body)});options.notify(result.message);setSelected(null);setPlan(null);}catch(reason){options.notify(errorText(reason),'error');}finally{setBusy(false);}};
  const profiles=selected?.resourceType==='customFormat'?(selected.qualityProfiles||[]):((selected?.engine?.profiles||[]) as Array<any>);
  return <div className="guide-templates-route">
    <div className="hero"><div><span className="eyebrow">ENGINE-NATIVE RECOMMENDATIONS</span><h1>Guide Templates</h1><p className="lede">Review, customize, and apply TRaSH recommendations through the setting they actually control.</p></div><button className="secondary" disabled={loading} onClick={()=>void load(true)}>{loading?'Checking…':'Check for updates'}</button></div>
    <ServiceTabs active="guide-templates"/>
    {engine.instances.length?<div className="settings-context-bar"><EngineInstanceSelect instances={engine.instances} value={engine.instanceId} onChange={value=>{engine.setInstanceId(value);setSelected(null);setPlan(null);}}/></div>:null}
    <section className="guide-source-strip"><div><strong>TRaSH Guides · {domain==='movie'?'Movies':'TV'} templates</strong><span>{catalog?`Revision ${short(catalog.revision)} · ${catalog.templates.filter(item=>item.domain===domain).length} templates`:'Catalog not loaded'}</span></div><div className="template-domain-switch" role="group" aria-label="Template engine"><button className={domain==='movie'?'active':''} onClick={()=>{setDomain('movie');setPurpose('all');}}>Movies</button><button className={domain==='tv'?'active':''} onClick={()=>{setDomain('tv');setPurpose('all');}}>TV</button></div><a href={domain==='movie'?'https://trash-guides.info/%52adarr/':'https://trash-guides.info/%53onarr/'} target="_blank" rel="noreferrer">Open source guide ↗</a></section>
    <nav className="template-family-tabs">{availableTypes.map(([id,label,place])=><button className={type===id?'active':''} key={id} onClick={()=>{setType(id);setPurpose('all');}}><strong>{label}</strong><small>{place}</small><span>{catalog?.templates.filter(item=>item.domain===domain&&item.resourceType===id).length||0}</span></button>)}</nav>
    {error?<div className="panel error-state"><p>{error}</p></div>:loading&&!catalog?<div className="panel skeleton">Loading guide catalog…</div>:<section className="template-browser">
      <div className="template-toolbar"><div><h2>{types.find(item=>item[0]===type)?.[1]}</h2><p className="muted">Applied settings will appear under <a href={destination[type]}>{types.find(item=>item[0]===type)?.[2]}</a>.</p></div><label>Find a template<input type="search" value={query} onChange={event=>setQuery(event.target.value)}/></label></div>
      {type==='customFormat'?<div className="purpose-chips"><button className={purpose==='all'?'active':''} onClick={()=>setPurpose('all')}>All</button>{catalog?.purposes.map(item=><button className={purpose===item.id?'active':''} key={item.id} onClick={()=>setPurpose(item.id)}>{item.label}</button>)}</div>:null}
      <div className="template-grid">{templates.map(item=>{const profileSlug=item.id.split('--profile--')[1]||'',group=item.resourceType==='qualityProfile'?catalog?.coordination[domain]?.profileGroups.find(value=>Object.hasOwn(value.profiles,profileSlug))?.name:null;return <button className="template-card panel" key={item.id} onClick={()=>void open(item)}><span className="template-kind">{group||item.familyLabel.toUpperCase()}</span><strong>{item.title}</strong><small>Review and customize {domain==='movie'?'movie':'TV'} engine changes</small><span className="review-link">Review →</span></button>;})}</div>
    </section>}
    {selected?<ModalPortal><div className="template-review-backdrop"><section className="template-review panel" role="dialog" aria-modal="true"><header className="template-review-header"><div className="template-review-title"><span className="eyebrow">{selected.familyLabel}</span><h2>{draft?.name||draft?.type||selected.title}</h2></div><button className="icon-button" aria-label="Close template review" onClick={()=>setSelected(null)}>×</button></header>
      <div className="review-facts"><div><small>Appears under</small><a href={destination[selected.resourceType]}>{types.find(item=>item[0]===selected.resourceType)?.[2]}</a></div><div><small>Resource type</small><strong>{selected.familyLabel}</strong></div><div><small>Source of truth</small><strong>{selected.domain==='movie'?'Movie':'TV'} engine</strong></div><div><small>Revision</small><strong>{short(selected.revision)}</strong></div></div>
      {selected.resourceType==='customFormat'?<CustomFormatEditor domain={selected.domain} value={draft as CustomFormat} naming={naming} busy={busy} onEnsureNamingToken={()=>void ensureNamingToken()} onChange={setDraft}/>:null}
      {selected.resourceType==='naming'?<NamingEditor domain={selected.domain} source={draft} value={draft} onChange={setDraft}/>:null}
      {selected.resourceType==='qualitySize'?<QualitySizeEditor value={draft} onChange={setDraft}/>:null}
      {selected.resourceType==='qualityProfile'?<QualityProfileEditor value={draft} onChange={setDraft}/>:null}
      {selected.resourceType==='customFormatGroup'?<GroupEditor value={draft} conflicts={catalog?.coordination[selected.domain]?.conflicts||[]} onChange={setDraft}/>:null}
      {['customFormat','customFormatGroup'].includes(selected.resourceType)&&profiles.length?<section className="score-review"><h3>Apply scores to quality profiles</h3><p className="control-help">Choose which profiles should use this recommendation. Selecting none leaves profile scores unchanged.</p>{selected.resourceType==='customFormat'?<label>Score set<small>The TRaSH scoring variant and value to apply.</small><select value={scoreSet} onChange={event=>setScoreSet(event.target.value)}>{Object.entries(selected.scores||{}).map(([name,value])=><option key={name} value={name}>{name} ({value})</option>)}</select></label>:null}<div className="profile-choice-grid">{profiles.map((profile:any)=><label className="check" key={profile.id}><input type="checkbox" checked={profileIds.includes(Number(profile.id))} onChange={()=>setProfileIds(current=>current.includes(Number(profile.id))?current.filter(id=>id!==Number(profile.id)):[...current,Number(profile.id)])}/><span><strong>{profile.name}</strong><small>{profile.currentScore==null?'Select to apply the score':`Current score ${profile.currentScore}`}</small></span></label>)}</div></section>:null}
      {plan?<ChangePreview plan={plan}/>:null}
      <footer className="template-review-footer"><div><a href={selected.url} target="_blank" rel="noreferrer">View upstream JSON ↗</a><small>{plan?'The engine was checked again. Review these changes before applying.':'Only engine configuration changes. Media files are not altered.'}</small></div>{plan?<button className="secondary" disabled={busy} onClick={()=>setPlan(null)}>Back</button>:<button className="secondary" disabled={busy} onClick={()=>void apply('reject')}>Reject</button>}<button className="primary" disabled={busy||Boolean(plan&&!plan.hasChanges)} onClick={()=>void apply('implement',Boolean(plan))}>{busy?'Checking…':plan?(plan.requiresConfirmation?'Confirm overwrite and apply':'Confirm and apply'):'Review engine changes'}</button></footer>
    </section></div></ModalPortal>:null}
  </div>;
}

function ChangePreview({plan}:{plan:TemplateChangePlan}){const value=(item:any)=>{const text=typeof item==='string'?item:JSON.stringify(item);return text.length>180?`${text.slice(0,177)}…`:text;};return <section className={`template-change-preview ${plan.requiresConfirmation?'warning':''}`}><h3>{plan.requiresConfirmation?'Confirm changes to existing settings':'Changes to apply'}</h3><p className="control-help">{plan.requiresConfirmation?'Items marked Update already exist in the movie engine and will be overwritten. Nothing changes until you confirm.':'No existing setting will be overwritten.'}</p><div className="template-change-list">{plan.changes.map((change,index)=><article key={`${change.resource}-${change.name}-${index}`}><span className={`change-action ${change.action}`}>{change.action}</span><div><strong>{change.name}</strong><small>{change.resource}</small>{change.details.map(detail=><p key={detail.field}><b>{detail.field}</b>: <del>{value(detail.before)}</del> → <ins>{value(detail.after)}</ins></p>)}</div></article>)}</div>{!plan.hasChanges?<p className="notice">The engine already matches this reviewed template. There is nothing to apply.</p>:null}</section>}

function CustomFormatEditor({domain,value,naming,busy,onEnsureNamingToken,onChange}:{domain:TemplateDomain;value:CustomFormat;naming:NamingSettings;busy:boolean;onEnsureNamingToken:()=>void;onChange:(value:CustomFormat)=>void}){if(!value)return null;const update=(index:number,change:any)=>onChange({...value,specifications:value.specifications.map((item,i)=>i===index?change(item):item)});return <section className="template-customizer"><label>Name<small>The name shown in Custom Formats and profile scoring.</small><input value={value.name} onChange={event=>onChange({...value,name:event.target.value})}/></label><label className="check"><input type="checkbox" checked={value.includeCustomFormatWhenRenaming} onChange={event=>onChange({...value,includeCustomFormatWhenRenaming:event.target.checked})}/><span>Include when renaming<small>Add this custom-format name to renamed files.</small></span></label>{value.includeCustomFormatWhenRenaming&&!namingHasCustomFormatsToken(domain,naming)?<div className="notice warning naming-token-warning"><div><strong>Naming token required</strong><p>Your active {domain==='movie'?'movie':'TV episode'} filename formats do not contain <code>{customFormatsToken}</code>. This custom-format name will not appear in renamed files until the token is added.</p></div><button type="button" className="secondary" disabled={busy} onClick={onEnsureNamingToken}>{busy?'Adding…':'Add to naming formats'}</button></div>:null}<h3>Matching conditions</h3><p className="control-help">Conditions describe how the engine recognizes a release.</p>{value.specifications.map((spec,index)=><article className="editable-condition" key={index}><label>Name<small>A readable label for this condition.</small><input value={String(spec.name||'')} onChange={event=>update(index,(item:any)=>({...item,name:event.target.value}))}/></label><div className="condition-switches"><label className="check" title="The condition's final result must pass"><input type="checkbox" checked={Boolean(spec.required)} onChange={event=>update(index,(item:any)=>({...item,required:event.target.checked}))}/> Required</label><label className="check" title="Reverse the condition's match result"><input type="checkbox" checked={Boolean(spec.negate)} onChange={event=>update(index,(item:any)=>({...item,negate:event.target.checked}))}/> Negated</label></div><p className="control-help condition-help"><strong>Required:</strong> this rule must pass. <strong>Negated:</strong> reverses the rule. When both are selected, the specified value must be absent.</p><details><summary>Advanced matching values</summary><p className="control-help">Engine values such as regular expressions, language IDs, or quality IDs.</p>{Object.entries(spec.fields||{}).map(([name,field])=><label key={name}>{name}<input value={String(field??'')} onChange={event=>update(index,(item:any)=>({...item,fields:{...item.fields,[name]:event.target.value}}))}/></label>)}</details></article>)}</section>}
function NamingEditor({domain,source,value,onChange}:{domain:TemplateDomain;source:any;value:any;onChange:(value:any)=>void}){if(domain==='movie'){const folder=source.folder||{},file=source.file||{};return <section className="template-customizer"><h3>Movie naming presets</h3><label>Movie folder<small>Controls the folder name created for each movie.</small><select onChange={event=>onChange({...value,movieFolderFormat:event.target.value})}><option value="">Choose…</option>{Object.entries(folder).map(([name,format])=><option key={name} value={String(format)}>{name}</option>)}</select></label><label>Movie file<small>Controls how imported movie files are named.</small><select onChange={event=>onChange({...value,standardMovieFormat:event.target.value})}><option value="">Choose…</option>{Object.entries(file).map(([name,format])=><option key={name} value={String(format)}>{name}</option>)}</select></label><label className="check"><input type="checkbox" checked={value.renameMovies!==false} onChange={event=>onChange({...value,renameMovies:event.target.checked})}/><span>Rename movie files<small>Use the selected format during import and manual renaming.</small></span></label></section>}const choices=[['seriesFolderFormat','Series folder',source.series||{}],['seasonFolderFormat','Season folder',source.season||{}],['standardEpisodeFormat','Standard episode',source.episodes?.standard||{}],['dailyEpisodeFormat','Daily episode',source.episodes?.daily||{}],['animeEpisodeFormat','Anime episode',source.episodes?.anime||{}]];return <section className="template-customizer"><h3>TV naming presets</h3><p className="control-help">Choose how series folders, seasons, and each episode type should be named.</p>{choices.map(([field,label,formats]:any)=><label key={field}>{label}<small>The naming format used by the TV engine.</small><select onChange={event=>onChange({...value,[field]:event.target.value})}><option value="">Keep current engine value</option>{Object.entries(formats).map(([name,format])=><option key={name} value={String(format)}>{name}</option>)}</select></label>)}<label className="check"><input type="checkbox" checked={value.renameEpisodes!==false} onChange={event=>onChange({...value,renameEpisodes:event.target.checked})}/><span>Rename episode files<small>Use the selected formats during import and manual renaming.</small></span></label></section>}
function QualitySizeEditor({value,onChange}:{value:any;onChange:(value:any)=>void}){const labels:{[key:string]:string}={min:'Minimum',preferred:'Preferred',max:'Maximum'};return <section className="template-customizer"><h3>{value.type} size limits</h3><p className="control-help">Values are megabytes per minute. Minimum rejects undersized releases; preferred is the target; maximum rejects oversized releases.</p><div className="quality-template-grid">{(value.qualities||[]).map((item:any,index:number)=><article key={item.quality}><strong>{item.quality}</strong>{['min','preferred','max'].map(key=><label key={key}>{labels[key]}<input type="number" value={item[key]} onChange={event=>{const qualities=structuredClone(value.qualities);qualities[index][key]=Number(event.target.value);onChange({...value,qualities});}}/></label>)}</article>)}</div></section>}
function QualityProfileEditor({value,onChange}:{value:any;onChange:(value:any)=>void}){const thresholds=[['minFormatScore','Minimum accepted score','Reject releases below this total score.'],['cutoffFormatScore','Upgrade-until score','Stop score-based upgrades after reaching this value.'],['minUpgradeFormatScore','Minimum upgrade gain','Require at least this score improvement to upgrade.']];return <section className="template-customizer"><label>Profile name<small>The name shown when adding or editing movies.</small><input value={value.name||''} onChange={event=>onChange({...value,name:event.target.value})}/></label><div className="form-grid three">{thresholds.map(([key,label,help])=><label key={key}>{label}<small>{help}</small><input type="number" value={value[key]||0} onChange={event=>onChange({...value,[key]:Number(event.target.value)})}/></label>)}</div><h3>Allowed qualities</h3><p className="control-help">Checked qualities may be downloaded. Their displayed order controls upgrade preference.</p><div className="profile-template-items">{(value.items||[]).map((item:any)=><label className="check" key={item.name}><input type="checkbox" checked={Boolean(item.allowed)} readOnly/><span><strong>{item.name}</strong><small>{item.items?.join(', ')||'Native quality'}</small></span></label>)}</div><p className="muted">{Object.keys(value.formatItems||{}).length} referenced custom formats will be installed and scored automatically.</p></section>}
function GroupEditor({value,conflicts,onChange}:{value:any;conflicts:Array<Record<string,{name:string;desc?:string}>>;onChange:(value:any)=>void}){const selected=new Set((value.custom_formats||[]).filter((item:any)=>item.selected??item.required??item.default).map((item:any)=>item.trash_id));const warnings=conflicts.filter(group=>Object.keys(group).filter(id=>selected.has(id)).length>1);return <section className="template-customizer"><h3>{value.name}</h3><p>{value.trash_description}</p>{warnings.map((warning,index)=><div className="notice warning" key={index}><strong>Conflicting choices</strong><p>{Object.values(warning).map(item=>item.name).join(' and ')} should not be enabled together.</p></div>)}<div className="profile-template-items">{(value.custom_formats||[]).map((item:any,index:number)=><label className="check" key={item.trash_id}><input type="checkbox" checked={Boolean(item.selected??item.required??item.default)} disabled={Boolean(item.required)} onChange={event=>{const custom_formats=structuredClone(value.custom_formats);custom_formats[index].selected=event.target.checked;onChange({...value,custom_formats});}}/><span><strong>{item.name}</strong><small>{item.required?'Required':'Optional'}</small></span></label>)}</div></section>}
