import { useEffect,useMemo,useRef,useState } from 'react';
import type { LibraryItem,LibraryMountOptions,LibraryView } from './library-types';
import './react-library.css';

const views:LibraryView[]=['poster','cards','compact','list'];
const viewLabels:Record<LibraryView,string>={poster:'Poster grid',cards:'Information cards',compact:'Compact grid',list:'Detailed list'};

function LibraryCard({item,kind,view,onMonitor,onPrefetch}:{item:LibraryItem;kind:LibraryMountOptions['kind'];view:LibraryView;onMonitor:(item:LibraryItem)=>Promise<void>;onPrefetch:(item:LibraryItem)=>void}){
  const movie=kind==='movies',href=`#${movie?'movie':'series'}/${item.id}`,attention=movie?item.state!=='available':item.monitoring!=='none'&&Number(item.missingEpisodes||0)>0;
  const status=movie?(item.state==='available'?'Available':item.state||'Unknown'):item.status||'Unknown';
  const context=movie?item.collection:item.network,quality=movie?(item.quality||item.qualityProfile||'Quality unknown'):(item.episodeProgress||'Episode count unknown');
  const episodeCounts=String(item.episodeProgress||'').match(/(\d+)\s*\/\s*(\d+)/),episodePercent=episodeCounts&&Number(episodeCounts[2])>0?Number(episodeCounts[1])/Number(episodeCounts[2])*100:Math.max(0,100-Number(item.missingEpisodes||0)*5);
  const details=movie
    ?[['Quality',item.quality||item.qualityProfile||'Not reported'],['Collection',item.collection||'None'],['Rating',item.rating?`${item.rating.toFixed(1)} / 10`:'Not rated'],['Genres',item.genres?.slice(0,3).join(', ')||'Not specified']]
    :[['Episodes',item.episodeProgress||'Not reported'],['Seasons',item.seasonProgress||'Not reported'],['Network',item.network||'Not specified'],['Genres',item.genres?.slice(0,3).join(', ')||'Not specified']];
  const prefetch=()=>{window.VynodeArrReact?.preloadRoute?.(movie?'movie':'series');onPrefetch(item);};
  return <article className={`card react-library-card ${view}`} onPointerEnter={prefetch} onFocus={prefetch}>
    <a className="poster" href={href}>{item.artwork?.url?<img src={item.artwork.url} alt="" loading="lazy"/>:<span className="art-fallback">{movie?'M':'TV'}</span>}<span className="poster-badges"><span className={`badge ${item.monitoring==='none'?'':'green'}`}>{item.monitoring==='none'?'Unmonitored':'Monitored'}</span><span className={`badge ${attention?'warm':''}`}>{status}</span></span>{view==='poster'?<span className="react-poster-title"><strong>{item.title}</strong><span>{[item.year,context].filter(Boolean).join(' · ')||quality}</span>{item.rating?<em aria-label={`Rating ${item.rating.toFixed(1)} out of 10`}>★ {item.rating.toFixed(1)}</em>:null}</span>:null}</a>
    <div className="card-body"><h2><a href={href}>{item.title}</a></h2><p>{[item.year,context].filter(Boolean).join(' · ')}</p>
      <div className="progress"><span style={{width:movie?(item.hasFile?'100%':'0%'):`${Math.min(100,episodePercent)}%`}}/></div>
      <div className="detail-row"><span>{quality}</span><span>{movie?(item.hasFile?'On disk':'Missing'):`${Number(item.missingEpisodes||0)} missing`}</span></div>
      {view==='cards'?<p className="react-library-overview">{item.overview||'No summary is available yet.'}</p>:null}
      <dl className="react-library-list-details">{details.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>
      <footer className="react-library-card-actions"><a className="secondary react-library-details" href={href}>Details</a><button className="secondary" type="button" onClick={()=>void onMonitor(item)}>{item.monitoring==='none'?'Monitor':'Unmonitor'}</button></footer>
    </div>
  </article>;
}

export function LibraryView({options}:{options:LibraryMountOptions}){
  const {kind,request,notify}=options,movie=kind==='movies';
  const storageKey=`vynodearr.libraryState.${kind}`,saved=useMemo(()=>{try{return JSON.parse(sessionStorage.getItem(storageKey)||'{}') as {filter?:string;sort?:string;query?:string;scrollY?:number};}catch{return{};}},[storageKey]);
  const [items,setItems]=useState(options.items),[filter,setFilter]=useState(saved.filter||'all'),[sort,setSort]=useState(saved.sort||'title'),[query,setQuery]=useState(saved.query||''),[debouncedQuery,setDebouncedQuery]=useState(saved.query||''),[view,setView]=useState(options.initialView),[limit,setLimit]=useState(120),[searching,setSearching]=useState(false);
  const loadMoreRef=useRef<HTMLDivElement|null>(null);
  useEffect(()=>{const timer=window.setTimeout(()=>setDebouncedQuery(query),200);return()=>window.clearTimeout(timer);},[query]);
  useEffect(()=>{setLimit(120);},[filter,sort,debouncedQuery,view]);
  useEffect(()=>{const persist=()=>sessionStorage.setItem(storageKey,JSON.stringify({filter,sort,query,scrollY:window.scrollY}));persist();window.addEventListener('scroll',persist,{passive:true});return()=>{persist();window.removeEventListener('scroll',persist);};},[storageKey,filter,sort,query]);
  useEffect(()=>{const y=Number(saved.scrollY||0);if(y)requestAnimationFrame(()=>window.scrollTo({top:y}));},[]);
  const visible=useMemo(()=>items.filter(item=>item.title.toLowerCase().includes(debouncedQuery.toLowerCase())).filter(item=>filter==='all'||filter==='monitored'&&item.monitoring!=='none'||filter==='missing'&&item.monitoring!=='none'&&(movie?item.state==='missing':Number(item.missingEpisodes||0)>0)||filter==='cutoff'&&movie&&item.monitoring!=='none'&&item.state==='cutoff').sort((a,b)=>sort==='year'?Number(b.year||0)-Number(a.year||0):sort==='attention'?(movie?Number(a.state==='available')-Number(b.state==='available'):Number(b.missingEpisodes||0)-Number(a.missingEpisodes||0)):a.title.localeCompare(b.title)),[items,filter,sort,debouncedQuery,movie]);
  useEffect(()=>{const node=loadMoreRef.current;if(!node||limit>=visible.length||!('IntersectionObserver'in window))return;const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting))setLimit(value=>value+120);},{rootMargin:'600px'});observer.observe(node);return()=>observer.disconnect();},[limit,visible.length]);
  const monitored=items.filter(item=>item.monitoring!=='none'),missing=monitored.filter(item=>movie?item.state==='missing':Number(item.missingEpisodes||0)>0).length,cutoff=movie?monitored.filter(item=>item.state==='cutoff').length:0,coverage=Math.round(items.filter(item=>movie?item.hasFile:Number(item.missingEpisodes||0)===0).length/Math.max(items.length,1)*100);
  async function monitor(item:LibraryItem){const domain=movie?'movie':'tv',engineId=item.id.replace(movie?'movie_':'series_','');try{const value=await request<{result:Record<string,unknown>}>(`/api/manage/${domain}/library/${engineId}`),raw=value.result;raw.monitored=!raw.monitored;await request(`/api/manage/${domain}/library/${engineId}`,{method:'PUT',body:JSON.stringify(raw)});setItems(current=>current.map(value=>value.id===item.id?{...value,monitoring:raw.monitored?(movie?'monitored':'all'):'none'}:value));notify(raw.monitored?`${movie?'Movie':'Series'} monitored.`:`${movie?'Movie':'Series'} unmonitored.`);}catch(error){notify(error instanceof Error?error.message:'The monitoring change failed.','error');}}
  async function searchAllMissing(){const ids=visible.filter(item=>item.state==='missing'&&item.monitoring!=='none').map(item=>Number(item.id.replace(/^movie_/,''))).filter(Number.isFinite);if(!ids.length)return;setSearching(true);try{for(let index=0;index<ids.length;index+=100)await request('/api/manage/movie/commands',{method:'POST',body:JSON.stringify({name:'MoviesSearch',movieIds:ids.slice(index,index+100)})});notify(`Search queued for ${ids.length} missing movie${ids.length===1?'':'s'}.`);}catch(error){notify(error instanceof Error?error.message:'The missing movie search failed.','error');}finally{setSearching(false);}}
  const prefetch=(item:LibraryItem)=>{void request(movie?`/api/media/movies/${encodeURIComponent(item.id)}`:`/api/media/tv/${encodeURIComponent(item.id)}`).catch(()=>{});};
  function chooseView(next:LibraryView){setView(next);options.onViewChange(next);}
  return <div className="react-library">
    <div className="hero"><div><span className="eyebrow">YOUR LIBRARY</span><h1>{movie?'Movies':'TV'}</h1><p className="lede">{movie?'Every story, presented through one secure gateway.':'Every season and episode, normalized in one library.'}</p></div><span className="read-only">Connected library</span></div>
    <div className="summary"><div><strong>{items.length}</strong><span>Titles</span></div><div><strong>{monitored.length}</strong><span>Monitored</span></div><div><strong>{missing+cutoff}</strong><span>Need attention</span><small>{movie?`${missing} missing · ${cutoff} below cutoff`:`${missing} series missing episodes`}</small></div><div><strong>{coverage}%</strong><span>Library coverage</span></div></div>
    <div className="toolbar react-library-toolbar"><div className="filters">{['all','monitored','missing',...(movie?['cutoff']:[])].map(value=><button key={value} type="button" className={`chip ${filter===value?'selected':''}`} onClick={()=>setFilter(value)}>{value==='cutoff'?'Cutoff unmet':value[0].toUpperCase()+value.slice(1)}</button>)}</div>{movie&&filter==='missing'?<button className="primary react-library-search-missing" disabled={searching||!visible.length} onClick={()=>void searchAllMissing()}>{searching?'Queuing searches…':`Search all missing (${visible.length})`}</button>:null}<label className="react-library-search">Filter titles<input value={query} onChange={event=>setQuery(event.target.value)} placeholder={`Search ${movie?'movies':'television'}`}/></label><div><select className="sort" aria-label="Sort media" value={sort} onChange={event=>setSort(event.target.value)}><option value="title">Title</option><option value="year">Year</option><option value="attention">Attention</option></select>{views.map(value=><button key={value} type="button" className={`icon-button ${view===value?'selected':''}`} title={viewLabels[value]} onClick={()=>chooseView(value)}>{value==='poster'?'▦':value==='cards'?'▥':value==='compact'?'▤':'☷'}</button>)}</div></div>
    <div className={`grid view-${view}`}>{visible.slice(0,limit).map(item=><LibraryCard key={item.id} item={item} kind={kind} view={view} onMonitor={monitor} onPrefetch={prefetch}/>)}</div>
    {!visible.length?<div className="empty"><h2>No titles match</h2><p>Change the search or library filter.</p></div>:null}
    {limit<visible.length?<div className="library-load-more" ref={loadMoreRef}><p>Showing {limit.toLocaleString()} of {visible.length.toLocaleString()}</p><button className="secondary" type="button" onClick={()=>setLimit(value=>value+120)}>Load more</button></div>:null}
  </div>;
}
