import {useEffect,useMemo,useState} from 'react';
import {analyzeDuplicateFolders,classifyImportChoice,scanDate} from './library-import-analysis';
import type {DuplicateDetail,ImportChoice,ImportFolder,ImportRecord} from './library-import-analysis';
import {ModalPortal} from './modal-portal';
import type {RootFolder,RootFoldersMountOptions,StorageDomain} from './root-folders-types';

type Profile={id:number|string;name:string};
type Match={folder:ImportFolder;options:ImportChoice[];selected:number;enabled:boolean;term:string;searching:boolean;expanded:boolean};
type Filter='all'|'unmatched'|'mismatch'|'matched';
const normalizePath=(value:unknown)=>String(value||'').replaceAll('\\','/').replace(/\/+$/,'').toLowerCase();
const message=(reason:unknown)=>reason instanceof Error?reason.message:'Folder scan unavailable.';
const importLookupTerm=(value:string)=>/^tt\d+$/i.test(value)?`imdb:${value.toLowerCase()}`:/^\d+$/.test(value)?`tmdb:${value}`:value;
const choiceIdentity=(choice:ImportChoice)=>choice.imdbId?` · IMDb ${choice.imdbId}`:choice.tmdbId?` · TMDB ${choice.tmdbId}`:'';
async function concurrentMap<T,R>(items:T[],limit:number,worker:(item:T,index:number)=>Promise<R>){
  const result=new Array<R>(items.length);let cursor=0;
  await Promise.all(Array.from({length:Math.min(limit,items.length)},async()=>{for(;;){const index=cursor++;if(index>=items.length)return;result[index]=await worker(items[index],index);}}));
  return result;
}
function DuplicateSummary({detail,path}:{detail?:DuplicateDetail;path:string}){
  if(!detail)return null;
  return <span className="import-duplicate-summary"><span className="badge warm">Possible duplicate</span>{detail.newestPath===path?<span className="badge green">Newest copy</span>:detail.newestPath?<span className="badge">Older copy</span>:null}<small>{detail.timestamp?`Modified ${scanDate(detail.timestamp)}`:'Modification date unavailable'}</small>{detail.entries.filter(entry=>entry.path!==path).map(entry=><small key={entry.path}>{entry.imported?'Already imported':'Also found'}: {entry.path}{detail.newestPath===entry.path?' · newest':''}</small>)}</span>;
}
export function LibraryImportReview({domain,initialRoot,options,onClose,onImported}:{domain:StorageDomain;initialRoot:RootFolder;options:RootFoldersMountOptions;onClose:()=>void;onImported:()=>Promise<void>}){
  const movie=domain==='movie';
  const managed=(path:string)=>initialRoot.engineInstanceId?`${path}${path.includes('?')?'&':'?'}engineInstanceId=${encodeURIComponent(initialRoot.engineInstanceId)}`:path;
  const [root,setRoot]=useState(initialRoot),[profiles,setProfiles]=useState<Profile[]>([]),[records,setRecords]=useState<ImportRecord[]>([]),[imported,setImported]=useState<ImportRecord[]>([]),[matches,setMatches]=useState<Match[]>([]),[duplicates,setDuplicates]=useState<Map<string,DuplicateDetail>>(new Map()),[loading,setLoading]=useState(true),[error,setError]=useState(''),[filter,setFilter]=useState<Filter>('all'),[profileId,setProfileId]=useState(''),[monitored,setMonitored]=useState(true),[monitor,setMonitor]=useState('all'),[seriesType,setSeriesType]=useState('standard'),[submitting,setSubmitting]=useState(false);
  useEffect(()=>{let active=true;void(async()=>{try{
    const initialPath=normalizePath(initialRoot.path),fresh=await options.request<{result?:RootFolder[]}>(managed(`/api/manage/${domain}/rootFolders`)),resolved=(fresh.result||[]).find(candidate=>String(candidate.id)===String(initialRoot.id)||normalizePath(candidate.path)===initialPath)||initialRoot,rootPath=normalizePath(resolved.path);
    const [{result:profileValues=[]},{result:libraryValue=[]}]=await Promise.all([options.request<{result?:Profile[]}>(managed(`/api/manage/${domain}/profiles`)),options.request<{result?:ImportRecord[]|{records?:ImportRecord[]}}>(managed(`/api/manage/${domain}/library`))]),library=Array.isArray(libraryValue)?libraryValue:libraryValue.records||[],inside=library.filter(record=>{const path=normalizePath(record.path);return path===rootPath||path.startsWith(`${rootPath}/`);}).sort((a,b)=>String(a.title||a.path).localeCompare(String(b.title||b.path),undefined,{numeric:true,sensitivity:'base'})),importedPaths=new Set(inside.map(record=>normalizePath(record.path))),folders=[...(resolved.unmappedFolders||[])].filter(folder=>!importedPaths.has(normalizePath(folder.path))).sort((a,b)=>String(a.name||a.path).localeCompare(String(b.name||b.path),undefined,{numeric:true,sensitivity:'base'}));
    const [lookups,duplicateValues]=await Promise.all([concurrentMap(folders,4,folder=>options.request<{result?:ImportChoice[]}>(managed(`/api/manage/${domain}/lookup?term=${encodeURIComponent(folder.name||folder.path)}`)).catch(()=>({result:[]}))),analyzeDuplicateFolders({domain,folders,imported:inside,request:(path,requestOptions)=>options.request(managed(path),requestOptions),mapConcurrent:concurrentMap})]);
    if(!active)return;setRoot(resolved);setProfiles(profileValues);setProfileId(String(profileValues[0]?.id||''));setRecords(library);setImported(inside);setDuplicates(duplicateValues);setMatches(folders.map((folder,index)=>({folder,options:(lookups[index].result||[]).slice(0,8),selected:0,enabled:false,term:folder.name||folder.path,searching:false,expanded:false})));
  }catch(reason){if(active)setError(message(reason));}finally{if(active)setLoading(false);}})();return()=>{active=false;};},[domain,initialRoot,options]);
  const classifications=useMemo(()=>matches.map(match=>classifyImportChoice(match.folder,match.options[match.selected],records,movie)),[matches,records,movie]);
  const visible=matches.map((_,index)=>index).filter(index=>{const value=classifications[index];return filter==='all'||filter==='unmatched'&&value.unmatched||filter==='mismatch'&&!value.unmatched&&(value.titleMismatch||value.yearMismatch||Boolean(value.duplicate))||filter==='matched'&&!value.unmatched&&!value.titleMismatch&&!value.yearMismatch&&!value.duplicate;});
  const selectable=visible.filter(index=>!classifications[index].unmatched),allSelected=Boolean(selectable.length)&&selectable.every(index=>matches[index].enabled),someSelected=selectable.some(index=>matches[index].enabled);
  const update=(index:number,patch:Partial<Match>)=>setMatches(value=>value.map((match,current)=>current===index?{...match,...patch}:match));
  const search=async(index:number)=>{const current=matches[index],term=current.term.trim();if(!term)return;update(index,{searching:true});try{const value=await options.request<{result?:ImportChoice[]}>(managed(`/api/manage/${domain}/lookup?term=${encodeURIComponent(importLookupTerm(term))}`)),choices=(value.result||[]).slice(0,12);update(index,{options:choices,selected:0,enabled:choices.length?current.enabled:false});}catch(reason){options.notify(message(reason),'error');}finally{update(index,{searching:false});}};
  const submit=async()=>{const selected=matches.filter(match=>match.enabled&&match.options[match.selected]);if(!selected.length)return options.notify(`Select at least one matched ${movie?'movie':'series'}.`,'error');const items=selected.map(match=>{const choice=match.options[match.selected],isMonitored=movie?monitored:monitor!=='none';return{title:choice.title||match.folder.name||match.folder.path,payload:{...choice,path:match.folder.path,rootFolderPath:root.path,qualityProfileId:Number(profileId),monitored:isMonitored,...(movie?{minimumAvailability:choice.minimumAvailability==='tba'?'announced':choice.minimumAvailability,addOptions:{searchForMovie:false}}:{seasonFolder:true,seriesType,addOptions:{monitor,searchForMissingEpisodes:false,searchForCutoffUnmetEpisodes:false}})}};});setSubmitting(true);try{await options.startImport(domain,items,root.engineInstanceId);onClose();await onImported();}catch(reason){options.notify(message(reason),'error');setSubmitting(false);}};
  return <ModalPortal><div className="root-folder-browser-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><section className="panel root-folder-browser library-import grouped-library-import" role="dialog" aria-modal="true" aria-label={`Import existing ${movie?'movies':'television'}`}>
    {loading?<div className="empty"><div className="skeleton">Comparing folders with your library…</div></div>:error?<div className="empty error-state"><h2>Folder scan unavailable</h2><p>{error}</p><button className="secondary" onClick={onClose}>Close</button></div>:<><div className="panel-heading"><div><span className="eyebrow">SCAN EXISTING {movie?'MOVIES':'TELEVISION'}</span><h2>{root.path}</h2><p className="muted">{matches.length} not imported · {imported.length} already imported</p></div><button className="secondary" onClick={onClose}>Cancel</button></div>
      <section className="scan-folder-group"><div className="scan-group-heading"><div><h3>Not imported</h3><p>Review and select folders to add. Duplicate labels are informational only.</p></div><span className="badge warm">{matches.length}</span></div>{matches.length?<><div className="import-options"><label>Quality profile<select value={profileId} onChange={event=>setProfileId(event.target.value)}>{profiles.map(profile=><option key={profile.id} value={profile.id}>{profile.name}</option>)}</select></label>{movie?<label className="check"><input type="checkbox" checked={monitored} onChange={event=>setMonitored(event.target.checked)}/> Monitor imported movies</label>:<><label>Monitor<select value={monitor} onChange={event=>setMonitor(event.target.value)}><option value="all">All episodes</option><option value="future">Future episodes</option><option value="missing">Missing episodes</option><option value="none">None</option></select></label><label>Series type<select value={seriesType} onChange={event=>setSeriesType(event.target.value)}><option value="standard">Standard</option><option value="daily">Daily</option><option value="anime">Anime</option></select></label></>}</div>
        <div className="import-review-toolbar"><label className="check"><input type="checkbox" checked={allSelected} ref={element=>{if(element)element.indeterminate=someSelected&&!allSelected;}} onChange={event=>setMatches(value=>value.map((match,index)=>selectable.includes(index)?{...match,enabled:event.target.checked}:match))}/> Select all shown</label><label>Show<select value={filter} onChange={event=>setFilter(event.target.value as Filter)}><option value="all">All folders</option><option value="unmatched">Unmatched only</option><option value="mismatch">Possible mismatches</option><option value="matched">Matched only</option></select></label><span className="import-filter-count">{visible.length} shown</span></div>
        <div className="import-list">{visible.map(index=>{const match=matches[index],classification=classifications[index],mismatch=!classification.unmatched&&(classification.titleMismatch||classification.yearMismatch||classification.duplicate),rowClass=`import-row${classification.unmatched?' import-unmatched':mismatch?' import-mismatch':' import-matched'}${duplicates.has(match.folder.path)?' import-duplicate':''}`;return <article className={rowClass} key={match.folder.path}><label className="check"><input type="checkbox" disabled={!match.options.length} checked={match.enabled} onChange={event=>update(index,{enabled:event.target.checked})}/> Import</label><div><strong>{match.folder.name}</strong><small>{match.folder.path}</small><DuplicateSummary detail={duplicates.get(match.folder.path)} path={match.folder.path}/>{classification.warning?<small className="import-match-warning">{classification.warning}</small>:null}{classification.duplicate?<span className="import-duplicate-summary import-identity-warning"><span className="badge warm">Already imported match</span><small>The selected match is already in the library as {classification.duplicate.title||match.options[match.selected]?.title}{classification.duplicate.year?` (${classification.duplicate.year})`:''}.</small><small>{classification.duplicate.path||'Library path unavailable'}</small></span>:null}</div>{match.options.length?<select className="import-match" value={match.selected} onChange={event=>update(index,{selected:Number(event.target.value)})}>{match.options.map((choice,choiceIndex)=><option key={`${choiceIndex}-${choice.title}`} value={choiceIndex}>{choice.title}{choice.year?` (${choice.year})`:''}{choiceIdentity(choice)}</option>)}</select>:<span className="form-error">No {movie?'movie':'series'} match found</span>}<div className="import-fix-match"><button className="secondary" type="button" onClick={()=>update(index,{expanded:!match.expanded})}>{match.options.length?'Change match':'Find match'}</button>{match.expanded?<div className="import-fix-controls"><input value={match.term} aria-label="Search by title, TMDB ID, or IMDb ID" placeholder="Title, TMDB ID, or tt IMDb ID" onChange={event=>update(index,{term:event.target.value})} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();void search(index);}}}/><button className="secondary" type="button" disabled={match.searching} onClick={()=>void search(index)}>{match.searching?'Searching…':'Search'}</button></div>:null}</div></article>;})}</div></>:<div className="empty compact"><h3>Everything is already imported</h3><p>No new folders were found.</p></div>}</section>
      <details className="scan-folder-group imported-folder-group"><summary><span><strong>Already imported</strong><small>Collapsed for convenience</small></span><span className="badge green">{imported.length}</span></summary><div className="imported-folder-list">{imported.length?imported.map(record=><article className="imported-folder-row" key={record.path}><div><strong>{record.title||record.path}</strong><small>{record.path}</small></div><span className="badge green">Imported</span></article>):<p className="muted">No imported folders in this root.</p>}</div></details><div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Close</button>{matches.length?<button className="primary" type="button" disabled={submitting||!profileId} onClick={()=>void submit()}>{submitting?'Starting import…':`Import selected ${movie?'movies':'series'}`}</button>:null}</div></>}
  </section></div></ModalPortal>;
}
