import {useCallback,useEffect,useState} from 'react';
import type {MediaManagementDomain,MediaManagementMountOptions,MediaSettingField,MediaSettings,NamingAuditJob} from './media-management-types';

const choices:Record<string,Array<[string|number,string]>>={
  colonReplacementFormat:[['delete','Delete'],['dash','Dash'],['spaceDash','Space + dash'],['spaceDashSpace','Space + dash + space'],['smart','Smart replacement']],
  multiEpisodeStyle:[[0,'Extend'],[1,'Duplicate'],[2,'Repeat'],[3,'Scene'],[4,'Range'],[5,'Prefixed range']],
  downloadPropersAndRepacks:[['doNotPrefer','Do not prefer'],['preferAndUpgrade','Prefer and upgrade'],['doNotUpgrade','Prefer, do not upgrade']],
  rescanAfterRefresh:[['always','Always'],['afterManual','After manual refresh'],['never','Never']],
  allowFingerprinting:[['never','Never'],['newFiles','New files only'],['allFiles','All files']],
  fileDate:[['none','Do not change'],['cinemas','Cinema release date'],['release','Release date'],['airDate','Air date']],
  episodeTitleRequired:[['always','Always'],['bulkSeasonReleases','Only for single-episode releases'],['never','Never']]
};
const help:Record<string,string>={
  renameMovies:'Rename movie files using the selected naming format.',renameEpisodes:'Rename episode files using the selected naming formats.',replaceIllegalCharacters:'Replace characters that are not valid for the destination file system.',createEmptyMovieFolders:'Create folders for monitored movies before files are available.',createEmptySeriesFolders:'Create folders for monitored series before files are available.',deleteEmptyFolders:'Remove empty media folders during disk scans.',copyUsingHardlinks:'Use hardlinks when the download and library share a file system.',importExtraFiles:'Import matching subtitle and companion files.',extraFileExtensions:'Comma-separated extra extensions to import.',enableMediaInfo:'Read technical media information from imported files.',skipFreeSpaceCheckWhenImporting:'Allow imports without checking destination free space.',minimumFreeSpaceWhenImporting:'Minimum destination free space in megabytes.',setPermissionsLinux:'Apply configured Unix permissions to imported files and folders.',chmodFolder:'Unix folder and file permission mode.',chownGroup:'Unix group applied to imported media.',recycleBin:'Folder used instead of permanently deleting files.',recycleBinCleanupDays:'Days to retain deleted files in the recycle folder.'
};
const label=(value:string)=>value.replace(/([a-z0-9])([A-Z])/g,'$1 $2').replace(/[_-]+/g,' ').replace(/\b\w/g,letter=>letter.toUpperCase());
const flatten=(value:MediaSettings,prefix=''):MediaSettingField[]=>Object.entries(value||{}).flatMap(([key,item])=>{
  if(key==='id')return[];
  const path=prefix?`${prefix}.${key}`:key;
  return item&&typeof item==='object'&&!Array.isArray(item)?flatten(item as MediaSettings,path):[{path,key,value:item}];
});
const setPath=(source:MediaSettings,path:string,value:unknown)=>{
  const next=structuredClone(source),parts=path.split('.');let target=next;
  for(const part of parts.slice(0,-1)){if(!target[part]||typeof target[part]!=='object')target[part]={};target=target[part] as MediaSettings;}
  target[parts.at(-1)!]=value;return next;
};
const errorText=(reason:unknown)=>reason instanceof Error?reason.message:'Media management settings are unavailable.';

function Setting({field,onChange}:{field:MediaSettingField;onChange:(value:unknown)=>void}){
  const description=help[field.key],options=field.key==='colonReplacementFormat'&&typeof field.value==='number'?[[0,'Delete'],[1,'Dash'],[2,'Space + dash'],[3,'Space + dash + space'],[4,'Smart replacement'],[5,'Custom replacement']] as Array<[number,string]>:choices[field.key];
  if(typeof field.value==='boolean')return <label className="config-switch"><span><strong>{label(field.key)}</strong>{description?<small>{description}</small>:null}</span><input type="checkbox" checked={field.value} onChange={event=>onChange(event.target.checked)}/></label>;
  if(options){const all=options.some(([value])=>String(value)===String(field.value))?options:[[String(field.value),label(String(field.value))],...options];return <label>{label(field.key)}{description?<small>{description}</small>:null}<select value={String(field.value)} onChange={event=>{const match=all.find(([value])=>String(value)===event.target.value);onChange(typeof field.value==='number'?Number(match?.[0]):match?.[0]);}}>{all.map(([value,text])=><option value={String(value)} key={String(value)}>{text}</option>)}</select></label>;}
  const serialized=Array.isArray(field.value)?field.value.join(', '):String(field.value??''),change=(raw:string)=>onChange(typeof field.value==='number'?Number(raw):Array.isArray(field.value)?raw.split(',').map(value=>value.trim()).filter(Boolean):raw);
  return <label>{label(field.key)}{description?<small>{description}</small>:null}{/Format$/.test(field.key)?<textarea rows={3} value={serialized} onChange={event=>change(event.target.value)}/>:<input type={typeof field.value==='number'?'number':'text'} value={serialized} onChange={event=>change(event.target.value)}/>}</label>;
}

export function MediaManagementView({options}:{options:MediaManagementMountOptions}){
  const [domain,setDomain]=useState<MediaManagementDomain>('movie'),[naming,setNaming]=useState<MediaSettings>({}),[management,setManagement]=useState<MediaSettings>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[audit,setAudit]=useState<NamingAuditJob|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [nameValue,managementValue]=await Promise.all([options.request<{result:MediaSettings}>(`/api/manage/${domain}/naming`),options.request<{result:MediaSettings}>(`/api/manage/${domain}/mediaManagement`)]);setNaming(nameValue.result||{});setManagement(managementValue.result||{});}catch(reason){setError(errorText(reason));}finally{setLoading(false);}},[domain,options]);
  useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(audit?.status!=='running')return;const timer=window.setInterval(()=>{void options.request<{job:NamingAuditJob}>(`/api/media-files/naming-audit/${audit.id}`).then(value=>setAudit(value.job)).catch(reason=>{window.clearInterval(timer);options.notify(errorText(reason),'error');});},1200);return()=>window.clearInterval(timer);},[audit?.id,audit?.status,options]);
  const save=async(resource:'naming'|'mediaManagement',value:MediaSettings)=>{setBusy(resource);try{await options.request(`/api/manage/${domain}/${resource}`,{method:'PUT',body:JSON.stringify(value)});options.notify(`${domain==='movie'?'Movie':'Television'} media management saved.`);await load();}catch(reason){options.notify(errorText(reason),'error');}finally{setBusy('');}};
  const startAudit=async()=>{setBusy('audit');setAudit(null);try{const value=await options.request<{job:NamingAuditJob}>('/api/media-files/naming-audit',{method:'POST',body:JSON.stringify({domain})});setAudit(value.job);}catch(reason){options.notify(errorText(reason),'error');}finally{setBusy('');}};
  const sections:Array<[string,'naming'|'mediaManagement',MediaSettings,string]>=[['Naming and folders','naming',naming,'File and folder naming formats, illegal-character handling, and library folder behavior.'],['Importing and file management','mediaManagement',management,'Import behavior, rescanning, free-space checks, recycling, media inspection, and permissions.']];
  return <div className="media-management-react-route"><div className="hero"><div><span className="eyebrow">SERVICE SETTINGS</span><h1>Media Management</h1><p className="lede">Control naming, folders, importing, file handling, permissions, and recycling for both libraries.</p></div></div>
    <nav className="settings-tabs"><a href="#service/root-folders">Root Folders</a><a className="active" href="#service/media-management">Media Management</a><a href="#service/profiles">Quality Profiles</a><a href="#service/custom-formats">Custom Formats</a><a href="#service/release-profiles">Release Profiles</a><a href="#service/indexers">Indexers</a><a href="#service/download-clients">Download Clients</a><a href="#service/discover">Discover</a><a href="#management">Advanced</a></nav>
    <div className="management-toolbar"><label>Library<select value={domain} onChange={event=>{setDomain(event.target.value as MediaManagementDomain);setAudit(null);}}><option value="movie">Movies</option><option value="tv">Television</option></select></label></div>
    <section className="panel naming-audit"><div className="panel-heading"><div><span className="eyebrow">LIBRARY REVIEW</span><h2>Naming audit</h2><p className="muted">Review imported folders and media files against the naming conventions currently configured in the {domain==='movie'?'movie':'television'} engine. Running an audit does not rename or move anything.</p></div><button className="primary" disabled={busy==='audit'||audit?.status==='running'} onClick={()=>void startAudit()}>{audit?.status==='running'?'Auditing…':busy==='audit'?'Starting…':'Audit library names'}</button></div>
      {audit?<><div className="naming-audit-summary"><div><strong>{audit.completed}</strong><span>Reviewed of {audit.total||'…'}</span></div><div><strong>{audit.matching}</strong><span>Matching</span></div><div><strong>{audit.mismatched}</strong><span>Need attention</span></div><div><strong>{audit.failed}</strong><span>Could not inspect</span></div></div>{audit.status==='running'?<div className="naming-audit-progress"><span style={{width:`${audit.total?Math.round(audit.completed/audit.total*100):2}%`}}/><small>{audit.currentTitle?`Checking ${audit.currentTitle}`:'Reading library…'}</small></div>:null}
      {audit.results.length?<div className="naming-audit-results">{audit.results.map(result=><article key={`${result.domain}-${result.mediaId}`}><header><div><strong>{result.title}</strong><small>{result.folderChange?'Folder and file naming review':'File naming review'}</small></div><a className="secondary button-link" href={`#${result.domain==='movie'?'movie':'series'}/${result.domain}_${result.mediaId}`}>Open details</a></header>{result.folderChange?<div className="naming-audit-change"><span><small>Current folder</small><code>{result.currentPath}</code></span><i>→</i><span><small>Expected folder</small><code>{result.destinationPath}</code></span></div>:null}{result.files.map((file,index)=><div className="naming-audit-change" key={`${file.id??index}-${file.existingPath}`}><span><small>Current file</small><code>{file.existingPath}</code></span><i>→</i><span><small>Expected file</small><code>{file.newPath}</code></span></div>)}</article>)}</div>:audit.status==='completed'?<div className="notice"><strong>All inspected names match.</strong><p>The engine found no folder or media-file names that differ from the current naming conventions.</p></div>:null}
      {audit.errors.length?<details className="naming-audit-errors"><summary>{audit.errors.length} inspection error{audit.errors.length===1?'':'s'}</summary>{audit.errors.map((item,index)=><p key={`${item.title}-${index}`}><strong>{item.title}:</strong> {item.message}</p>)}</details>:null}</>:<div className="naming-audit-empty"><span>✓</span><p>Start a read-only audit to find folders and files that would change if “Rename &amp; organize” were run.</p></div>}
    </section>
    {loading?<div className="panel skeleton">Loading media management…</div>:error?<div className="panel error-state"><h2>Media management unavailable</h2><p>{error}</p><button className="secondary" onClick={()=>void load()}>Try again</button></div>:<div className="media-management-layout">{sections.map(([titleText,resource,value,description])=><form className="panel media-config-form" key={resource} onSubmit={event=>{event.preventDefault();void save(resource,value);}}><div className="panel-heading"><div><h2>{titleText}</h2><p className="muted">{description}</p></div><button className="primary" disabled={busy===resource}>{busy===resource?'Saving…':'Save'}</button></div><div className="media-config-grid">{flatten(value).map(field=><Setting key={field.path} field={field} onChange={next=>resource==='naming'?setNaming(current=>setPath(current,field.path,next)):setManagement(current=>setPath(current,field.path,next))}/>)}</div></form>)}</div>}
  </div>;
}
