import {useCallback,useEffect,useState,type FormEvent} from 'react';
import type{MediaExpansionOptions,ProviderSummary}from'./media-expansion-types';

type MusicSnapshot={artists:Array<{id:string;name:string;monitored:boolean;monitorMode:string;genres:string[]}>;albums:Array<{id:string;artistId:string;title:string;trackCount:number;availableTrackCount:number}>;jobs:Array<{id:string;title:string;status:string}>;indexers:ProviderSummary[];downloadClients:ProviderSummary[]};
type SubtitleSnapshot={providers:ProviderSummary[];profiles:Array<{id:string;name:string;languages:string[];forced:string[]}>;assignments:Array<{id:string;domain:string;mediaId:string;profileId:string}>;items:Array<{id:string;title:string;domain:string;seasonNumber:number|null;episodeNumber:number|null;missingLanguages:string[];presentLanguages:string[];complete:boolean}>;jobs:Array<{id:string;itemId:string;language:string;status:string}>};
const errorMessage=(error:unknown)=>error instanceof Error?error.message:'The request could not be completed.';
const values=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form).entries());

function ProviderForm({kind,onSave}:{kind:'music-indexer'|'music-client'|'subtitle';onSave:()=>void}){
  const [busy,setBusy]=useState(false);const endpoint=kind==='subtitle'?'/api/subtitles/providers':kind==='music-indexer'?'/api/music/indexers':'/api/music/download-clients';
  async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=event.currentTarget,input=values(form);try{await (window as any).__vynodeMoreRequest(endpoint,{method:'POST',body:JSON.stringify({...input,priority:Number(input.priority)||25,enabled:true})});form.reset();onSave();}finally{setBusy(false);}}
  return <form className="panel expansion-provider-form" onSubmit={submit}><h3>{kind==='subtitle'?'Add subtitle provider':kind==='music-indexer'?'Add music indexer':'Add music download client'}</h3><div className="form-grid"><label>Name<input name="name" required/></label><label>Implementation<select name="implementation">{kind==='subtitle'?<><option value="opensubtitles">OpenSubtitles-compatible</option><option value="whisper">Local speech recognition</option><option value="custom">Custom HTTP provider</option></>:kind==='music-indexer'?<><option value="torznab">Torznab</option><option value="newznab">Newznab</option><option value="custom">Custom HTTP indexer</option></>:<><option value="qbittorrent">qBittorrent</option><option value="sabnzbd">SABnzbd</option><option value="nzbget">NZBGet</option><option value="custom">Custom HTTP client</option></>}</select></label><label>Endpoint<input name="endpoint" type="url" required placeholder="https://provider.example"/></label><label>API key<input name="apiKey" type="password" autoComplete="new-password"/></label><label>Priority<input name="priority" type="number" min="1" max="100" defaultValue="25"/></label></div><button className="primary" disabled={busy}>{busy?'Saving…':'Save configuration'}</button></form>;
}
function ProviderList({title,items}:{title:string;items:ProviderSummary[]}){return <section className="panel"><div className="panel-heading"><h3>{title}</h3><span className="badge">{items.length}</span></div>{items.length?items.map(item=><div className="data-row" key={item.id}><span><strong>{item.name}</strong><small>{item.implementation} · priority {item.priority}</small></span><span className={`badge ${item.enabled?'green':''}`}>{item.enabled?'Enabled':'Disabled'}</span></div>):<p className="muted">Nothing configured yet.</p>}</section>}

function SubtitleProfileForm({options,onSave}:{options:MediaExpansionOptions;onSave:()=>void}){const[busy,setBusy]=useState(false);async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=event.currentTarget,input=values(form);try{await options.request('/api/subtitles/profiles',{method:'POST',body:JSON.stringify({name:input.name,languages:String(input.languages||'').split(',').map(value=>value.trim()),forced:String(input.forced||'').split(',').map(value=>value.trim()).filter(Boolean),hearingImpaired:input.hearingImpaired})});form.reset();options.notify('Subtitle language profile saved.');onSave();}catch(error){options.notify(errorMessage(error),'error');}finally{setBusy(false);}}return <form className="panel expansion-provider-form" onSubmit={submit}><h3>Create language profile</h3><label>Name<input name="name" required placeholder="Family English + Spanish"/></label><div className="form-grid"><label>Languages<input name="languages" required placeholder="en, es"/><small>Comma-separated language codes.</small></label><label>Forced languages<input name="forced" placeholder="en"/></label><label>Hearing impaired<select name="hearingImpaired" defaultValue="include"><option value="include">Include</option><option value="prefer">Prefer</option><option value="exclude">Exclude</option></select></label></div><button className="primary" disabled={busy}>{busy?'Saving…':'Save profile'}</button></form>}

function Music({options}:{options:MediaExpansionOptions}){const[data,setData]=useState<MusicSnapshot|null>(null),[error,setError]=useState('');const load=useCallback(()=>options.request<MusicSnapshot>('/api/music').then(setData).catch(reason=>setError(errorMessage(reason))),[options]);useEffect(()=>{(window as any).__vynodeMoreRequest=options.request;void load();return()=>{delete(window as any).__vynodeMoreRequest;}},[load,options]);if(error)return <div className="panel error-state">{error}</div>;if(!data)return <div className="panel skeleton">Loading music workspace…</div>;return <><div className="expansion-summary"><div><strong>{data.artists.length}</strong><span>Artists</span></div><div><strong>{data.albums.length}</strong><span>Albums</span></div><div><strong>{data.indexers.length}</strong><span>Indexers</span></div><div><strong>{data.downloadClients.length}</strong><span>Download clients</span></div></div><section className="expansion-columns"><div><h2>Music library</h2><p className="muted">Artist → album → track monitoring, with transparent release scoring and independent quality policies.</p>{data.artists.length?data.artists.map(artist=><article className="panel" key={artist.id}><h3>{artist.name}</h3><p>{artist.monitorMode} monitoring · {artist.genres.join(', ')||'No genres'}</p></article>):<div className="panel empty compact"><h3>No artists yet</h3><p>Add artists after configuring search and download providers.</p></div>}</div><div><ProviderList title="Music indexers" items={data.indexers}/>{options.administrator&&<ProviderForm kind="music-indexer" onSave={()=>void load()}/>}<ProviderList title="Music download clients" items={data.downloadClients}/>{options.administrator&&<ProviderForm kind="music-client" onSave={()=>void load()}/>}</div></section></>}

function Subtitles({options}:{options:MediaExpansionOptions}){const[data,setData]=useState<SubtitleSnapshot|null>(null),[error,setError]=useState('');const load=useCallback(()=>options.request<SubtitleSnapshot>('/api/subtitles').then(setData).catch(reason=>setError(errorMessage(reason))),[options]);useEffect(()=>{(window as any).__vynodeMoreRequest=options.request;void load();return()=>{delete(window as any).__vynodeMoreRequest;}},[load,options]);if(error)return <div className="panel error-state">{error}</div>;if(!data)return <div className="panel skeleton">Loading subtitle workspace…</div>;const missing=data.items.filter(item=>!item.complete);return <><div className="expansion-summary"><div><strong>{data.items.length}</strong><span>Titles & episodes</span></div><div><strong>{missing.length}</strong><span>Need subtitles</span></div><div><strong>{data.profiles.length}</strong><span>Language profiles</span></div><div><strong>{data.providers.length}</strong><span>Providers</span></div></div><section className="expansion-columns"><div><h2>Episode-aware subtitle coverage</h2><p className="muted">Policies inherit from series to season to episode, with episode overrides taking priority.</p>{data.items.length?data.items.map(item=><article className="panel subtitle-item" key={item.id}><div><h3>{item.title||item.id}</h3><small>{item.domain==='episode'&&item.seasonNumber!=null?`S${String(item.seasonNumber).padStart(2,'0')}E${String(item.episodeNumber||0).padStart(2,'0')}`:item.domain}</small></div><div><span className={`badge ${item.complete?'green':'warm'}`}>{item.complete?'Complete':`${item.missingLanguages.length} missing`}</span><small>{item.missingLanguages.join(', ')||item.presentLanguages.join(', ')||'No policy assigned'}</small></div></article>):<div className="panel empty compact"><h3>No subtitle inventory yet</h3><p>Episode and movie files appear here when they are imported or reconciled.</p></div>}</div><div><ProviderList title="Subtitle providers" items={data.providers}/>{options.administrator&&<ProviderForm kind="subtitle" onSave={()=>void load()}/>}<section className="panel"><div className="panel-heading"><h3>Language profiles</h3><span className="badge">{data.profiles.length}</span></div>{data.profiles.map(profile=><div className="data-row" key={profile.id}><span><strong>{profile.name}</strong><small>{profile.languages.join(', ')}{profile.forced.length?` · forced ${profile.forced.join(', ')}`:''}</small></span></div>)}{!data.profiles.length&&<p className="muted">No language profiles configured.</p>}</section>{options.administrator&&<SubtitleProfileForm options={options} onSave={()=>void load()}/>}</div></section></>}

export function MediaExpansionView({options}:{options:MediaExpansionOptions}){const[section,setSection]=useState(options.initialSection);useEffect(()=>setSection(options.initialSection),[options.initialSection]);return <div className="media-expansion"><div className="hero"><div><span className="eyebrow">VYNODE MORE</span><h1>{section==='music'?'Music':'Subtitles'}</h1><p className="lede">{section==='music'?'A native music library built around artist intent, album completeness, and explainable grabs.':'Subtitle coverage that follows every movie and individual television episode.'}</p></div></div><nav className="expansion-tabs"><a className={section==='music'?'selected':''} href="#music" onClick={()=>setSection('music')}>Music</a><a className={section==='subtitles'?'selected':''} href="#subtitles" onClick={()=>setSection('subtitles')}>Subtitles</a></nav>{section==='music'?<Music options={options}/>:<Subtitles options={options}/>}</div>}
