import { useCallback,useEffect,useState,type FormEvent } from 'react';
import type { MovieDetail,MovieDetailMountOptions } from './movie-detail-types';
import type { MediaEnrichment } from './media-enrichment-types';
import './react-movie-detail.css';

const errorMessage=(reason:unknown)=>reason instanceof Error?reason.message:'The operation failed.';
type LibraryMovie=Record<string,unknown>&{monitored?:boolean;qualityProfileId?:number;path?:string;minimumAvailability?:string};
type SelectOption={id:number;name?:string;path?:string};
type BrowserEntry={name?:string;path:string};

export function MovieDetailView({options}:{options:MovieDetailMountOptions}){
  const engineId=Number(options.publicId.replace(/^movie_/,''));
  const [item,setItem]=useState<MovieDetail|null>(null);
  const [loading,setLoading]=useState(true);
  const [error,setError]=useState('');
  const [busy,setBusy]=useState('');
  const [releases,setReleases]=useState<Record<string,unknown>[]|null>(null);
  const [editing,setEditing]=useState<{movie:LibraryMovie;profiles:SelectOption[];roots:SelectOption[]}|null>(null);
  const [enrichment,setEnrichment]=useState<MediaEnrichment|null>(null);
  const [fileBrowser,setFileBrowser]=useState<{path:string;directories:BrowserEntry[];files:BrowserEntry[];loading:boolean}|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const value=await options.request<{item:MovieDetail}>(`/api/media/movies/${encodeURIComponent(options.publicId)}`);setItem(value.item);setError('');const rich=await options.request<{item:MediaEnrichment|null}>(`/api/discover/enrich?domain=movie&title=${encodeURIComponent(value.item.title)}&year=${value.item.year||''}`).catch(()=>({item:null}));setEnrichment(rich.item);}catch(reason){setError(errorMessage(reason));}finally{setLoading(false);}},[options]);
  useEffect(()=>{void load();},[load]);
  const run=async(name:string,work:()=>Promise<unknown>,notice:string,refreshAfter=false)=>{setBusy(name);try{await work();options.notify(notice);if(refreshAfter)await load();}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const monitor=async()=>{if(!item)return;await run('monitor',async()=>{const value=await options.request<{result:LibraryMovie}>(`/api/manage/movie/library/${engineId}`),raw=value.result;raw.monitored=!raw.monitored;await options.request(`/api/manage/movie/library/${engineId}`,{method:'PUT',body:JSON.stringify(raw)});},item.monitoring==='none'?'Movie monitored.':'Movie unmonitored.',true);};
  const automatic=()=>run('automatic',()=>options.request('/api/manage/movie/automaticSearch',{method:'POST',body:JSON.stringify({movieId:engineId})}),'Best available release selected.');
  const refresh=()=>run('refresh',()=>options.request('/api/manage/movie/commands',{method:'POST',body:JSON.stringify({name:'RefreshMovie',movieIds:[engineId]})}),'Refresh and folder scan queued.');
  const rename=()=>run('rename',()=>options.request('/api/media-files/rename',{method:'POST',body:JSON.stringify({domain:'movie',mediaId:engineId})}),`Rename and organization queued for ${item?.title}.`);
  const interactive=async()=>{setBusy('interactive');try{const value=await options.request<{result:Record<string,unknown>[] }>(`/api/manage/movie/releases?movieId=${engineId}`);setReleases((value.result||[]).slice(0,200));}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const edit=async()=>{setBusy('edit');try{const [movie,profiles,roots]=await Promise.all([options.request<{result:LibraryMovie}>(`/api/manage/movie/library/${engineId}`),options.request<{result:SelectOption[]}>('/api/manage/movie/profiles'),options.request<{result:SelectOption[]}>('/api/manage/movie/rootFolders')]);setEditing({movie:movie.result,profiles:profiles.result||[],roots:roots.result||[]});}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const saveEdit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!editing)return;const form=new FormData(event.currentTarget),root=String(form.get('rootFolderPath')||''),currentPath=String(editing.movie.path||''),leaf=currentPath.replace(/\\/g,'/').split('/').filter(Boolean).at(-1)||item?.title||'';const payload={...editing.movie,monitored:form.get('monitored')==='on',qualityProfileId:Number(form.get('qualityProfileId')),rootFolderPath:root,path:`${root.replace(/[\\/]+$/,'')}/${leaf}`,minimumAvailability:String(form.get('minimumAvailability')||'released')};await run('save-edit',async()=>{await options.request(`/api/manage/movie/library/${engineId}?moveFiles=true`,{method:'PUT',body:JSON.stringify(payload)});setEditing(null);},'Library settings saved.',true);};
  const grab=(release:Record<string,unknown>)=>run('grab',async()=>{await options.request('/api/manage/movie/releases',{method:'POST',body:JSON.stringify(release)});setReleases(null);},'Release sent to the download client.');
  const browseFiles=async(path=item?.location||item?.rootFolder||'/')=>{const clean=String(path||'/').replaceAll('\\','/').replace(/\/+$/,'')||'/';setFileBrowser({path:clean,directories:[],files:[],loading:true});try{const value=await options.request<{result:{directories?:BrowserEntry[];files?:Array<BrowserEntry|string>}}>(`/api/manage/movie/filesystem?path=${encodeURIComponent(clean)}&includeFiles=true&allowFoldersWithoutTrailingSlashes=true`),video=/\.(?:avi|mkv|mp4|m4v|mov|wmv|mpg|mpeg|ts|m2ts|webm)$/i;setFileBrowser({path:clean,directories:value.result?.directories||[],files:(value.result?.files||[]).map(file=>typeof file==='string'?{path:file,name:file.split(/[\\/]/).at(-1)}:file).filter(file=>video.test(file.path)),loading:false});}catch(reason){setFileBrowser(null);options.notify(errorMessage(reason),'error');}};
  const chooseFile=async(path:string)=>{if(!window.confirm(`Use ${path.split(/[\\/]/).at(-1)} for ${item?.title}?`))return;await run('choose-file',async()=>{await options.request('/api/media-files/reassign',{method:'POST',body:JSON.stringify({domain:'movie',path,movieId:engineId})});setFileBrowser(null);},'Movie file reassignment started.',true);};
  const remove=async()=>{if(!item||!window.confirm(`Remove ${item.title} from the library? Files will be kept.`))return;await run('delete',async()=>{await options.request(`/api/manage/movie/library/${engineId}?deleteFiles=false`,{method:'DELETE'});location.hash='#movies';},`${item.title} removed.`);};
  if(loading)return <div className="detail-skeleton skeleton"/>;
  if(error||!item)return <div className="empty error-state"><h2>Movie details unavailable</h2><p>{error}</p></div>;
  const facts=[['Year',item.year||'Not reported'],['Runtime',item.runtimeMinutes?`${item.runtimeMinutes} min`:'Not reported'],['Availability',item.availability||'Unknown'],['Quality',item.quality||'Not available'],['Profile',item.qualityProfile||'None'],['Collection',item.collection||'None']];
  const information=[['Genres',item.genres?.join(', ')||'Not specified'],['Studio',item.studio||'Not specified'],['Certification',item.certification||'Not rated'],['Original language',item.originalLanguage||'Not specified'],['Rating',item.rating?`${item.rating.toFixed(1)} / 10`:'Not rated'],['Library path',item.rootFolder||'Not configured'],['File status',item.hasFile?'Available on disk':'Missing'],['Digital release',item.releaseDates?.digital?new Date(item.releaseDates.digital).toLocaleDateString():'Not announced']];
  return <div className="react-movie-detail" role="dialog" aria-modal="true" aria-label={`${item.title} movie details`}>
    <div className="vynode-detail-surface">
    {item.backdrop?.url?<div className="detail-backdrop"><img src={item.backdrop.url} alt="" aria-hidden="true"/></div>:null}
    <a className="back-link" href="#movies">← Back to Movies</a>
    <section className="detail-hero"><div className="detail-art">{item.artwork?.url?<img src={item.artwork.url} alt=""/>:<span className="art-fallback">M</span>}</div><div className="detail-copy"><span className="eyebrow">MOVIE</span><h1>{item.title}</h1><p className="lede">{item.overview}</p><span className="badge green">{item.monitoring||'Unknown'}</span><div className="detail-actions"><button className="primary" disabled={Boolean(busy)} onClick={()=>void automatic()}>{busy==='automatic'?'Selecting…':'Automatic search'}</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void interactive()}>Interactive search</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void monitor()}>{item.monitoring==='none'?'Monitor':'Unmonitor'}</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void rename()}>Rename & organize</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void browseFiles()}>Change file</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void refresh()}>Refresh & scan</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void edit()}>Edit</button><button className="danger" disabled={Boolean(busy)} onClick={()=>void remove()}>Delete</button></div></div></section>
    <div className="fact-grid">{facts.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>
    <section className="panel movie-information"><h2>Movie information</h2><div className="movie-information-grid">{information.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div></section>
    {enrichment?<section className="panel tmdb-enrichment"><div className="panel-heading"><div><span className="eyebrow">EXTENDED DETAILS</span><h2>{enrichment.tagline||'Cast and links'}</h2></div><span className="read-only">TMDB</span></div><div className="enrichment-facts">{[['Original title',enrichment.originalTitle],['Language',enrichment.originalLanguage?.toUpperCase()],['Countries',enrichment.countries?.join(', ')],['Studios',enrichment.productionCompanies?.join(', ')]].filter(([,value])=>value).map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>{enrichment.cast?.length?<div className="cast-section"><h3>Cast</h3><div className="cast-row">{enrichment.cast.map(person=><article key={person.id}>{person.photo?<img src={person.photo} alt="" loading="lazy"/>:<span className="cast-fallback">{person.name[0]}</span>}<strong>{person.name}</strong><small>{person.character||'Cast'}</small></article>)}</div></div>:null}<div className="enrichment-links">{enrichment.trailer?<a className="primary" href={enrichment.trailer.url} target="_blank" rel="noreferrer">▶ {enrichment.trailer.name}</a>:null}{enrichment.externalLinks?.map(link=><a className="secondary" href={link.url} target="_blank" rel="noreferrer" key={link.label}>{link.label} ↗</a>)}</div></section>:<section className="panel tmdb-unavailable"><div><span className="eyebrow">OPTIONAL DETAILS</span><h2>Cast, trailers, and external links are unavailable</h2><p>VynodeArr is showing complete engine details. Add a TMDB read key in Service Settings to include extended title metadata.</p></div><a className="primary" href="#service/discover">Configure TMDB</a></section>}
    {fileBrowser?<dialog open className="react-detail-dialog file-browser-dialog"><div className="panel-heading"><div><span className="eyebrow">CHOOSE MOVIE FILE</span><h2>{item.title}</h2><p>{fileBrowser.path}</p></div><button className="secondary" onClick={()=>setFileBrowser(null)}>Close</button></div><div className="file-browser-actions"><button className="secondary" disabled={fileBrowser.path==='/'||fileBrowser.loading} onClick={()=>void browseFiles(fileBrowser.path.split('/').slice(0,-1).join('/')||'/')}>← Parent</button></div>{fileBrowser.loading?<div className="skeleton">Loading files…</div>:<div className="file-browser-list">{fileBrowser.directories.map(folder=><button className="folder-row" key={folder.path} onClick={()=>void browseFiles(folder.path)}><span>▰</span><strong>{folder.name||folder.path.split('/').at(-1)}</strong><small>{folder.path}</small></button>)}{fileBrowser.files.map(file=><button className="folder-row media-file-choice" key={file.path} onClick={()=>void chooseFile(file.path)}><span>▶</span><strong>{file.name||file.path.split('/').at(-1)}</strong><small>{file.path}</small></button>)}{!fileBrowser.directories.length&&!fileBrowser.files.length?<div className="empty compact"><p>No video files are available in this folder.</p></div>:null}</div>}</dialog>:null}
    {editing?<dialog open className="react-detail-dialog react-detail-editor"><form onSubmit={event=>void saveEdit(event)}><div className="panel-heading"><div><span className="eyebrow">LIBRARY SETTINGS</span><h2>Edit {item.title}</h2></div><button type="button" className="secondary" onClick={()=>setEditing(null)}>Close</button></div><label className="check"><input name="monitored" type="checkbox" defaultChecked={Boolean(editing.movie.monitored)}/> Monitored</label><label>Quality profile<select name="qualityProfileId" defaultValue={editing.movie.qualityProfileId}>{editing.profiles.map(profile=><option value={profile.id} key={profile.id}>{profile.name||`Profile ${profile.id}`}</option>)}</select></label><label>Root folder<select name="rootFolderPath" defaultValue={editing.roots.find(root=>editing.movie.path?.startsWith(String(root.path)))?.path}>{editing.roots.map(root=><option value={root.path} key={root.id}>{root.path}</option>)}</select></label><label>Minimum availability<select name="minimumAvailability" defaultValue={editing.movie.minimumAvailability||'released'}><option value="announced">Announced</option><option value="inCinemas">In cinemas</option><option value="released">Released</option></select></label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={busy==='save-edit'}>{busy==='save-edit'?'Saving…':'Save changes'}</button></div></form></dialog>:null}
    {releases?<dialog open className="react-detail-dialog"><div className="panel-heading"><div><span className="eyebrow">INTERACTIVE SEARCH</span><h2>{item.title}</h2><p>{releases.length} releases found</p></div><button className="secondary" onClick={()=>setReleases(null)}>Close</button></div><div className="wanted-release-list">{releases.map((release,index)=><article className="release-row" key={index}><div className="release-title"><strong>{String(release.title||'Unknown release')}</strong><small>{String(release.indexer||release.protocol||'Unknown source')}</small></div><span>{String((release.quality as {quality?:{name?:string}})?.quality?.name||'Unknown')}</span><span>{(Number(release.size||0)/1073741824).toFixed(2)} GB</span><span>{String(release.seeders??'—')} seeders</span><button className="primary" onClick={()=>void grab(release)}>Grab</button></article>)}</div></dialog>:null}
    </div>
  </div>;
}
