import { useCallback, useEffect, useState } from "react";
import { ServiceTabs } from "./service-tabs";
import { ModalPortal } from "./modal-portal";
import type { AvailableLibraryFolder, AvailableLibraryFoldersResponse, Directory, RootFoldersMountOptions } from "./root-folders-types";
import { errorMessage } from "./shell-utils";

const clean=(value:string)=>(value==="/"?"/":value.replace(/\/+$/g,"")||"/"), parent=(value:string)=>clean(value).split("/").slice(0,-1).join("/")||"/";
type Settings={downloadPath:string;libraryRoot:string;naming:string;downloadAccessible?:boolean;libraryAccessible?:boolean};

function MusicFolderLevel({path,settings,busy,onChoose,request}:{path:string;settings:Settings;busy:boolean;onChoose:(path:string)=>Promise<void>;request:RootFoldersMountOptions["request"]}){
 const[folders,setFolders]=useState<AvailableLibraryFolder[]>([]),[expanded,setExpanded]=useState(""),[loading,setLoading]=useState(true);
 useEffect(()=>{setLoading(true);void request<{folders:AvailableLibraryFolder[]}>(`/api/storage/library-folder-children?path=${encodeURIComponent(path)}`).then(value=>setFolders(value.folders||[])).finally(()=>setLoading(false));},[path,request]);
 if(loading)return <div className="empty compact"><p>Loading the next folder level…</p></div>;
 if(!folders.length)return <div className="empty compact"><p>No subfolders were found inside {path}.</p></div>;
 return <div className="media-folder-children">{folders.map(item=>{const selected=clean(settings.libraryRoot)===clean(item.path),open=expanded===item.path;return <div className="media-folder-tree-node" key={item.path}><article className="storage-path-row"><span className={`storage-path-state ${selected?"available":"pending"}`}/><div className="storage-path-copy"><strong>{item.label}</strong><small>{item.path}</small><small>{selected?"Current Music library root.":"Choose this folder or browse one level deeper."}</small></div><div className="storage-path-actions"><button className="secondary" onClick={()=>setExpanded(open?"":item.path)}>{open?"Hide subfolders":"Show subfolders"}</button>{!selected&&<button className="secondary" disabled={busy} onClick={()=>void onChoose(item.path)}>Use for Music</button>}</div></article>{open?<MusicFolderLevel path={item.path} settings={settings} busy={busy} onChoose={onChoose} request={request}/>:null}</div>})}</div>;
}
function MusicMediaNode({item,settings,busy,onChoose,request}:{item:AvailableLibraryFolder;settings:Settings;busy:boolean;onChoose:(path:string)=>Promise<void>;request:RootFoldersMountOptions["request"]}){
 const[open,setOpen]=useState(false),selected=clean(settings.libraryRoot)===clean(item.path);
 return <div className="media-folder-tree-node"><article className="storage-path-row"><span className={`storage-path-state ${selected?"available":"pending"}`}/><div className="storage-path-copy"><strong>{item.label}</strong><small>{item.path}</small><small>{selected?"Current Music library root.":"Choose this folder or browse its next level."}</small></div><div className="storage-path-actions"><button className="secondary" onClick={()=>setOpen(value=>!value)}>{open?"Hide subfolders":"Show subfolders"}</button>{!selected&&<button className="secondary" disabled={busy} onClick={()=>void onChoose(item.path)}>Use for Music</button>}</div></article>{open?<MusicFolderLevel path={item.path} settings={settings} busy={busy} onChoose={onChoose} request={request}/>:null}</div>;
}

export default function MusicStorageFolders({options}:{options:RootFoldersMountOptions}){
 const[settings,setSettings]=useState<Settings|null>(null),[available,setAvailable]=useState<AvailableLibraryFoldersResponse|null>(null),[busy,setBusy]=useState(false),[browser,setBrowser]=useState<"download"|"root"|null>(null),[current,setCurrent]=useState("/"),[directories,setDirectories]=useState<Directory[]>([]),[browseError,setBrowseError]=useState("");
 const load=useCallback(async()=>{try{const[value,folders]=await Promise.all([options.request<Settings>("/api/music/import/settings"),options.request<AvailableLibraryFoldersResponse>("/api/storage/available-library-folders")]);setSettings(value);setAvailable(folders);}catch(error){options.notify(errorMessage(error,"Music storage settings are unavailable."),"error");}},[options]);
 useEffect(()=>{void load();},[load]);
 useEffect(()=>{if(!browser)return;setDirectories([]);setBrowseError("");void options.request<{directories:Directory[]}>(`/api/music/storage/filesystem?path=${encodeURIComponent(current)}`).then(value=>setDirectories(value.directories||[])).catch(error=>setBrowseError(errorMessage(error,"Folder access failed.")));},[browser,current,options]);
 async function save(next:Partial<Settings>){if(!settings)return;setBusy(true);try{const value=await options.request<Settings>("/api/music/import/settings",{method:"PUT",body:JSON.stringify({...settings,...next})});setSettings(value);options.notify("Music storage folders saved and verified.");}catch(error){options.notify(errorMessage(error),"error");}finally{setBusy(false);}}
 function open(target:"download"|"root"){setBrowser(target);setCurrent(clean(target==="download"?settings?.downloadPath||"/downloads/music":settings?.libraryRoot||"/music"));}
 if(!settings)return <div className="panel skeleton">Loading music storage…</div>;
 const same=clean(settings.downloadPath)===clean(settings.libraryRoot),mediaChildren=available?.mediaChildren||[];
 return <div className="root-folders-react-route"><div className="hero storage-hero"><div><span className="eyebrow">SERVICE SETTINGS</span><h1>Storage Folders</h1><p className="lede">Separate completed downloads from the permanent, organized media library.</p></div></div><ServiceTabs active="root-folders"/>
  <section className="storage-engine-bar"><div><span className="eyebrow">CONFIGURING</span><strong>Music storage</strong></div><label>Media engine<select value="music" onChange={event=>{window.location.hash=`service/root-folders/${event.target.value}`;}}><option value="movie">Movies</option><option value="tv">Television</option><option value="music">Music</option></select></label></section>
  {same&&<div className="notice storage-warning"><strong>Download and library paths match</strong><p>Choose separate paths so completed downloads remain isolated until VynodeArr validates and imports them.</p></div>}
  <div className="storage-config-grid"><section className="panel storage-folder-card"><div className="storage-card-heading"><span className="storage-card-icon">↓</span><div><span className="eyebrow">INCOMING MEDIA</span><h2>Download folder</h2><p>The completed-download staging folder Music reads before import.</p></div><span className={`badge ${settings.downloadAccessible?"green":"warm"}`}>{settings.downloadAccessible?"Accessible":"Setup required"}</span></div><div className="storage-path-control"><label>Current folder<input readOnly value={settings.downloadPath}/></label><button className="secondary" onClick={()=>open("download")}>Choose folder</button></div><div className="storage-card-footer"><small>The selected folder must be visible and writable inside VynodeArr.</small><button className="primary" disabled={busy||same} onClick={()=>void save({downloadPath:settings.downloadPath})}>Save download folder</button></div></section>
  <section className="panel storage-folder-card"><div className="storage-card-heading"><span className="storage-card-icon">▰</span><div><span className="eyebrow">ORGANIZED MEDIA</span><h2>Library folders</h2><p>Permanent destinations for organized artists, albums, and tracks.</p></div><span className="badge">{settings.libraryRoot?1:0}</span></div><div className="storage-add-form"><div className="storage-path-control"><label>New library folder<input readOnly value={settings.libraryRoot}/></label><button className="secondary" onClick={()=>open("root")}>Choose folder</button></div></div><div className="storage-root-list"><article className="storage-path-row"><span className={`storage-path-state ${settings.libraryAccessible?"available":"unavailable"}`}/><div className="storage-path-copy"><strong>{settings.libraryRoot||"No music root configured"}</strong><small>{settings.libraryAccessible?"Accessible and writable":"Folder access must be configured"}</small><small>Primary Music library root</small></div><div className="storage-path-actions"><button className="secondary" disabled={busy||same} onClick={()=>void save({libraryRoot:settings.libraryRoot})}>Save library folder</button></div></article></div></section></div>
  <section className="panel available-library-mappings"><div className="panel-heading"><div><span className="eyebrow">UNRAID CONTAINER PATHS</span><h2>Configured library mappings</h2><p className="muted">Choose a visible folder for Music, or show its subfolders to select a more specific location.</p></div></div><div className="main-media-folders"><div className="panel-heading"><div><h3>Main media folder</h3><p className="muted">Each row is one direct child of /media.</p></div><span className="badge">/media</span></div>{available?.mainMediaConfigured?<div className="available-mapping-list">{mediaChildren.map(item=><MusicMediaNode key={item.path} item={item} settings={settings} busy={busy} onChoose={path=>save({libraryRoot:path})} request={options.request}/>)}</div>:<div className="empty compact"><p>Map the shared host media folder to /media, apply the container change, and return here.</p></div>}</div></section>
  {browser&&<ModalPortal><div className="root-folder-browser-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setBrowser(null);}}><section className="panel root-folder-browser" role="dialog" aria-modal="true"><div className="panel-heading"><div><span className="eyebrow">CHOOSE A FOLDER</span><h2>{current}</h2><p className="muted">Only supported media and download mappings visible inside this container are shown.</p></div><button className="secondary" onClick={()=>setBrowser(null)}>Cancel</button></div><div className="folder-browser-actions"><button className="secondary" disabled={["/media","/music","/downloads"].includes(current)} onClick={()=>setCurrent(parent(current))}>← Parent</button><button className="primary" onClick={()=>{void save(browser==="root"?{libraryRoot:current}:{downloadPath:current});setBrowser(null);}}>Use this folder</button></div><div className="folder-browser-list">{browseError?<div className="empty error-state"><p>{browseError}</p></div>:directories.length?directories.map(folder=><button className="folder-row" key={folder.path} onClick={()=>setCurrent(clean(folder.path))}><span className="folder-icon">▰</span><span>{folder.name}</span><small>{folder.path}</small></button>):<div className="empty compact"><p>No subfolders here. You can still use this folder.</p></div>}</div></section></div></ModalPortal>}
 </div>;
}
