import {useCallback,useEffect,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import type {NotificationChannel,NotificationDelivery,NotificationItem,NotificationMountOptions,NotificationPreferences,SearchActivity} from './notification-types';

const relativeTime=(value:string)=>{const seconds=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));if(seconds<60)return'Just now';if(seconds<3600)return`${Math.floor(seconds/60)}m ago`;if(seconds<86400)return`${Math.floor(seconds/3600)}h ago`;return`${Math.floor(seconds/86400)}d ago`;};
const stages=['queued','searching','grabbed','downloading','imported'] as const;
const stageLabel=(value:string)=>({queued:'Queued',searching:'Searching',grabbed:'Grabbed',downloading:'Downloading',imported:'Imported',completed:'Completed',failed:'Failed',canceled:'Canceled'}[value]||value);
const stagePosition=(status:string)=>status==='completed'?1:Math.max(0,stages.indexOf(status as typeof stages[number]));

export function Notifications({options}:{options:NotificationMountOptions}){
  const [items,setItems]=useState<NotificationItem[]>([]),[activities,setActivities]=useState<SearchActivity[]>([]),[unread,setUnread]=useState(0),[open,setOpen]=useState(false),[tab,setTab]=useState<'inbox'|'history'|'search'|'settings'>('inbox'),[error,setError]=useState(''),[preferences,setPreferences]=useState<NotificationPreferences|null>(null),[defaults,setDefaults]=useState<NotificationPreferences|null>(null),[quiet,setQuiet]=useState(false),[channels,setChannels]=useState<NotificationChannel[]>([]),[deliveries,setDeliveries]=useState<NotificationDelivery[]>([]);
  const host=useRef<HTMLDivElement>(null),panel=useRef<HTMLElement>(null);
  const load=useCallback(async()=>{if(!options.canPoll())return;try{const notificationRequest=options.request<{items:NotificationItem[];unread:number;quietHoursActive:boolean;pageBadge:{href:'#request-management'|'#requests';count:number}}>('/api/notifications'),activityRequest=options.administrator?options.request<{items:SearchActivity[]}>('/api/search-activities'):Promise.resolve({items:[]});const[value,activityValue]=await Promise.all([notificationRequest,activityRequest]);setItems(value.items||[]);setActivities(activityValue.items||[]);setUnread(Number(value.unread||0));setQuiet(Boolean(value.quietHoursActive));options.onPageBadge(value.pageBadge);setError('');}catch{setError('Activity is temporarily unavailable.');}},[options]);
  const loadPreferences=useCallback(async()=>{try{const preferenceRequest=options.request<{preferences:NotificationPreferences;defaults:NotificationPreferences}>('/api/notifications/preferences'),channelRequest=options.administrator?options.request<{channels:NotificationChannel[];deliveries:NotificationDelivery[]}>('/api/notifications/channels'):Promise.resolve({channels:[],deliveries:[]});const[value,external]=await Promise.all([preferenceRequest,channelRequest]);setPreferences(value.preferences);setDefaults(value.defaults);setChannels(external.channels);setDeliveries(external.deliveries);}catch{setError('Notification preferences could not be loaded.');}},[options]);
  const savePreferences=async(value:NotificationPreferences,scope:'user'|'defaults'='user')=>{try{const result=await options.request<{preferences:NotificationPreferences;defaults:NotificationPreferences}>('/api/notifications/preferences',{method:'PATCH',body:JSON.stringify({scope,preferences:value})});setPreferences(result.preferences);setDefaults(result.defaults);await load();}catch{setError('Notification preferences could not be saved.');}};
  const sendTest=async()=>{try{await options.request('/api/notifications/test',{method:'POST',body:'{}'});await load();setTab('inbox');}catch{setError('The test notification could not be sent.');}};
  const saveChannel=async(channel:NotificationChannel)=>{try{await options.request('/api/notifications/channels',{method:'POST',body:JSON.stringify(channel)});await loadPreferences();}catch(reason){setError(reason instanceof Error?reason.message:'The notification channel could not be saved.');}};
  const channelAction=async(channelId:string,action:'test'|'delete',deliveryId?:string)=>{try{await options.request(`/api/notifications/channels/${channelId}${action==='delete'?'':`/${deliveryId?'retry':'test'}`}`,action==='delete'?{method:'DELETE'}:{method:'POST',body:JSON.stringify(deliveryId?{deliveryId}:{})});await loadPreferences();}catch(reason){setError(reason instanceof Error?reason.message:'The delivery action failed.');await loadPreferences();}};
  const mark=useCallback(async(ids?:string[])=>{try{await options.request('/api/notifications/read',{method:'POST',body:JSON.stringify(ids?{ids}:{})});setItems(current=>current.map(item=>!ids||ids.includes(item.id)?{...item,read:true}:item));setUnread(current=>ids?Math.max(0,current-ids.filter(id=>items.some(item=>item.id===id&&!item.read)).length):0);}catch{setError('Notifications could not be marked as read.');}},[items,options]);
  const dismiss=async(id:string)=>{try{await options.request(`/api/search-activities/${id}`,{method:'DELETE'});setActivities(current=>current.filter(item=>item.id!==id));}catch{setError('Search activity could not be dismissed.');}};
  useEffect(()=>{void load();const timer=window.setInterval(()=>void load(),activities.some(item=>['queued','searching','grabbed','downloading'].includes(item.status))?5_000:15_000);return()=>window.clearInterval(timer);},[activities,load]);
  useEffect(()=>{if(open&&!preferences)void loadPreferences();},[loadPreferences,open,preferences]);
  useEffect(()=>{const close=(event:MouseEvent)=>{if(open&&!host.current?.contains(event.target as Node)&&!panel.current?.contains(event.target as Node))setOpen(false);};document.addEventListener('mousedown',close);return()=>document.removeEventListener('mousedown',close);},[open]);
  const inbox=items.filter(item=>!item.read||item.actionable),history=items.filter(item=>item.read&&!item.actionable),shown=tab==='history'?history:inbox;
  const title=tab==='settings'?'Notification preferences':tab==='search'?'Search activity':tab==='history'?'Notification history':'Inbox';
  return <div className="notification-center" ref={host}>
    <button className={`notification-bell${open?' active':''}`} type="button" aria-label={unread?`Notifications, ${unread} unread`:'Notifications'} aria-expanded={open} onClick={()=>setOpen(current=>!current)}><svg aria-hidden="true" viewBox="0 0 24 24"><path d="M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4"/></svg>{unread?<strong>{unread>99?'99+':unread}</strong>:null}</button>
    {open?createPortal(<section className="notification-panel" aria-label="Activity center" ref={panel}>
      <header><div><span className="eyebrow">ACTIVITY</span><h2>{title}</h2></div>{tab==='inbox'&&unread?<button type="button" className="text-button" onClick={()=>void mark()}>Mark all read</button>:null}</header>
      <div className={`activity-tabs${options.administrator?' administrator':''}`} role="tablist"><button className={tab==='inbox'?'active':''} onClick={()=>setTab('inbox')}>Inbox{unread?` (${unread})`:''}{quiet?<i title="Quiet hours active"/>:null}</button><button className={tab==='history'?'active':''} onClick={()=>setTab('history')}>History</button>{options.administrator?<button className={tab==='search'?'active':''} onClick={()=>setTab('search')}>Search activity{activities.some(item=>['queued','searching','grabbed','downloading'].includes(item.status))?<i/>:null}</button>:null}<button className={tab==='settings'?'active':''} onClick={()=>setTab('settings')}>Settings</button></div>
      {error?<p className="notification-error">{error}</p>:null}
      {tab==='settings'?<NotificationSettings value={preferences} defaults={defaults} administrator={options.administrator} channels={channels} deliveries={deliveries} onSave={savePreferences} onTest={sendTest} onSaveChannel={saveChannel} onChannelAction={channelAction}/>:tab!=='search'?<NotificationList items={shown} emptyTitle={tab==='history'?'No history yet':'All caught up'} emptyMessage={tab==='history'?'Read and resolved notifications will remain here.':'New and actionable notifications will appear here.'} onOpen={item=>{if(!item.read)void mark([item.id]);setOpen(false);}}/>:<SearchActivityList items={activities} onDismiss={dismiss} onOpen={()=>setOpen(false)}/>}
    </section>,document.body):null}
  </div>;
}

function NotificationSettings({value,defaults,administrator,channels,deliveries,onSave,onTest,onSaveChannel,onChannelAction}:{value:NotificationPreferences|null;defaults:NotificationPreferences|null;administrator:boolean;channels:NotificationChannel[];deliveries:NotificationDelivery[];onSave:(value:NotificationPreferences,scope?:'user'|'defaults')=>Promise<void>;onTest:()=>Promise<void>;onSaveChannel:(channel:NotificationChannel)=>Promise<void>;onChannelAction:(channelId:string,action:'test'|'delete',deliveryId?:string)=>Promise<void>}){
  const [draft,setDraft]=useState<NotificationPreferences|null>(value);useEffect(()=>setDraft(value),[value]);if(!draft)return <div className="notification-empty"><strong>Loading preferences…</strong></div>;
  const categories=Object.keys(draft.categories) as (keyof NotificationPreferences['categories'])[],set=(patch:Partial<NotificationPreferences>)=>setDraft(current=>current?{...current,...patch}:current);
  return <div className="notification-settings-wrap"><form className="notification-settings" onSubmit={event=>{event.preventDefault();void onSave(draft);}}><label className="notification-toggle"><input type="checkbox" checked={draft.inApp} onChange={event=>set({inApp:event.target.checked})}/><span><strong>In-app notifications</strong><small>Show alerts in the notification center.</small></span></label><fieldset><legend>Categories</legend>{categories.map(category=><label key={category}><input type="checkbox" checked={draft.categories[category]} onChange={event=>set({categories:{...draft.categories,[category]:event.target.checked}})}/><span>{category.replace(/^./,letter=>letter.toUpperCase())}</span></label>)}</fieldset><label>Minimum severity<select value={draft.minimumSeverity} onChange={event=>set({minimumSeverity:event.target.value as NotificationPreferences['minimumSeverity']})}><option value="information">All activity</option><option value="warning">Warnings and critical</option><option value="critical">Critical only</option></select></label><fieldset><legend>Quiet hours (UTC)</legend><label><input type="checkbox" checked={draft.quietHours.enabled} onChange={event=>set({quietHours:{...draft.quietHours,enabled:event.target.checked}})}/><span>Suppress badges during quiet hours</span></label><div className="quiet-hours"><label>Start<input type="number" min="0" max="23" value={draft.quietHours.start} onChange={event=>set({quietHours:{...draft.quietHours,start:Number(event.target.value)}})}/></label><label>End<input type="number" min="0" max="23" value={draft.quietHours.end} onChange={event=>set({quietHours:{...draft.quietHours,end:Number(event.target.value)}})}/></label></div></fieldset><div className="notification-settings-actions"><button type="button" className="secondary" onClick={()=>void onTest()}>Send test</button><button type="submit" className="primary">Save mine</button>{administrator&&defaults?<button type="button" className="secondary" onClick={()=>void onSave(draft,'defaults')}>Set admin defaults</button>:null}</div></form>{administrator?<ExternalChannels channels={channels} deliveries={deliveries} onSave={onSaveChannel} onAction={onChannelAction}/>:null}</div>;
}

function ExternalChannels({channels,deliveries,onSave,onAction}:{channels:NotificationChannel[];deliveries:NotificationDelivery[];onSave:(channel:NotificationChannel)=>Promise<void>;onAction:(channelId:string,action:'test'|'delete',deliveryId?:string)=>Promise<void>}){
  const blank:NotificationChannel={id:'',type:'discord',name:'Discord',enabled:true,categories:['request','download','import','system','security'],credential:''},[draft,setDraft]=useState<NotificationChannel>(blank),categories=['request','download','import','system','security'];
  return <section className="external-channels"><h3>External delivery</h3><p>Send selected alerts to Discord, Telegram, or Gotify. Credentials are encrypted and never displayed again.</p><form onSubmit={event=>{event.preventDefault();void onSave(draft).then(()=>setDraft(blank));}}><label>Provider<select value={draft.type} onChange={event=>{const type=event.target.value as NotificationChannel['type'];setDraft({...blank,type,name:type.replace(/^./,value=>value.toUpperCase())});}}><option value="discord">Discord webhook</option><option value="telegram">Telegram</option><option value="gotify">Gotify</option></select></label><label>Name<input value={draft.name} onChange={event=>setDraft({...draft,name:event.target.value})}/></label>{draft.type==='gotify'?<label>Server URL<input type="url" placeholder="https://gotify.example.com" value={draft.endpoint||''} onChange={event=>setDraft({...draft,endpoint:event.target.value})}/></label>:null}{draft.type==='telegram'?<label>Chat ID<input value={draft.chatId||''} onChange={event=>setDraft({...draft,chatId:event.target.value})}/></label>:null}<label>{draft.type==='discord'?'Webhook URL':'Token'}<input type="password" required={!draft.id} placeholder={draft.id?'Leave blank to keep saved credential':''} value={draft.credential||''} onChange={event=>setDraft({...draft,credential:event.target.value})}/></label><fieldset><legend>Route categories</legend>{categories.map(category=><label key={category}><input type="checkbox" checked={draft.categories.includes(category)} onChange={event=>setDraft({...draft,categories:event.target.checked?[...draft.categories,category]:draft.categories.filter(value=>value!==category)})}/>{category}</label>)}</fieldset><button className="primary" type="submit">{draft.id?'Update channel':'Add channel'}</button></form><div className="channel-list">{channels.map(channel=><article key={channel.id}><div><strong>{channel.name}</strong><small>{channel.type} · {channel.categories.join(', ')}</small></div><button className="secondary" onClick={()=>setDraft({...channel,credential:''})}>Edit</button><button className="secondary" onClick={()=>void onAction(channel.id,'test')}>Test</button><button className="danger" onClick={()=>void onAction(channel.id,'delete')}>Remove</button></article>)}</div>{deliveries.length?<div className="delivery-history"><h4>Delivery history</h4>{deliveries.slice(0,10).map(item=><article className={item.status} key={item.id}><div><strong>{item.title}</strong><small>{item.channelName} · {item.status}{item.error?` · ${item.error}`:''}</small></div>{item.status==='failed'?<button className="secondary" onClick={()=>void onAction(item.channelId,'test',item.id)}>Retry</button>:null}</article>)}</div>:null}</section>;
}

function NotificationList({items,emptyTitle,emptyMessage,onOpen}:{items:NotificationItem[];emptyTitle:string;emptyMessage:string;onOpen:(item:NotificationItem)=>void}){
  if(!items.length)return <div className="notification-empty"><strong>{emptyTitle}</strong><span>{emptyMessage}</span></div>;
  return <div className="notification-list">{items.map(item=><a className={`notification-item ${item.type} severity-${item.severity||'information'}${item.read?' read':''}`} href={item.href} key={item.id} onClick={()=>onOpen(item)}><i aria-hidden="true"/><div><strong>{item.title}</strong><p>{item.message}</p><small>{relativeTime(item.timestamp)} · {item.category||'activity'}{item.actionable?' · Action required':''}</small></div></a>)}</div>;
}

function SearchActivityList({items,onDismiss,onOpen}:{items:SearchActivity[];onDismiss:(id:string)=>Promise<void>;onOpen:()=>void}){
  if(!items.length)return <div className="notification-empty"><strong>No searches yet</strong><span>Automatic searches will be tracked here.</span></div>;
  return <div className="search-activity-list">{items.map(item=>{const position=stagePosition(item.status),terminal=['completed','failed','canceled','imported'].includes(item.status);return <article className={`search-activity-card ${item.status}`} key={item.id}><div className="search-activity-heading"><div className="search-activity-poster">{item.seriesId?<img src={`/api/artwork/tv/series_${item.seriesId}/poster`} alt=""/>:item.movieId?<img src={`/api/artwork/movie/movie_${item.movieId}/poster`} alt=""/>:<span>{item.domain==='tv'?'TV':'M'}</span>}</div><div><small>{item.scope.replace(/^./,value=>value.toUpperCase())} · {relativeTime(item.createdAt)}</small><strong>{item.title}</strong><span>{stageLabel(item.status)}</span></div>{terminal?<button type="button" aria-label="Dismiss search activity" onClick={()=>void onDismiss(item.id)}>×</button>:null}</div><div className="search-stage-track" aria-label={`Search status: ${stageLabel(item.status)}`}>{stages.map((stage,index)=><span className={index<=position&&!['failed','canceled'].includes(item.status)?'reached':''} key={stage}><i/>{stageLabel(stage)}</span>)}</div><p>{item.message}</p>{item.counts?<div className="search-counts"><span>{item.counts.completed}/{item.counts.total} queued</span>{item.counts.failed?<span>{item.counts.failed} failed</span>:null}</div>:null}{item.selection?<small className="search-selection">{item.selection.quality} · {(item.selection.size/1073741824).toFixed(2)} GB</small>:null}<div className="search-activity-actions"><a href="#queue" onClick={onOpen}>Open Queue</a>{item.seriesId?<a href={`#series/series_${item.seriesId}`} onClick={onOpen}>Open title</a>:item.movieId?<a href={`#movie/movie_${item.movieId}`} onClick={onOpen}>Open title</a>:null}</div></article>;})}</div>;
}
