import {useCallback,useMemo,useRef,useState} from 'react';
import type{OperationActionItem,OperationTimelineItem,OperationsMountOptions}from'./operations-types';
import {useVisibleRefresh} from './use-visible-refresh';

const when=(value:string)=>new Date(value).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'});
export function OperationsCenterView({options}:{options:OperationsMountOptions}){
 const[tab,setTab]=useState<'actions'|'timeline'>('actions'),[actions,setActions]=useState<OperationActionItem[]>([]),[timeline,setTimeline]=useState<OperationTimelineItem[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[query,setQuery]=useState(''),[domain,setDomain]=useState('all'),[category,setCategory]=useState('all'),[showDismissed,setShowDismissed]=useState(false),[busy,setBusy]=useState('');
 const hydrated=useRef(false);
 const load=useCallback(async(announce=false)=>{if(!hydrated.current)setLoading(true);try{const[actionValue,timelineValue]=await Promise.all([options.request<{items:OperationActionItem[]}>(`/api/operations/actions?dismissed=${showDismissed}`),options.request<{items:OperationTimelineItem[]}>('/api/operations/timeline')]);setActions(actionValue.items||[]);setTimeline(timelineValue.items||[]);hydrated.current=true;setError('');if(announce)options.notify('Operations data refreshed.');}catch(reason){setError(reason instanceof Error?reason.message:'Operations data could not be loaded.');}finally{setLoading(false)}},[options,showDismissed]);
 useVisibleRefresh(()=>load(false),30_000);
 const filteredActions=useMemo(()=>actions.filter(item=>(domain==='all'||item.domain===domain)&&(!query||`${item.title} ${item.what} ${item.why} ${item.affected}`.toLowerCase().includes(query.toLowerCase()))),[actions,domain,query]);
 const filteredTimeline=useMemo(()=>timeline.filter(item=>(domain==='all'||item.domain===domain)&&(category==='all'||item.category===category)&&(!query||`${item.title} ${item.summary} ${item.actor}`.toLowerCase().includes(query.toLowerCase()))),[timeline,domain,category,query]);
 const counts={open:actions.filter(item=>!item.dismissedAt).length,critical:actions.filter(item=>!item.dismissedAt&&item.severity==='critical').length,warning:actions.filter(item=>!item.dismissedAt&&item.severity==='warning').length};
 async function setDismissed(item:OperationActionItem,dismiss:boolean){setBusy(item.id);try{await options.request(`/api/operations/actions/${encodeURIComponent(item.id)}/${dismiss?'dismiss':'restore'}`,{method:'POST',body:'{}'});options.notify(dismiss?'Action item dismissed.':'Action item restored.');await load()}catch(reason){options.notify(reason instanceof Error?reason.message:'The action could not be updated.','error')}finally{setBusy('')}}
 return <div className="operations-center">
  <div className="hero operations-hero"><div><span className="eyebrow">ADMIN OPERATIONS</span><h1>Library Action Center</h1><p className="lede">Understand what needs attention, why it happened, who or what is affected, and the safest next step.</p></div><button className="secondary" onClick={()=>void load(true)}>Refresh</button></div>
  <div className="operations-summary"><button className={tab==='actions'?'active':''} aria-pressed={tab==='actions'} onClick={()=>setTab('actions')}><strong>{counts.open}</strong><span>Open actions</span></button><button onClick={()=>{setTab('actions');setQuery('')}}><strong className="danger-text">{counts.critical}</strong><span>Critical</span></button><button onClick={()=>{setTab('actions');setQuery('')}}><strong>{counts.warning}</strong><span>Warnings</span></button><button className={tab==='timeline'?'active':''} aria-pressed={tab==='timeline'} onClick={()=>setTab('timeline')}><strong>{timeline.length}</strong><span>Timeline events</span></button></div>
  <div className="settings-tabs operations-tabs" role="group" aria-label="Operations view"><button type="button" className={tab==='actions'?'active':''} aria-pressed={tab==='actions'} onClick={()=>setTab('actions')} title="Problems that may require a person to review or act">Action Center</button><button type="button" className={tab==='timeline'?'active':''} aria-pressed={tab==='timeline'} onClick={()=>setTab('timeline')} title="A read-only history of automatic and user-triggered work">Automation Timeline</button></div>
  <p className="operations-view-help">{tab==='actions'?'Only items that may need attention appear here. Dismiss hides an item without deleting its history.':'This is the durable activity record. Opening an event does not rerun or change the original action.'}</p>
  <section className="panel operations-toolbar"><label>Find activity<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Title, reason, user, or service"/></label><label>Library<select value={domain} onChange={event=>setDomain(event.target.value)}><option value="all">All libraries</option><option value="movie">Movies</option><option value="tv">Television</option></select></label>{tab==='timeline'?<label>Category<select value={category} onChange={event=>setCategory(event.target.value)}><option value="all">All categories</option>{[...new Set(timeline.map(item=>item.category))].sort().map(value=><option value={value} key={value}>{value}</option>)}</select></label>:<label className="check operations-dismissed"><input type="checkbox" checked={showDismissed} onChange={event=>setShowDismissed(event.target.checked)}/> Show dismissed</label>}</section>
  {error?<div className="notice warning"><strong>Operations data is delayed</strong><p>{error}</p></div>:null}
  {loading?<div className="panel skeleton">Loading operations…</div>:tab==='actions'?<div className="operations-action-list">{filteredActions.map(item=><article className={`panel operations-action severity-${item.severity}`} key={item.id}><header><div><span className={`badge ${item.severity==='critical'?'warm':item.severity==='warning'?'':'green'}`}>{item.severity}</span><h2>{item.title}</h2></div><time>{when(item.timestamp)}</time></header><div className="operations-evidence"><div><span>What happened</span><p>{item.what}</p></div><div><span>Why it matters</span><p>{item.why}</p></div><div><span>Affected</span><p>{item.affected}</p></div><div><span>Recommended action</span><p>{item.recommended}</p></div></div><footer><a className="primary button-link" href={item.href}>Review</a><button className="secondary" disabled={busy===item.id} onClick={()=>void setDismissed(item,!item.dismissedAt)}>{item.dismissedAt?'Restore':'Dismiss'}</button></footer></article>)}{!filteredActions.length?<div className="empty panel"><h2>Nothing needs attention</h2><p>No action items match the current filters.</p></div>:null}</div>:<div className="panel operations-timeline"><div className="operations-timeline-list">{filteredTimeline.map(item=><article key={item.id}><span className={`timeline-marker source-${item.source}`}/><div><header><strong>{item.title}</strong><span className="badge">{item.status}</span></header><p>{item.summary}</p><small>{item.actor} · {item.domain==='movie'?'Movies':item.domain==='tv'?'Television':item.category} · {when(item.timestamp)}</small></div><a className="secondary button-link" href={item.href}>Open</a></article>)}</div>{!filteredTimeline.length?<div className="empty"><h2>No timeline events</h2><p>Try a broader filter.</p></div>:null}</div>}
 </div>
}
