import type {OverlayAsset,OverlayLayer,OverlayTemplate,PosterOverlayMountOptions} from "./poster-overlays-types";

export function validateImportedTemplate(value:unknown,assetIds:Map<string,string>=new Map()):OverlayTemplate{
 if(!value||typeof value!=="object")throw new Error("The selected file is not a poster template.");const source=(value as {template?:unknown}).template??value;if(!source||typeof source!=="object")throw new Error("The template payload is missing.");const candidate=source as OverlayTemplate;
 if(!String(candidate.name||"").trim())throw new Error("The template needs a name.");if(!["movie","tv"].includes(candidate.domain))throw new Error("The template must target Movies or Television.");if(!["vynode","plex"].includes(candidate.target))throw new Error("The template destination is invalid.");if(!Array.isArray(candidate.layers)||!candidate.layers.length||candidate.layers.length>12)throw new Error("A template must contain 1 to 12 layers.");
 const componentIds=new Map((candidate.components||[]).map(component=>[component.id,`component_${crypto.randomUUID()}`])),definitionIds=new Map((candidate.components||[]).flatMap(component=>component.layers.map(layer=>[layer.id,`layer_${crypto.randomUUID()}`] as const))),remap=(layers:OverlayLayer[])=>{const groupIds=new Map<string,string>(),instanceIds=new Map<string,string>();return layers.map(layer=>{if(layer.groupId&&!groupIds.has(layer.groupId))groupIds.set(layer.groupId,`group_${crypto.randomUUID()}`);if(layer.componentInstanceId&&!instanceIds.has(layer.componentInstanceId))instanceIds.set(layer.componentInstanceId,`component_instance_${crypto.randomUUID()}`);return{...layer,id:definitionIds.get(layer.id)||`layer_${crypto.randomUUID()}`,groupId:layer.groupId?groupIds.get(layer.groupId):undefined,componentId:layer.componentId?componentIds.get(layer.componentId):undefined,componentInstanceId:layer.componentInstanceId?instanceIds.get(layer.componentInstanceId):undefined,componentLayerId:layer.componentLayerId?definitionIds.get(layer.componentLayerId):undefined,assetId:layer.assetId?(assetIds.get(layer.assetId)||layer.assetId):undefined};});};
 return{...candidate,id:"",name:`${candidate.name} (imported)`,layers:remap(candidate.layers),variants:(candidate.variants||[]).map(variant=>({...variant,id:`variant_${crypto.randomUUID()}`,layers:remap(variant.layers)})),components:(candidate.components||[]).map(component=>({...component,id:componentIds.get(component.id)!,layers:remap(component.layers)}))};
}
const dataUrl=(blob:Blob)=>new Promise<string>((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result));reader.onerror=()=>reject(new Error("An overlay image could not be exported."));reader.readAsDataURL(blob);}),templateLayers=(template:OverlayTemplate)=>[...template.layers,...(template.variants||[]).flatMap(value=>value.layers),...(template.components||[]).flatMap(value=>value.layers)];
export function inspectTemplatePack(value:unknown){const pack=value as{version?:number;template?:OverlayTemplate;assets?:unknown[]},template=pack.template||(value as OverlayTemplate);validateImportedTemplate(value);return{template,assetCount:Array.isArray(pack.assets)?pack.assets.length:0};}
export async function downloadTemplate(template:OverlayTemplate){const referenced=[...new Map(templateLayers(template).filter(layer=>layer.kind==="image"&&layer.assetId).map(layer=>[layer.assetId!,layer])).values()],assets=[];for(const layer of referenced){const response=await fetch(`/api/poster-overlays/assets/${layer.assetId}`);if(!response.ok)throw new Error(`${layer.assetName||"An overlay image"} could not be exported.`);const blob=await response.blob();if(blob.size>5e6)throw new Error(`${layer.assetName||"An overlay image"} exceeds the portable pack limit.`);assets.push({id:layer.assetId,name:layer.assetName||"Overlay image",image:await dataUrl(blob)});}const blob=new Blob([JSON.stringify({format:"vynodearr-poster-template",version:2,template,assets},null,2)],{type:"application/json"}),url=URL.createObjectURL(blob),anchor=document.createElement("a");anchor.href=url;anchor.download=`${template.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"")||"poster-template"}.json`;anchor.click();URL.revokeObjectURL(url);}
export async function importTemplatePack(value:unknown,request:PosterOverlayMountOptions["request"]){const pack=value as{version?:number;template?:OverlayTemplate;assets?:Array<{id?:string;name?:string;image?:string}>},source=pack.template||(value as OverlayTemplate),referenced=new Set(templateLayers(source).filter(layer=>layer.kind==="image"&&layer.assetId).map(layer=>layer.assetId!)),assets=(pack.assets||[]).filter(asset=>asset.id&&referenced.has(asset.id)),uploaded:OverlayAsset[]=[],assetIds=new Map<string,string>();if(assets.length>24)throw new Error("Poster packs can contain up to 24 images.");if(pack.version===2&&[...referenced].some(id=>!assets.some(asset=>asset.id===id)))throw new Error("The poster pack is missing a referenced image.");try{for(const asset of assets){if(!asset.id||!asset.image)throw new Error("The poster pack contains an invalid image.");const result=await request<{asset:OverlayAsset}>("/api/poster-overlays/assets",{method:"POST",body:JSON.stringify({name:asset.name||"Overlay image",image:asset.image})});uploaded.push(result.asset);assetIds.set(asset.id,result.asset.id);}return validateImportedTemplate(value,assetIds);}catch(reason){await Promise.allSettled(uploaded.map(asset=>request(`/api/poster-overlays/assets/${asset.id}`,{method:"DELETE"})));throw reason;}}
