import type { OverlayLayer } from "./poster-overlays-types";
import { posterIcons } from "./poster-overlay-icons";
const shapes=["rounded","square","pill","circle","ticket","ribbon","tag","hexagon","chevron"] as const;
const variableCategories:Record<string,string>={custom_text:"Custom",title:"Identity",year:"Identity",rating:"Identity",certification:"Identity",studio:"Identity",network:"Identity",genres:"Identity",original_language:"Identity",collection:"Identity",tmdb_id:"Identity",tvdb_id:"Identity",imdb_id:"Identity",quality:"Media file",resolution:"Media file",quality_profile:"Media file",video_codec:"Media file",audio_codec:"Media file",audio_channels:"Media file",dynamic_range:"Media file",source:"Media file",languages:"Media file",subtitle_languages:"Media file",bitrate:"Media file",edition:"Media file",release_group:"Media file",custom_formats:"Media file",custom_format_score:"Media file",runtime:"Media file",file_size:"Media file",monitored:"Library",availability:"Library",library_status:"Library",completion_percent:"Library",tags:"Library",date_added:"Dates",added_ago:"Dates",release_date:"Dates",release_age:"Dates",first_aired:"Dates",download_status:"Download",download_progress:"Download",download_eta:"Download",missing_count:"Television",cutoff_status:"Television",cutoff_unmet_count:"Television",season_progress:"Television",episode_progress:"Television",episodes_available:"Television",episodes_total:"Television",season_count:"Television",current_season:"Current season",current_season_progress:"Current season",current_season_missing:"Current season",series_type:"Television",next_episode:"Next episode",next_episode_title:"Next episode",next_episode_date:"Next episode",next_episode_countdown:"Next episode",next_episode_season:"Next episode",next_episode_number:"Next episode",next_episode_code:"Next episode",latest_episode_title:"Latest episode",latest_episode_date:"Latest episode",latest_episode_season:"Latest episode",latest_episode_number:"Latest episode",latest_episode_code:"Latest episode",series_status:"Television",next_episode_or_status:"Television",requested_by:"Requests",request_count:"Requests",requested_date:"Requests",requested_ago:"Requests"};
const variableLabel=(value:string,kind:OverlayLayer["kind"])=>value==="custom_text"?(kind==="text"?"Custom text":"No variable / custom text"):value.replaceAll("_"," ").replace(/\b(tmdb|tvdb|imdb|eta)\b/gi,word=>word.toUpperCase()).replace(/^./,letter=>letter.toUpperCase());
export default function LayerIdentity({layer,variables,onChange}:{layer:OverlayLayer;variables:string[];onChange:(changes:Partial<OverlayLayer>)=>void}){
 const kind=layer.kind||(layer.variable==="icon"?"icon":"text"),variable=layer.variable==="icon"?"custom_text":layer.variable,grouped=Object.entries(variables.filter(value=>value!=="icon").reduce<Record<string,string[]>>((groups,value)=>{const group=variableCategories[value]||"Other";(groups[group]||=[]).push(value);return groups;},{}));
 return <section className="overlay-control-group overlay-content-controls">
  <header className="overlay-control-group-heading"><span className="eyebrow">CONTENT</span><strong>{kind[0].toUpperCase()+kind.slice(1)} layer</strong><small className="muted">{kind==="text"?"Choose the metadata or custom text shown by this layer.":kind==="icon"?"Icon artwork with optional metadata shown alongside it.":"Shape with optional metadata shown inside or beside it."}</small></header>
  <div className="overlay-control-grid">
  {kind==="icon"?<>
   <label>Icon artwork<select value={layer.iconName||layer.label||"movie"} onChange={e=>onChange({iconName:e.target.value})}>{posterIcons.map(([id,label])=><option value={id} key={id}>{label}</option>)}</select></label>
   <label>Outer shape<select value={layer.shape||"rounded"} onChange={e=>onChange({shape:e.target.value as OverlayLayer["shape"]})}>{shapes.map(shape=><option value={shape} key={shape}>{shape}</option>)}</select></label>
   <label>Icon color<input type="color" value={layer.iconColor||layer.foreground} onChange={e=>onChange({iconColor:e.target.value})}/></label>
   <label className="overlay-range"><span>Icon size</span><span>{Math.round(layer.iconSize||70)}%</span><input type="range" min="10" max="100" value={layer.iconSize||70} onChange={e=>onChange({iconSize:Number(e.target.value)})}/></label>
  </>:null}
  {kind==="shape"?<><label>Shape<select value={layer.shape||"rounded"} onChange={e=>onChange({shape:e.target.value as OverlayLayer["shape"]})}>{shapes.map(shape=><option value={shape} key={shape}>{shape}</option>)}</select></label><label className="overlay-range"><span>Shape height</span><span>{Math.round(layer.height||6)}%</span><input type="range" min="3" max="100" value={layer.height||6} onChange={e=>{const height=Number(e.target.value);onChange({height,...(layer.y+height>100?{position:"custom",y:Math.max(0,100-height)}:{})})}}/></label></>:null}
  <label>{kind==="text"?"Variable":"Optional variable"}<select value={variable} onChange={e=>{const value=e.target.value,rules=layer.conditions?.rules||[];onChange({variable:value,label:value==="custom_text"?"":`{${value}}`,contentPosition:kind==="text"?"none":layer.contentPosition==="none"?"inside":layer.contentPosition,...(rules.length===1&&rules[0].variable===variable?{conditions:{...layer.conditions,rules:[{...rules[0],variable:value}]}}:{})})}}>{grouped.map(([group,values])=><optgroup label={group} key={group}>{values?.map(value=><option value={value} key={value}>{variableLabel(value,kind)}</option>)}</optgroup>)}</select></label>
  {variable==="custom_text"?<label>{kind==="text"?"Custom text":"Optional custom text"}<input value={layer.label} maxLength={80} placeholder={kind==="text"?"Custom badge":"Leave blank for artwork only"} onChange={e=>onChange({label:e.target.value})}/></label>:null}
  {kind!=="text"?<label>Variable placement<select value={layer.contentPosition||"none"} onChange={e=>onChange({contentPosition:e.target.value as OverlayLayer["contentPosition"]})}><option value="none">Do not show text</option><option value="inside">Inside</option><option value="above">Above</option><option value="below">Below</option><option value="left">Left</option><option value="right">Right</option></select></label>:null}
  <label>Text fitting<select value={layer.textFit||"fixed"} onChange={e=>onChange({textFit:e.target.value as OverlayLayer["textFit"]})}><option value="fixed">Fixed size</option><option value="shrink">Auto-shrink to fit</option><option value="wrap">Wrap to lines</option></select></label>
  {layer.textFit==="wrap"?<label className="overlay-range"><span>Maximum lines</span><span>{layer.maxLines||2}</span><input type="range" min="1" max="6" value={layer.maxLines||2} onChange={e=>onChange({maxLines:Number(e.target.value)})}/></label>:null}
  {kind==="icon"&&!["none","inside"].includes(layer.contentPosition)?<label className="overlay-range"><span>Icon/text spacing</span><span>{Math.round(layer.contentGap??12)}px</span><input type="range" min="0" max="120" value={layer.contentGap??12} onChange={e=>onChange({contentGap:Number(e.target.value)})}/></label>:null}
  </div>
 </section>;
}
