const css = `.overlay-editor{width:min(1680px,calc(100vw - 32px))}.overlay-editor .overlay-editor-grid{grid-template-columns:220px minmax(300px,1fr) minmax(340px,1.1fr) 340px;grid-template-areas:"rail fields conditions preview";align-items:stretch;min-height:0;overflow:hidden}.overlay-editor .overlay-editor-rail,.overlay-editor .overlay-editor-fields,.overlay-editor .overlay-editor-grid>.overlay-condition-row{box-sizing:border-box;max-height:calc(100dvh - 190px);min-width:0;overflow-x:hidden;overflow-y:auto;padding-right:6px}.overlay-editor .overlay-editor-grid>.overlay-condition-row{grid-area:conditions;grid-column:auto;grid-row:auto;position:static}.overlay-editor .overlay-preview-column{grid-area:preview;align-self:start;position:sticky;top:0}.overlay-editor .overlay-preview-column .overlay-preview{width:min(100%,280px)}.overlay-editor .overlay-condition-rule,.overlay-editor .overlay-style-overrides{grid-template-columns:1fr}.overlay-editor .overlay-style-variants>header{align-items:stretch;flex-direction:column}@media(max-width:1350px){.overlay-editor .overlay-editor-grid{grid-template-columns:210px minmax(300px,1fr) 320px;grid-template-areas:"rail fields preview" "conditions conditions preview"}.overlay-editor .overlay-editor-grid>.overlay-condition-row{max-height:420px}}@media(max-width:1050px){.overlay-editor .overlay-editor-grid{grid-template-columns:minmax(280px,1fr) 320px;grid-template-areas:"rail preview" "fields preview" "conditions preview"}.overlay-editor .overlay-editor-rail,.overlay-editor .overlay-editor-fields,.overlay-editor .overlay-editor-grid>.overlay-condition-row{max-height:calc((100dvh - 220px)/2)}}@media(max-width:980px){.overlay-editor .overlay-editor-grid{grid-template-columns:1fr;grid-template-areas:"preview" "rail" "fields" "conditions";align-items:start;overflow-y:auto}.overlay-editor .overlay-editor-rail,.overlay-editor .overlay-editor-fields,.overlay-editor .overlay-editor-grid>.overlay-condition-row{max-height:none;overflow:visible;padding-right:0}.overlay-editor .overlay-preview-column{position:static}.overlay-editor .overlay-preview-column .overlay-preview{width:min(100%,220px)}}`;
const refinements = `.overlay-editor .overlay-layer-body>.notice{grid-column:1/-1;display:grid;grid-template-columns:auto minmax(0,1fr);gap:6px 10px;align-items:baseline;padding:10px 12px}.overlay-editor .overlay-layer-body>.notice strong,.overlay-editor .overlay-layer-body>.notice small{display:block;min-width:0;line-height:1.4}.overlay-editor .overlay-style-variants>header{position:static;display:grid;height:auto;padding:0 0 12px;border-bottom:1px solid var(--border);background:transparent;text-align:left}.overlay-editor .overlay-style-variants>header h3{margin:0;line-height:1.25}.overlay-editor .overlay-style-variants>header small{display:block;margin-top:5px;line-height:1.45}.overlay-editor .overlay-style-variants>header button{width:100%;margin-top:2px}.overlay-editor .overlay-style-variants>p{margin:0;line-height:1.5}.overlay-editor .overlay-condition-workspace{align-content:start}.overlay-editor .overlay-condition-builder,.overlay-editor .overlay-style-variants{align-content:start}@media(min-width:1351px){.overlay-editor .overlay-editor-grid{box-sizing:border-box;height:100%;max-height:100%;min-height:0}.overlay-editor .overlay-editor-rail,.overlay-editor .overlay-editor-fields,.overlay-editor .overlay-editor-grid>.overlay-condition-row{align-self:stretch;box-sizing:border-box;height:100%!important;min-height:0!important;max-height:100%!important;overflow-x:hidden!important;overflow-y:scroll!important;overscroll-behavior:contain;touch-action:pan-y;scrollbar-gutter:stable;padding-bottom:48px}.overlay-editor .overlay-editor-fields{scrollbar-color:var(--accent) color-mix(in srgb,var(--panel) 80%,#000);scrollbar-width:auto}}`;
const sizingFix = `@media(min-width:981px){.overlay-editor{height:calc(100dvh - 40px);grid-template-rows:auto minmax(0,1fr) auto}.overlay-editor .overlay-editor-grid{height:100%;max-height:100%;min-height:0}}`;

const id = "poster-overlay-editor-layout";
if (typeof document !== "undefined" && !document.getElementById(id)) {
  const style = document.createElement("style");
  style.id = id;
  style.textContent = css + refinements + sizingFix;
  document.head.append(style);
}
