import {useCallback,useEffect,useState} from "react";
import type {OverlayTemplate,PlexMatchReview,PlexOverlayConnection,PlexPosterApplication,PosterOverlayMountOptions} from "./poster-overlays-types";

const errorText=(reason:unknown)=>reason instanceof Error?reason.message:"Plex operation failed.";

export function PlexConnectionPanel({options,templates}:{options:PosterOverlayMountOptions;templates:OverlayTemplate[]}){
  const [plex,setPlex]=useState<PlexOverlayConnection|null>(null),[endpoint,setEndpoint]=useState(""),[token,setToken]=useState(""),[busy,setBusy]=useState(false),[selectedLibraries,setSelectedLibraries]=useState<string[]>([]),[review,setReview]=useState<PlexMatchReview|null>(null),[reviewFilter,setReviewFilter]=useState<"all"|"matched"|"unmatched"|"ambiguous">("all"),[reviewQuery,setReviewQuery]=useState(""),[templateId,setTemplateId]=useState(""),[selectedTargets,setSelectedTargets]=useState<string[]>([]),[confirmation,setConfirmation]=useState(""),[applications,setApplications]=useState<PlexPosterApplication[]>([]),[restoreId,setRestoreId]=useState(""),[restoreConfirmation,setRestoreConfirmation]=useState("");
  const load=useCallback(async()=>{try{const [connection,history]=await Promise.all([options.request<PlexOverlayConnection>("/api/poster-overlays/plex"),options.request<{applications:PlexPosterApplication[]}>("/api/poster-overlays/plex/applications")]);setPlex(connection);setEndpoint(connection.endpoint||"");setApplications(history.applications);setSelectedLibraries(current=>current.length?current:connection.libraries.map(item=>item.key));}catch(reason){options.notify(errorText(reason),"error");}},[options]);
  useEffect(()=>{void load();},[load]);
  const save=async()=>{setBusy(true);try{const value=await options.request<PlexOverlayConnection>("/api/poster-overlays/plex",{method:"POST",body:JSON.stringify({endpoint,token})});setPlex(value);setToken("");options.notify(`Connected to ${value.server?.name||"Plex"}.`);}catch(reason){options.notify(errorText(reason),"error");}finally{setBusy(false);}};
  const remove=async()=>{if(!confirm("Remove the saved Plex connection? Existing rollback records remain available."))return;setBusy(true);try{await options.request("/api/poster-overlays/plex",{method:"DELETE"});await load();setReview(null);options.notify("Plex connection removed.");}catch(reason){options.notify(errorText(reason),"error");}finally{setBusy(false);}};
  const reviewMatches=async()=>{setBusy(true);try{const value=await options.request<PlexMatchReview>("/api/poster-overlays/plex/matches",{method:"POST",body:JSON.stringify({libraryKeys:selectedLibraries})});setReview(value);setSelectedTargets([]);options.notify(`Plex match review completed: ${value.summary.matched} matched.`);}catch(reason){options.notify(errorText(reason),"error");}finally{setBusy(false);}};
  const selectedTemplate=templates.find(item=>item.id===templateId),targetKey=(item:PlexMatchReview["entries"][number])=>`${item.plexLibrary.key}:${item.domain}:${item.id}:${item.plex[0]?.ratingKey||""}`,compatible=(item:PlexMatchReview["entries"][number])=>item.status==="matched"&&Boolean(selectedTemplate)&&(selectedTemplate?.domain==="all"||selectedTemplate?.domain===item.domain),selectedEntries=(review?.entries||[]).filter(item=>selectedTargets.includes(targetKey(item))),selectedEntry=selectedEntries[0],confirmationText=selectedEntries.length===1?"APPLY TO PLEX":`APPLY ${selectedEntries.length} TO PLEX`,previewUrl=(mode:"original"|"preview",item:PlexMatchReview["entries"][number])=>{const params=new URLSearchParams({libraryKey:item.plexLibrary.key,ratingKey:item.plex[0].ratingKey});if(mode==="preview")params.set("templateId",templateId);return`/api/poster-overlays/plex/${mode}/${item.domain}/${item.id}?${params}`;};
  const visibleEntries=(review?.entries||[]).filter(item=>(reviewFilter==="all"||item.status===reviewFilter)&&(!reviewQuery.trim()||`${item.title} ${item.year||""} ${item.plexLibrary.title} ${item.externalIds.join(" ")}`.toLowerCase().includes(reviewQuery.trim().toLowerCase()))).slice(0,500);
  const toggleTarget=(key:string,checked:boolean)=>setSelectedTargets(current=>checked?(current.includes(key)?current:[...current,key]):current.filter(value=>value!==key));
  const apply=async()=>{if(!selectedEntries.length)return;setBusy(true);try{const targets=selectedEntries.map(item=>({domain:item.domain,mediaId:item.id,title:item.title,libraryKey:item.plexLibrary.key,ratingKey:item.plex[0].ratingKey}));if(targets.length===1){const value=await options.request<{application:PlexPosterApplication}>("/api/poster-overlays/plex/apply",{method:"POST",body:JSON.stringify({confirmation,templateId,...targets[0]})});setApplications(current=>[value.application,...current]);options.notify(`${targets[0].title} was updated in Plex. Rollback artwork is ready.`);}else{const value=await options.request<{applications:PlexPosterApplication[];summary:{applied:number;failed:number}}>("/api/poster-overlays/plex/apply-batch",{method:"POST",body:JSON.stringify({confirmation,templateId,targets})});setApplications(current=>[...value.applications,...current]);options.notify(`${value.summary.applied} Plex posters updated${value.summary.failed?`; ${value.summary.failed} failed`:""}.`);}setConfirmation("");}catch(reason){options.notify(errorText(reason),"error");}finally{setBusy(false);}};
  const restore=async(application:PlexPosterApplication)=>{setBusy(true);try{const value=await options.request<{application:PlexPosterApplication}>(`/api/poster-overlays/plex/applications/${application.id}/restore`,{method:"POST",body:JSON.stringify({confirmation:restoreConfirmation})});setApplications(current=>current.map(item=>item.id===application.id?value.application:item));setRestoreId("");setRestoreConfirmation("");options.notify(`${application.title} was restored to its captured Plex poster.`);}catch(reason){options.notify(errorText(reason),"error");}finally{setBusy(false);}};
  return <section className="panel" style={{marginBottom:16}}>
    <style>{`.plex-match-toolbar{display:grid;grid-template-columns:minmax(220px,1fr) auto;gap:12px;align-items:end}.plex-match-list{display:grid;gap:8px;max-height:620px;overflow:auto;padding:2px}.plex-match-row{display:grid;grid-template-columns:44px minmax(220px,1.3fr) minmax(260px,1fr) auto;gap:16px;align-items:center;min-height:76px;padding:12px 14px;border:1px solid var(--border);border-radius:12px;background:color-mix(in srgb,var(--panel,#08111f) 88%,transparent);cursor:pointer}.plex-match-row:hover{border-color:var(--accent,#58a6ff);background:color-mix(in srgb,var(--panel,#08111f) 78%,var(--accent,#58a6ff) 8%)}.plex-match-row.is-selected{border-color:var(--accent,#58a6ff);box-shadow:inset 3px 0 0 var(--accent,#58a6ff)}.plex-match-row.is-disabled{cursor:not-allowed;opacity:.68}.plex-match-check{display:grid;place-items:center;align-self:stretch}.plex-match-check input{width:22px;height:22px;margin:0}.plex-match-title,.plex-match-details{display:grid;gap:4px;min-width:0}.plex-match-title strong{font-size:1rem;line-height:1.25}.plex-match-title small,.plex-match-details small{color:var(--muted);overflow-wrap:anywhere}.plex-match-status{justify-self:end}.plex-match-empty{padding:28px;text-align:center;border:1px dashed var(--border);border-radius:12px;color:var(--muted)}@media(max-width:760px){.plex-match-toolbar,.plex-match-row{grid-template-columns:44px minmax(0,1fr)}.plex-match-details,.plex-match-status{grid-column:2}.plex-match-row{gap:8px 12px;min-height:96px}.plex-match-status{justify-self:start}.plex-match-list{max-height:70dvh}}`}</style>
    <div className="panel-heading"><div><span className="eyebrow">PLEX ARTWORK</span><h2>{plex?.configured?`Connected to ${plex.server?.name||"Plex"}`:"Connect Plex Media Server"}</h2><p className="muted">Match by external ID, preview real Plex artwork, then apply to one, selected, or all matched titles with an individual rollback poster for every change.</p></div><span className={`badge${plex?.configured?" green":""}`}>{plex?.configured?"CONNECTED":"NOT CONNECTED"}</span></div>
    <div className="overlay-scope-row"><label>Plex server URL<input type="url" value={endpoint} placeholder="http://192.168.1.10:32400" onChange={event=>setEndpoint(event.target.value)}/></label><label>Plex access token<input type="password" value={token} placeholder={plex?.configured?"Saved securely — leave blank to keep":"Enter token"} onChange={event=>setToken(event.target.value)} autoComplete="off"/></label></div>
    <div className="form-actions"><button type="button" className="primary" disabled={busy||!endpoint||(!plex?.configured&&!token)} onClick={()=>void save()}>{busy?"Working…":plex?.configured?"Revalidate connection":"Test and save"}</button>{plex?.configured?<button type="button" className="danger" disabled={busy} onClick={()=>void remove()}>Remove connection</button>:null}</div>
    {plex?.configured?<div className="notice"><strong>Choose libraries and revalidate matches</strong><div className="overlay-plex-badges">{plex.libraries.map(library=><label key={library.key}><input type="checkbox" checked={selectedLibraries.includes(library.key)} onChange={event=>setSelectedLibraries(current=>event.target.checked?[...current,library.key]:current.filter(key=>key!==library.key))}/>{library.title} · {library.type==="movie"?"Movies":"TV"}</label>)}</div><button type="button" className="secondary" disabled={busy||!selectedLibraries.length} onClick={()=>void reviewMatches()}>Review matches</button></div>:null}
    {review?<div className="notice">
      <div className="plex-match-toolbar">
        <label>Find a Plex library title<input type="search" value={reviewQuery} placeholder="Search title, year, library, TMDB, TVDB, or IMDb" onChange={event=>setReviewQuery(event.target.value)}/></label>
        <strong>{review.summary.matched} matched · {review.summary.unmatched} unmatched · {review.summary.ambiguous} ambiguous</strong>
      </div>
      <div className="form-actions">{(["all","matched","unmatched","ambiguous"] as const).map(value=><button type="button" className={reviewFilter===value?"primary":"secondary"} onClick={()=>setReviewFilter(value)} key={value}>{value}</button>)}</div>
      <label>Plex poster style<select value={templateId} onChange={event=>{setTemplateId(event.target.value);setSelectedTargets([]);}}><option value="">Choose a Plex style</option>{templates.filter(item=>item.enabled&&item.target==="plex").map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select><small className="muted">Only styles saved with the Plex artwork destination are available here.</small></label>
      <div className="form-actions"><button type="button" className="secondary" disabled={!selectedTemplate} onClick={()=>setSelectedTargets(review.entries.filter(compatible).slice(0,500).map(targetKey))}>Select all matched</button><button type="button" className="secondary" disabled={!selectedTargets.length} onClick={()=>setSelectedTargets([])}>Clear selection</button><span className="badge green">{selectedTargets.length} selected</span><span className="muted">Showing {visibleEntries.length} of {review.summary.total}</span></div>
      <div className="plex-match-list">{visibleEntries.map(item=>{const key=targetKey(item),canApply=compatible(item),selected=selectedTargets.includes(key);return <label className={`plex-match-row${selected?" is-selected":""}${canApply?"":" is-disabled"}`} key={key}>
        <span className="plex-match-check"><input type="checkbox" disabled={!canApply} checked={selected} aria-label={`Select ${item.title}`} onChange={event=>toggleTarget(key,event.target.checked)}/></span>
        <span className="plex-match-title"><strong>{item.title} {item.year?`(${item.year})`:""}</strong><small>{item.domain==="movie"?"Movie":"Television series"} · {item.plexLibrary.title}</small></span>
        <span className="plex-match-details"><small>{item.externalIds.join(" · ")||"No external IDs available"}</small><small>{item.status==="matched"?`Matched to ${item.plex[0]?.title||item.title}${item.plex[0]?.year?` (${item.plex[0].year})`:""}`:item.status==="ambiguous"?`${item.plex.length} possible Plex matches require review`:"No exact external-ID match in Plex"}</small></span>
        <span className={`plex-match-status badge${item.status==="matched"?" green":""}`}>{item.status.toUpperCase()}</span>
      </label>;})}{!visibleEntries.length?<div className="plex-match-empty">No library items match this search and status filter.</div>:null}</div>
    </div>:null}
    {selectedEntry&&selectedTemplate?<div className="notice"><h3>{selectedEntries.length===1?"One-title application review":`${selectedEntries.length}-title application review`}</h3><p>The first selected title is shown below as a representative exact preview. VynodeArr captures a separate original poster and rollback record before changing every selected title.</p><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,240px))",gap:16,alignItems:"start"}}><figure style={{margin:0}}><img style={{display:"block",width:"100%",maxWidth:240,aspectRatio:"2 / 3",objectFit:"cover",borderRadius:12}} src={previewUrl("original",selectedEntry)} alt={`Current Plex poster for ${selectedEntry.title}`}/><figcaption>Current Plex poster</figcaption></figure><figure style={{margin:0}}><img style={{display:"block",width:"100%",maxWidth:240,aspectRatio:"2 / 3",objectFit:"cover",borderRadius:12}} src={previewUrl("preview",selectedEntry)} alt={`Rendered overlay for ${selectedEntry.title}`}/><figcaption>Overlay preview</figcaption></figure></div><label>Type <strong>{confirmationText}</strong><input value={confirmation} onChange={event=>setConfirmation(event.target.value)} autoComplete="off"/></label><button type="button" className="danger" disabled={busy||confirmation!==confirmationText} onClick={()=>void apply()}>Capture rollback and apply {selectedEntries.length===1?"to Plex":`${selectedEntries.length} posters`}</button></div>:null}
    {applications.length?<div className="notice"><h3>Recent Plex poster changes</h3><div className="overlay-template-list">{applications.map(application=><article className="overlay-template-card" key={application.id}><div className="overlay-template-content"><strong>{application.title}</strong><small>{application.plexLibraryTitle} · {application.templateName} · {application.status}</small>{application.status==="applied"?<>{restoreId===application.id?<label>Type <strong>RESTORE PLEX POSTER</strong><input value={restoreConfirmation} onChange={event=>setRestoreConfirmation(event.target.value)} autoComplete="off"/></label>:null}<div className="form-actions"><button type="button" className="secondary" onClick={()=>{setRestoreId(application.id);setRestoreConfirmation("");}}>Prepare restore</button>{restoreId===application.id?<button type="button" className="danger" disabled={busy||restoreConfirmation!=="RESTORE PLEX POSTER"} onClick={()=>void restore(application)}>Restore captured poster</button>:null}</div></>:null}</div></article>)}</div></div>:null}
  </section>;
}
