const css = `.overlay-editor{width:min(1680px,calc(100vw - 32px))}.overlay-editor .overlay-editor-grid{grid-template-columns:220px minmax(300px,1fr) minmax(340px,1.1fr) 340px;grid-template-areas:"rail fields conditions preview";align-items:stretch;min-height:0;overflow:hidden}.overlay-editor .overlay-editor-rail,.overlay-editor .overlay-editor-fields,.overlay-editor .overlay-editor-grid>.overlay-condition-row{box-sizing:border-box;max-height:calc(100dvh - 190px);min-width:0;overflow-x:hidden;overflow-y:auto;padding-right:6px}.overlay-editor .overlay-editor-grid>.overlay-condition-row{grid-area:conditions;grid-column:auto;grid-row:auto;position:static}.overlay-editor .overlay-preview-column{grid-area:preview;align-self:start;position:sticky;top:0}.overlay-editor .overlay-preview-column .overlay-preview{width:min(100%,280px)}.overlay-editor .overlay-condition-rule,.overlay-editor .overlay-style-overrides{grid-template-columns:1fr}.overlay-editor .overlay-style-variants>header{align-items:stretch;flex-direction:column}@media(max-width:1350px){.overlay-editor .overlay-editor-grid{grid-template-columns:210px minmax(300px,1fr) 320px;grid-template-areas:"rail fields preview" "conditions conditions preview"}.overlay-editor .overlay-editor-grid>.overlay-condition-row{max-height:420px}}@media(max-width:1050px){.overlay-editor .overlay-editor-grid{grid-template-columns:minmax(280px,1fr) 320px;grid-template-areas:"rail preview" "fields preview" "conditions preview"}.overlay-editor .overlay-editor-rail,.overlay-editor .overlay-editor-fields,.overlay-editor .overlay-editor-grid>.overlay-condition-row{max-height:calc((100dvh - 220px)/2)}}@media(max-width:980px){.overlay-editor .overlay-editor-grid{grid-template-columns:1fr;grid-template-areas:"preview" "rail" "fields" "conditions";align-items:start;overflow-y:auto}.overlay-editor .overlay-editor-rail,.overlay-editor .overlay-editor-fields,.overlay-editor .overlay-editor-grid>.overlay-condition-row{max-height:none;overflow:visible;padding-right:0}.overlay-editor .overlay-preview-column{position:static}.overlay-editor .overlay-preview-column .overlay-preview{width:min(100%,220px)}}`;

const id = "poster-overlay-editor-layout";
if (typeof document !== "undefined" && !document.getElementById(id)) {
  const style = document.createElement("style");
  style.id = id;
  style.textContent = css;
  document.head.append(style);
}
