import type {OverlayMedia,OverlayTemplate} from "./poster-overlays-types";
import {OverlayLayerView,overlayLayerVisible,resolveConditionalLayer} from "./poster-overlay-layer";
import {PosterLayerContent,resolveLayerContent} from "./poster-overlay-icons";

export type TemplateIssue={severity:"error"|"warning";message:string};
const allLayers=(template:OverlayTemplate)=>[...template.layers,...(template.components||[]).flatMap(value=>value.layers),...(template.variants||[]).flatMap(value=>value.layers)];
export function validateTemplate(template:OverlayTemplate,variables:string[]):TemplateIssue[]{const issues:TemplateIssue[]=[];if(!template.layers.some(layer=>layer.enabled))issues.push({severity:"error",message:"Enable at least one layer."});const assets=new Set(allLayers(template).filter(layer=>layer.kind==="image"&&layer.assetId).map(layer=>layer.assetId));for(const [index,layer] of template.layers.entries()){const name=layer.name||`Layer ${index+1}`;if(layer.kind==="image"&&!layer.assetId)issues.push({severity:"error",message:`${name} is missing its image.`});if(layer.width<=0||layer.x<0||layer.x+layer.width>100||layer.y<0||layer.y+Math.max(0,layer.height)>100)issues.push({severity:"error",message:`${name} is outside the poster bounds.`});if(layer.enabled&&(layer.kind==="image"?layer.imageOpacity===0:layer.textOpacity===0&&layer.backgroundOpacity===0))issues.push({severity:"warning",message:`${name} is enabled but fully transparent.`});for(const token of layer.contentTemplate?.matchAll(/\{([^{}]+)\}/g)||[])if(!variables.includes(token[1]))issues.push({severity:"warning",message:`${name} uses unknown metadata {${token[1]}}.`});if(layer.conditions?.rules.some(rule=>rule.operator==="equals"&&!rule.value.trim()))issues.push({severity:"warning",message:`${name} has an equals condition with no value.`});if(layer.conditions?.join==="and"){const equals=layer.conditions.rules.filter(rule=>rule.operator==="equals"),values=new Map<string,Set<string>>();for(const rule of equals)values.set(rule.variable,(values.get(rule.variable)||new Set()).add(rule.value));if([...values.values()].some(set=>set.size>1))issues.push({severity:"warning",message:`${name} has contradictory conditions that can never match.`});}if(layer.componentId&&(!layer.componentLayerId||!template.components?.some(component=>component.id===layer.componentId&&component.layers.some(definition=>definition.id===layer.componentLayerId))))issues.push({severity:"error",message:`${name} has a broken component link.`});}for(const component of template.components||[])for(const layer of component.layers)if(layer.kind==="image"&&layer.assetId&&!assets.has(layer.assetId))issues.push({severity:"error",message:`Component ${component.name} references a missing image.`});return [...new Map(issues.map(issue=>[issue.message,issue])).values()].slice(0,20);}
const valueFor=(layer:OverlayTemplate["layers"][number],item:OverlayMedia)=>layer.variable==="custom_text"?layer.label:String(item.artwork?.overlayValues?.[layer.variable]??(item as unknown as Record<string,unknown>)[layer.variable]??"");
export default function OverlayQuality({template,items,issues}:{template:OverlayTemplate;items:OverlayMedia[];issues:TemplateIssue[]}){return <section className="overlay-quality"><header><div><strong>Real-title preview matrix</strong><small>Check long titles, missing metadata, conditions, and contrast before saving.</small></div><span className={issues.some(issue=>issue.severity==="error")?"badge danger":"badge"}>{issues.length?`${issues.length} issue${issues.length===1?"":"s"}`:"Ready"}</span></header>{issues.length?<ul>{issues.map(issue=><li className={issue.severity} key={issue.message}><strong>{issue.severity}</strong> {issue.message}</li>)}</ul>:null}<div className="overlay-preview-matrix">{items.slice(0,4).map(item=><article key={item.id}><div className="overlay-matrix-poster" style={{containerType:"inline-size",backgroundImage:`url(${item.artwork?.originalUrl||item.artwork?.url||""})`}}>{template.layers.map(layer=>{const values=item.artwork?.overlayValues||{},resolved=resolveConditionalLayer(layer,values),value=resolveLayerContent(resolved,values)||valueFor(resolved,item);return overlayLayerVisible(resolved,value,values)?<OverlayLayerView key={layer.id} layer={resolved}><PosterLayerContent layer={resolved} text={`${resolved.prefix}${value}${resolved.suffix}`}/></OverlayLayerView>:null;})}</div><strong>{item.title}</strong><small>{item.year||"Year unknown"}</small></article>)}</div>{!items.length?<p className="muted">Choose a media type with available titles to populate this matrix.</p>:null}</section>}
