import type { CSSProperties } from "react";
import type { OverlayDomain, OverlayLayer, OverlayTemplate } from "./poster-overlays-types";
import { PosterIcon, posterIcons } from "./poster-overlay-icons";
const shapes: Array<[OverlayLayer["shape"],string,CSSProperties]>=[
 ["rounded","Rounded",{borderRadius:6}],["square","Square",{}],["pill","Pill",{borderRadius:999}],
 ["circle","Circle",{borderRadius:"50%",aspectRatio:"1"}],["ticket","Ticket",{clipPath:"polygon(4% 0,96% 0,100% 22%,96% 50%,100% 78%,96% 100%,4% 100%,0 78%,4% 50%,0 22%)"}],
 ["ribbon","Ribbon",{clipPath:"polygon(0 0,94% 0,100% 50%,94% 100%,0 100%,5% 50%)"}],["tag","Tag",{clipPath:"polygon(0 0,88% 0,100% 50%,88% 100%,0 100%)"}],
 ["hexagon","Hexagon",{clipPath:"polygon(8% 0,92% 0,100% 50%,92% 100%,8% 100%,0 50%)"}],["chevron","Chevron",{clipPath:"polygon(0 0,88% 0,100% 50%,88% 100%,0 100%,12% 50%)"}],
];
const css=`.overlay-editor{width:min(1380px,100%)}.overlay-editor-grid{grid-template-columns:220px minmax(260px,1fr) 340px;grid-template-areas:"rail preview fields";align-items:start}.overlay-editor-rail{grid-area:rail;display:grid;gap:12px;align-content:start}.overlay-editor-fields{grid-area:fields;max-height:calc(100dvh - 190px);overflow:auto;padding-right:4px}.overlay-preview-column{grid-area:preview;justify-self:center}.overlay-layer-list{display:grid;gap:6px}.overlay-layer-list button{display:grid;grid-template-columns:auto 1fr auto;gap:7px;align-items:center;width:100%;padding:8px;text-align:left}.overlay-layer-list button.active{border-color:var(--accent);background:rgba(72,95,190,.22)}.overlay-layer-list small{color:var(--muted)}.overlay-icon-library{display:grid;grid-template-columns:repeat(4,1fr);gap:6px}.overlay-icon-library button{display:grid;gap:3px;min-width:0;padding:7px 3px;place-items:center}.overlay-icon-library svg{width:20px}.overlay-icon-library span{max-width:100%;overflow:hidden;font-size:.58rem;text-overflow:ellipsis}.overlay-shape-library{display:grid;grid-template-columns:repeat(3,1fr);gap:6px}.overlay-shape-library button{display:grid;gap:5px;min-width:0;padding:6px;place-items:center}.overlay-shape-library button.active{border-color:var(--accent)}.overlay-shape-swatch{display:block;width:34px;height:18px;background:linear-gradient(135deg,var(--accent),#31d6c7)}.overlay-shape-library small{font-size:.58rem}.overlay-layer-editor[hidden]{display:none}.overlay-layer-editor{border:0!important}.overlay-layer-editor>summary{display:none!important}.overlay-layer-body>*{min-width:0}.overlay-layer-body input,.overlay-layer-body select{box-sizing:border-box;width:100%;min-width:0}@media(max-width:380px){.overlay-layer-body{grid-template-columns:1fr!important}}@media(max-width:980px){.overlay-editor-grid{grid-template-columns:1fr;grid-template-areas:"preview" "rail" "fields"}.overlay-editor-fields{max-height:none}.overlay-editor-rail{grid-template-columns:1fr 1fr}.overlay-icon-library{grid-template-columns:repeat(6,1fr)}}@media(max-width:600px){.overlay-editor-rail{grid-template-columns:1fr}.overlay-icon-library{grid-template-columns:repeat(4,1fr)}}`;
export default function EditorRail({editing,selectedId,query,onQuery,onSelect,onChange,onAddText,onAddIcon,onAddShape}:{editing:OverlayTemplate;selectedId:string;query:string;onQuery:(value:string)=>void;onSelect:(id:string)=>void;onChange:(changes:Partial<OverlayTemplate>)=>void;onAddText:()=>void;onAddIcon:(name:string)=>void;onAddShape:(shape:OverlayLayer["shape"])=>void}){
 const icons=posterIcons.filter(([,label])=>!query||label.toLowerCase().includes(query.toLowerCase()));
 return <aside className="overlay-editor-rail" style={{maxHeight:"calc(100dvh - 190px)",overflow:"auto",paddingRight:4}}><style>{css}</style><label>Name<input value={editing.name} maxLength={80} onChange={e=>onChange({name:e.target.value})}/></label><label>Library<select value={editing.domain} onChange={e=>onChange({domain:e.target.value as OverlayDomain})}><option value="all">Movies & television</option><option value="movie">Movies</option><option value="tv">Television</option></select></label><div className="panel-heading"><h3>Layers</h3><button className="secondary" onClick={onAddText}>Add text</button></div><div className="overlay-layer-list">{editing.layers.map((layer,index)=><button className={layer.id===selectedId?"active secondary":"secondary"} onClick={()=>onSelect(layer.id)} key={layer.id}><span>{index+1}</span><strong>{layer.kind==="icon"?posterIcons.find(([id])=>id===layer.iconName)?.[1]||"Icon":layer.kind==="shape"?`${layer.shape} shape`:layer.variable.replaceAll("_"," ")}</strong><small>{layer.enabled?"On":"Off"}</small></button>)}</div><div><h3>Add shape</h3><small className="muted">Creates an independent shape layer</small></div><div className="overlay-shape-library">{shapes.map(([id,label,style])=><button className="secondary" title={`Add ${label} shape`} onClick={()=>onAddShape(id)} key={id}><span className="overlay-shape-swatch" style={style}/><small>{label}</small></button>)}</div><div><h3>Media icons</h3><input aria-label="Find media icons" placeholder="Find icons" value={query} onChange={e=>onQuery(e.target.value)}/></div><div className="overlay-icon-library">{icons.map(([id,label])=><button className="secondary" title={`Add ${label} icon`} onClick={()=>onAddIcon(id)} key={id}><PosterIcon name={id}/><span>{label}</span></button>)}</div></aside>;
}
