import {useCallback,useEffect,useState} from "react";
import type {OverlayTemplate,PlexMatchReview,PlexOverlayConnection,PlexPosterApplication,PosterOverlayMountOptions} from "./poster-overlays-types";

const errorText=(reason:unknown)=>reason instanceof Error?reason.message:"Plex operation failed.";

export function PlexConnectionPanel({options,templates}:{options:PosterOverlayMountOptions;templates:OverlayTemplate[]}){
  const [plex,setPlex]=useState<PlexOverlayConnection|null>(null),[endpoint,setEndpoint]=useState(""),[token,setToken]=useState(""),[busy,setBusy]=useState(false),[selectedLibraries,setSelectedLibraries]=useState<string[]>([]),[review,setReview]=useState<PlexMatchReview|null>(null),[reviewFilter,setReviewFilter]=useState<"all"|"matched"|"unmatched"|"ambiguous">("all"),[templateId,setTemplateId]=useState(""),[selectedTarget,setSelectedTarget]=useState(""),[confirmation,setConfirmation]=useState(""),[applications,setApplications]=useState<PlexPosterApplication[]>([]),[restoreId,setRestoreId]=useState(""),[restoreConfirmation,setRestoreConfirmation]=useState("");
  const load=useCallback(async()=>{try{const [connection,history]=await Promise.all([options.request<PlexOverlayConnection>("/api/poster-overlays/plex"),options.request<{applications:PlexPosterApplication[]}>("/api/poster-overlays/plex/applications")]);setPlex(connection);setEndpoint(connection.endpoint||"");setApplications(history.applications);setSelectedLibraries(current=>current.length?current:connection.libraries.map(item=>item.key));}catch(reason){options.notify(errorText(reason),"error");}},[options]);
  useEffect(()=>{void load();},[load]);
  const save=async()=>{setBusy(true);try{const value=await options.request<PlexOverlayConnection>("/api/poster-overlays/plex",{method:"POST",body:JSON.stringify({endpoint,token})});setPlex(value);setToken("");options.notify(`Connected to ${value.server?.name||"Plex"}.`);}catch(reason){options.notify(errorText(reason),"error");}finally{setBusy(false);}};
  const remove=async()=>{if(!confirm("Remove the saved Plex connection? Existing rollback records remain available."))return;setBusy(true);try{await options.request("/api/poster-overlays/plex",{method:"DELETE"});await load();setReview(null);options.notify("Plex connection removed.");}catch(reason){options.notify(errorText(reason),"error");}finally{setBusy(false);}};
  const reviewMatches=async()=>{setBusy(true);try{const value=await options.request<PlexMatchReview>("/api/poster-overlays/plex/matches",{method:"POST",body:JSON.stringify({libraryKeys:selectedLibraries})});setReview(value);setSelectedTarget("");options.notify(`Plex match review completed: ${value.summary.matched} matched.`);}catch(reason){options.notify(errorText(reason),"error");}finally{setBusy(false);}};
  const selectedTemplate=templates.find(item=>item.id===templateId),targetKey=(item:PlexMatchReview["entries"][number])=>`${item.plexLibrary.key}:${item.domain}:${item.id}:${item.plex[0]?.ratingKey||""}`,selectedEntry=review?.entries.find(item=>targetKey(item)===selectedTarget),previewUrl=(mode:"original"|"preview",item:PlexMatchReview["entries"][number])=>{const params=new URLSearchParams({libraryKey:item.plexLibrary.key,ratingKey:item.plex[0].ratingKey});if(mode==="preview")params.set("templateId",templateId);return`/api/poster-overlays/plex/${mode}/${item.domain}/${item.id}?${params}`;};
  const apply=async()=>{if(!selectedEntry)return;setBusy(true);try{const value=await options.request<{application:PlexPosterApplication}>("/api/poster-overlays/plex/apply",{method:"POST",body:JSON.stringify({confirmation,templateId,domain:selectedEntry.domain,mediaId:selectedEntry.id,libraryKey:selectedEntry.plexLibrary.key,ratingKey:selectedEntry.plex[0].ratingKey})});setApplications(current=>[value.application,...current]);setConfirmation("");options.notify(`${selectedEntry.title} was updated in Plex. Rollback artwork is ready.`);}catch(reason){options.notify(errorText(reason),"error");}finally{setBusy(false);}};
  const restore=async(application:PlexPosterApplication)=>{setBusy(true);try{const value=await options.request<{application:PlexPosterApplication}>(`/api/poster-overlays/plex/applications/${application.id}/restore`,{method:"POST",body:JSON.stringify({confirmation:restoreConfirmation})});setApplications(current=>current.map(item=>item.id===application.id?value.application:item));setRestoreId("");setRestoreConfirmation("");options.notify(`${application.title} was restored to its captured Plex poster.`);}catch(reason){options.notify(errorText(reason),"error");}finally{setBusy(false);}};
  return <section className="panel" style={{marginBottom:16}}>
    <div className="panel-heading"><div><span className="eyebrow">PLEX ARTWORK</span><h2>{plex?.configured?`Connected to ${plex.server?.name||"Plex"}`:"Connect Plex Media Server"}</h2><p className="muted">Match by external ID, preview against real Plex artwork, then apply to one title with a captured rollback poster.</p></div><span className={`badge${plex?.configured?" green":""}`}>{plex?.configured?"CONNECTED":"NOT CONNECTED"}</span></div>
    <div className="overlay-scope-row"><label>Plex server URL<input type="url" value={endpoint} placeholder="http://192.168.1.10:32400" onChange={event=>setEndpoint(event.target.value)}/></label><label>Plex access token<input type="password" value={token} placeholder={plex?.configured?"Saved securely — leave blank to keep":"Enter token"} onChange={event=>setToken(event.target.value)} autoComplete="off"/></label></div>
    <div className="form-actions"><button type="button" className="primary" disabled={busy||!endpoint||(!plex?.configured&&!token)} onClick={()=>void save()}>{busy?"Working…":plex?.configured?"Revalidate connection":"Test and save"}</button>{plex?.configured?<button type="button" className="danger" disabled={busy} onClick={()=>void remove()}>Remove connection</button>:null}</div>
    {plex?.configured?<div className="notice"><strong>Choose libraries and revalidate matches</strong><div className="overlay-plex-badges">{plex.libraries.map(library=><label key={library.key}><input type="checkbox" checked={selectedLibraries.includes(library.key)} onChange={event=>setSelectedLibraries(current=>event.target.checked?[...current,library.key]:current.filter(key=>key!==library.key))}/>{library.title} · {library.type==="movie"?"Movies":"TV"}</label>)}</div><button type="button" className="secondary" disabled={busy||!selectedLibraries.length} onClick={()=>void reviewMatches()}>Review matches</button></div>:null}
    {review?<div className="notice"><strong>{review.summary.matched} matched · {review.summary.unmatched} unmatched · {review.summary.ambiguous} ambiguous</strong><div className="form-actions">{(["all","matched","unmatched","ambiguous"] as const).map(value=><button type="button" className={reviewFilter===value?"primary":"secondary"} onClick={()=>setReviewFilter(value)} key={value}>{value}</button>)}</div><label>Poster style<select value={templateId} onChange={event=>{setTemplateId(event.target.value);setSelectedTarget("");}}><option value="">Choose a style</option>{templates.filter(item=>item.enabled).map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><div className="overlay-template-list">{review.entries.filter(item=>reviewFilter==="all"||item.status===reviewFilter).slice(0,200).map(item=>{const key=targetKey(item),compatible=item.status==="matched"&&Boolean(selectedTemplate)&&(selectedTemplate?.domain==="all"||selectedTemplate?.domain===item.domain);return <article className="overlay-template-card" key={key}><div className="overlay-template-content"><label><input type="radio" name="plex-target" disabled={!compatible} checked={selectedTarget===key} onChange={()=>setSelectedTarget(key)}/><strong>{item.title} {item.year?`(${item.year})`:""}</strong></label><small>{item.plexLibrary.title} · {item.externalIds.join(" · ")||"No external IDs"}</small><span className={`badge${item.status==="matched"?" green":""}`}>{item.status.toUpperCase()}</span></div></article>;})}</div></div>:null}
    {selectedEntry&&selectedTemplate?<div className="notice"><h3>One-title application review</h3><p>VynodeArr will capture the current Plex poster before uploading this exact preview.</p><div className="overlay-plex-preview"><figure><img src={previewUrl("original",selectedEntry)} alt={`Current Plex poster for ${selectedEntry.title}`}/><figcaption>Current Plex poster</figcaption></figure><figure><img src={previewUrl("preview",selectedEntry)} alt={`Rendered overlay for ${selectedEntry.title}`}/><figcaption>Exact overlay preview</figcaption></figure></div><label>Type <strong>APPLY TO PLEX</strong><input value={confirmation} onChange={event=>setConfirmation(event.target.value)} autoComplete="off"/></label><button type="button" className="danger" disabled={busy||confirmation!=="APPLY TO PLEX"} onClick={()=>void apply()}>Capture rollback and apply to Plex</button></div>:null}
    {applications.length?<div className="notice"><h3>Recent Plex poster changes</h3><div className="overlay-template-list">{applications.map(application=><article className="overlay-template-card" key={application.id}><div className="overlay-template-content"><strong>{application.title}</strong><small>{application.plexLibraryTitle} · {application.templateName} · {application.status}</small>{application.status==="applied"?<>{restoreId===application.id?<label>Type <strong>RESTORE PLEX POSTER</strong><input value={restoreConfirmation} onChange={event=>setRestoreConfirmation(event.target.value)} autoComplete="off"/></label>:null}<div className="form-actions"><button type="button" className="secondary" onClick={()=>{setRestoreId(application.id);setRestoreConfirmation("");}}>Prepare restore</button>{restoreId===application.id?<button type="button" className="danger" disabled={busy||restoreConfirmation!=="RESTORE PLEX POSTER"} onClick={()=>void restore(application)}>Restore captured poster</button>:null}</div></>:null}</div></article>)}</div></div>:null}
  </section>;
}
