import {useCallback,useEffect,useMemo,useState} from 'react';
import type {ProviderDomain,ProviderField,ProviderKind,ProviderRecord,ProviderSettingsMountOptions} from './provider-settings-types';

const errorText=(reason:unknown)=>reason instanceof Error?reason.message:'The provider could not be updated.';
const providerName=(item:ProviderRecord)=>String(item.name||item.implementationName||item.implementation||'Provider');
const clone=<T,>(value:T):T=>structuredClone(value);
const Tabs=({kind}:{kind:ProviderKind})=><nav className="settings-tabs"><a href="#service/root-folders">Root Folders</a><a href="#service/media-management">Media Management</a><a href="#service/profiles">Quality Profiles</a><a href="#service/custom-formats">Custom Formats</a><a href="#service/guide-templates">Guide Templates</a><a href="#service/release-profiles">Release Profiles</a><a className={kind==='indexers'?'active':''} href="#service/indexers">Indexers</a><a className={kind==='downloadClients'?'active':''} href="#service/download-clients">Download Clients</a><a href="#service/discover">Discover</a><a href="#management">Advanced</a></nav>;

function Field({field,onChange}:{field:ProviderField;onChange:(value:unknown)=>void}){
  const label=field.label||field.name;
  if(['checkbox','boolean'].includes(field.type||''))return <label className="config-switch"><span><strong>{label}</strong>{field.helpText?<small>{field.helpText}</small>:null}</span><input type="checkbox" checked={Boolean(field.value)} onChange={event=>onChange(event.target.checked)}/></label>;
  if(field.type==='select'&&field.selectOptions?.length){const multiple=Array.isArray(field.value),selected=multiple?(field.value as unknown[]).map(String):String(field.value??''),native=(value:string)=>field.selectOptions?.find(option=>String(option.value)===value)?.value??value;return <label>{label}{field.helpText?<small>{field.helpText}</small>:null}<select multiple={multiple} value={selected} onChange={event=>onChange(multiple?[...event.target.selectedOptions].map(option=>native(option.value)):native(event.target.value))}>{field.selectOptions.map(option=><option value={String(option.value)} key={String(option.value)}>{option.name}{option.hint?` · ${option.hint}`:''}</option>)}</select></label>;}
  const secret=['password','apiKey'].includes(field.privacy||'')||field.type==='password',value=field.value==='********'?'':String(field.value??'');
  return <label>{label}{field.helpText?<small>{field.helpText}</small>:null}<input type={secret?'password':field.type==='number'?'number':'text'} step={field.isFloat?'any':undefined} value={value} placeholder={secret&&field.value==='********'?'Stored securely — leave blank to keep':''} onChange={event=>onChange(field.type==='number'?(event.target.value===''?null:Number(event.target.value)):event.target.value)}/></label>;
}

export function ProviderSettingsView({options}:{options:ProviderSettingsMountOptions}){
  const {kind}=options,indexer=kind==='indexers',title=indexer?'Indexers':'Download Clients',schema=indexer?'indexerSchemas':'downloadClientSchemas',testResource=indexer?'indexerTest':'downloadClientTest';
  const [domain,setDomain]=useState<ProviderDomain>('movie'),[items,setItems]=useState<ProviderRecord[]>([]),[selected,setSelected]=useState<ProviderRecord|null>(null),[definitions,setDefinitions]=useState<ProviderRecord[]>([]),[advanced,setAdvanced]=useState(false),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[fieldErrors,setFieldErrors]=useState<Record<string,string>>({}),[policy,setPolicy]=useState<ProviderRecord|null>(null);
  const load=useCallback(async()=>{setLoading(true);setError('');setSelected(null);try{
    const providers=await options.request<{result:ProviderRecord[]}>(`/api/manage/${domain}/${kind}`);
    setItems(providers.result||[]);
    if(indexer)setPolicy(null);
    else{
      const settings=await options.request<{result:ProviderRecord}>(`/api/manage/${domain}/downloadClientSettings`);
      setPolicy(settings.result||null);
    }
  }catch(reason){setError(errorText(reason));}finally{setLoading(false);}},[domain,indexer,kind,options]);
  useEffect(()=>{void load();},[load]);
  const visibleFields=useMemo(()=>(selected?.fields||[]).map((field,index)=>({field,index})).filter(({field})=>!field.hidden&&(advanced||!field.advanced)),[selected,advanced]);
  const update=(key:string,value:unknown)=>setSelected(current=>current?{...current,[key]:value}:null);
  const updateField=(index:number,value:unknown)=>setSelected(current=>current?{...current,fields:(current.fields||[]).map((field,i)=>i===index?{...field,value}:field)}:null);
  const add=async()=>{setBusy('add');try{const value=await options.request<{result:ProviderRecord[]}>(`/api/manage/${domain}/${schema}`),records=value.result||[];setDefinitions(records);setSelected(clone(records[0]||{}));setAdvanced(false);}catch(reason){options.notify(errorText(reason),'error');}finally{setBusy('');}};
  const chooseDefinition=(index:number)=>setSelected(clone(definitions[index]||{}));
  const validate=()=>{const errors:Record<string,string>={};if(!String(selected?.name||'').trim())errors.name='Enter a name.';for(const field of selected?.fields||[])if(field.type==='number'&&field.value!==null&&!Number.isFinite(Number(field.value)))errors[field.name]='Enter a valid number.';setFieldErrors(errors);return !Object.keys(errors).length;};
  const test=async()=>{if(!selected||!validate())return;setBusy('test');try{await options.request(`/api/manage/${domain}/${testResource}`,{method:'POST',body:JSON.stringify(selected)});options.notify(`${indexer?'Indexer':'Download client'} connection successful.`);}catch(reason){options.notify(errorText(reason),'error');}finally{setBusy('');}};
  const save=async()=>{if(!selected||!validate())return;const exists=selected.id!==undefined;setBusy('save');try{await options.request(`/api/manage/${domain}/${kind}${exists?`/${selected.id}`:''}`,{method:exists?'PUT':'POST',body:JSON.stringify(selected)});options.notify(`${indexer?'Indexer':'Download client'} saved.`);await load();}catch(reason){options.notify(errorText(reason),'error');}finally{setBusy('');}};
  const remove=async()=>{if(selected?.id===undefined||!confirm(`Delete ${providerName(selected)}?`))return;setBusy('delete');try{await options.request(`/api/manage/${domain}/${kind}/${selected.id}`,{method:'DELETE'});options.notify('Provider deleted.');await load();}catch(reason){options.notify(errorText(reason),'error');}finally{setBusy('');}};
  const savePolicy=async()=>{if(!policy)return;setBusy('policy');try{await options.request(`/api/manage/${domain}/downloadClientSettings`,{method:'PUT',body:JSON.stringify(policy)});options.notify('Download handling saved.');}catch(reason){options.notify(errorText(reason),'error');}finally{setBusy('');}};
  return <div className="provider-settings-route"><div className="hero"><div><span className="eyebrow">SERVICE SETTINGS</span><h1>{title}</h1><p className="lede">{indexer?'Configure native release sources and decide which search modes each source may serve.':'Configure native download applications and completed/failed download handling.'}</p></div><button className="primary" disabled={busy==='add'} onClick={()=>void add()}>Add {indexer?'indexer':'download client'}</button></div><Tabs kind={kind}/>
    <div className="management-toolbar"><label>Library<select value={domain} onChange={event=>setDomain(event.target.value as ProviderDomain)}><option value="movie">Movies</option><option value="tv">Television</option></select></label><button className="secondary" onClick={()=>void load()}>Reload from engine</button></div>
    {!indexer&&policy?<section className="panel provider-policy"><div><h2>Download handling</h2><p className="muted">These settings are applied directly to the selected engine.</p></div><div className="provider-policy-controls">{['enableCompletedDownloadHandling','removeCompletedDownloads','redownloadFailed'].filter(key=>key in policy).map(key=><label className="config-switch" key={key}><span><strong>{key.replace(/([A-Z])/g,' $1')}</strong></span><input type="checkbox" checked={Boolean(policy[key])} onChange={event=>setPolicy(current=>current?{...current,[key]:event.target.checked}:current)}/></label>)}</div><button className="secondary" disabled={busy==='policy'} onClick={()=>void savePolicy()}>Save handling</button></section>:null}
    {error?<section className="panel error-state"><h2>{title} unavailable</h2><p>{error}</p><button className="secondary" onClick={()=>void load()}>Try again</button></section>:<div className="provider-settings-layout"><section className="panel provider-list"><div className="panel-heading"><h2>Configured</h2><span className="badge">{items.length}</span></div>{loading?<div className="skeleton">Loading…</div>:items.length?items.map(item=><button className={selected?.id===item.id?'profile-item selected':'profile-item'} key={String(item.id)} onClick={()=>{setDefinitions([]);setFieldErrors({});setSelected(clone(item));}}><strong>{providerName(item)}</strong><small>{String(item.implementationName||item.implementation||item.protocol||'Native provider')} · {item.enable===false?'Disabled':'Enabled'}</small></button>):<div className="empty compact"><h3>No {title.toLowerCase()}</h3><p>Add one to begin.</p></div>}</section>
      <section className="panel provider-editor">{selected?<><div className="panel-heading"><div><span className="eyebrow">{selected.id===undefined?'NEW PROVIDER':'ENGINE CONFIGURATION'}</span><h2>{providerName(selected)}</h2></div><label className="advanced-toggle"><input type="checkbox" checked={advanced} onChange={event=>setAdvanced(event.target.checked)}/> Show advanced</label></div>{definitions.length?<label>Provider type<select onChange={event=>chooseDefinition(Number(event.target.value))}>{definitions.map((definition,index)=><option value={index} key={`${providerName(definition)}-${index}`}>{providerName(definition)}</option>)}</select></label>:null}<div className="provider-core-grid"><label>Name<input value={String(selected.name||'')} onChange={event=>update('name',event.target.value)}/>{fieldErrors.name?<small className="form-error">{fieldErrors.name}</small>:null}</label><label>Priority<input type="number" value={Number(selected.priority??25)} onChange={event=>update('priority',Number(event.target.value))}/></label></div><div className="provider-toggles"><label className="config-switch"><span><strong>Enabled</strong></span><input type="checkbox" checked={selected.enable!==false} onChange={event=>update('enable',event.target.checked)}/></label>{(indexer?['enableRss','enableAutomaticSearch','enableInteractiveSearch']:['removeCompletedDownloads','removeFailedDownloads']).map(key=><label className="config-switch" key={key}><span><strong>{key.replace(/([A-Z])/g,' $1')}</strong></span><input type="checkbox" checked={Boolean(selected[key])} onChange={event=>update(key,event.target.checked)}/></label>)}</div><div className="provider-native-fields">{visibleFields.map(({field,index})=><div key={`${field.name}-${index}`}><Field field={field} onChange={value=>updateField(index,value)}/>{fieldErrors[field.name]?<small className="form-error">{fieldErrors[field.name]}</small>:null}</div>)}</div><div className="form-actions">{selected.id!==undefined?<button className="danger" disabled={Boolean(busy)} onClick={()=>void remove()}>Delete</button>:null}<button className="secondary" disabled={Boolean(busy)} onClick={()=>void test()}>{busy==='test'?'Testing…':'Test connection'}</button><button className="primary" disabled={Boolean(busy)} onClick={()=>void save()}>{busy==='save'?'Saving…':'Save to engine'}</button></div></>:<div className="empty"><h2>Select a provider</h2><p>Choose a configured provider or add a new one.</p></div>}</section></div>}
  </div>;
}
