import {useCallback,useEffect,useState,type FormEvent} from 'react';
import {ServiceTabs} from './service-tabs';
import {EngineInstanceSelect,useEngineInstance} from './engine-instance-control';
import type {CustomFormat,EngineDomain,QualityDefinition,QualityItem,QualityProfile,QualityProfilesMountOptions} from './quality-profiles-types';

const errorText=(value:unknown)=>value instanceof Error?value.message:'Quality profiles are unavailable.';
const key=(item:QualityItem)=>item.id??item.quality?.id??0;
const clone=<T,>(value:T):T=>structuredClone(value);

export function QualityProfilesView({options}:{options:QualityProfilesMountOptions}){
 const [domain,setDomain]=useState<EngineDomain>('movie'),[profiles,setProfiles]=useState<QualityProfile[]>([]),[formats,setFormats]=useState<CustomFormat[]>([]),[definitions,setDefinitions]=useState<QualityDefinition[]>([]),[limits,setLimits]=useState({min:0,max:2000}),[selected,setSelected]=useState<QualityProfile|null>(null),[isNew,setIsNew]=useState(false),[loading,setLoading]=useState(true),[failure,setFailure]=useState('');
 const engine=useEngineInstance(options.request,domain);
 const load=useCallback(async()=>{if(!engine.ready)return;setLoading(true);setFailure('');setSelected(null);options.onDirtyChange(false);try{const [p,f,d,l]=await Promise.all([options.request<{result:QualityProfile[]}>(engine.route(`/api/manage/${domain}/profiles`)),options.request<{result:CustomFormat[]}>(engine.route(`/api/manage/${domain}/customFormats`)),options.request<{result:QualityDefinition[]}>(engine.route(`/api/manage/${domain}/qualityDefinitions`)),options.request<{result:{min:number;max:number}}>(engine.route(`/api/manage/${domain}/qualityDefinitionLimits`)).catch(()=>({result:{min:0,max:domain==='movie'?2000:1000}}))]);setProfiles(p.result);setFormats(f.result);setDefinitions(d.result||[]);setLimits(l.result);}catch(reason){setFailure(errorText(reason));}finally{setLoading(false);}},[domain,options,engine.instanceId,engine.ready]);
 useEffect(()=>{void load();},[load]);
 const choose=(profile:QualityProfile,newProfile=false)=>{setSelected(clone(profile));setIsNew(newProfile);options.onDirtyChange(newProfile);};
 const change=(mutate:(profile:QualityProfile)=>void)=>setSelected(current=>{if(!current)return current;const next=clone(current);mutate(next);options.onDirtyChange(true);return next;});
 const create=async()=>{try{const {result}=await options.request<{result:QualityProfile}>(engine.route(`/api/manage/${domain}/profileSchema`));choose(result,true);}catch(reason){options.notify(errorText(reason),'error');}};
 const save=async(event:FormEvent)=>{event.preventDefault();if(!selected)return;try{await options.request(engine.route(`/api/manage/${domain}/profiles${isNew?'':`/${selected.id}`}`),{method:isNew?'POST':'PUT',body:JSON.stringify(selected)});options.notify('Quality profile saved.');await load();}catch(reason){options.notify(errorText(reason),'error');}};
 const remove=async()=>{if(!selected?.id||!confirm(`Delete ${selected.name}? Profiles currently assigned to media cannot be deleted.`))return;try{await options.request(engine.route(`/api/manage/${domain}/profiles/${selected.id}`),{method:'DELETE'});options.notify('Profile deleted.');await load();}catch(reason){options.notify(errorText(reason),'error');}};
 const saveSizes=async()=>{try{await Promise.all(definitions.map(item=>options.request(engine.route(`/api/manage/${domain}/qualityDefinitions/${item.id}`),{method:'PUT',body:JSON.stringify(item)})));options.notify(`${domain==='movie'?'Movie':'Television'} engine quality size limits updated.`);options.onDirtyChange(false);await load();}catch(reason){options.notify(errorText(reason),'error');}};
 const updateSize=(index:number,field:'minSize'|'preferredSize'|'maxSize',value:string)=>{setDefinitions(items=>items.map((item,i)=>i===index?{...item,[field]:value===''?null:Number(value)}:item));options.onDirtyChange(true);};
 const cutoffIndex=selected?.items.findIndex(item=>key(item)===selected.cutoff||(item.items||[]).some(child=>key(child)===selected.cutoff))??-1;
 const allowedAbove=Boolean(selected&&cutoffIndex>=0&&selected.items.some((item,index)=>index>cutoffIndex&&(item.allowed||(item.items||[]).some(child=>child.allowed))));
 return <div className="quality-profiles-route">
  <div className="hero"><div><span className="eyebrow">SERVICE SETTINGS</span><h1>Quality Profiles</h1><p className="lede">Control acceptable qualities, upgrades, cutoffs, custom-format scores, and file-size limits.</p></div><div className="form-actions"><a className="secondary button-link" href="#service/guide-templates/qualityProfile,qualitySize">Browse TRaSH templates</a><button className="primary" onClick={()=>void create()}>New profile</button></div></div>
  <ServiceTabs active="profiles"/>
  <div className="management-toolbar"><label>Library<select value={domain} onChange={event=>setDomain(event.target.value as EngineDomain)}><option value="movie">Movies</option><option value="tv">Television</option></select></label><EngineInstanceSelect instances={engine.instances} value={engine.instanceId} onChange={engine.setInstanceId}/></div>
  {failure?<div className="panel error-state"><p>{failure}</p><button className="secondary" onClick={()=>void load()}>Try again</button></div>:<div className="profile-layout">
   <section className={`panel profile-list${loading?' skeleton':''}`}>{loading?'Loading…':profiles.map(profile=><button className="profile-item" key={profile.id} onClick={()=>choose(profile)}><strong>{profile.name}</strong><small>{profile.items.filter(item=>item.allowed).length} qualities · {profile.upgradeAllowed?'Upgrades enabled':'No upgrades'}</small></button>)}</section>
   <section className="panel profile-editor">{!selected?<div className="empty"><h2>Select a profile</h2><p>Choose a profile to edit its quality rules.</p></div>:<form onSubmit={event=>void save(event)}>
    <div className="panel-heading"><h2>{isNew?'New profile':`Edit ${selected.name}`}</h2>{!isNew?<button className="danger" type="button" onClick={()=>void remove()}>Delete</button>:null}</div>
    <label>Profile name<input required value={selected.name} onChange={event=>change(p=>{p.name=event.target.value;})}/></label>
    <label className="check upgrade-toggle"><input type="checkbox" checked={selected.upgradeAllowed} onChange={event=>change(p=>{p.upgradeAllowed=event.target.checked;})}/> Upgrade until the cutoff is met</label>
    <label className={!selected.upgradeAllowed?'disabled cutoff-field':'cutoff-field'}>Upgrade cutoff<select disabled={!selected.upgradeAllowed} value={selected.cutoff} onChange={event=>change(p=>{p.cutoff=Number(event.target.value);})}>{selected.items.map(item=><option key={key(item)} value={key(item)}>{item.name||item.quality?.name}</option>)}</select></label>
    <h3>Allowed qualities</h3><p className="muted">Enable the qualities this profile may download. Groups keep equivalent sources together.</p>
    {allowedAbove?<div className="notice quality-cutoff-warning"><strong>Allowed qualities exceed this cutoff</strong><p>The cutoff stops upgrades; it is not a maximum. Disable higher qualities if the engine should never download them.</p></div>:null}
    <div className="quality-list">{selected.items.map((item,index)=><div className="quality-option" key={`${key(item)}-${index}`}><label className="check"><input type="checkbox" checked={item.allowed} onChange={event=>change(p=>{p.items[index].allowed=event.target.checked;})}/><strong>{item.name||item.quality?.name}</strong>{item.quality?.resolution?<small> {item.quality.resolution}p</small>:null}</label>{item.items?.length?<div className="quality-children">{item.items.map((child,childIndex)=><label className="check" key={`${key(child)}-${childIndex}`}><input type="checkbox" checked={child.allowed} onChange={event=>change(p=>{p.items[index].items![childIndex].allowed=event.target.checked;})}/>{child.quality?.name||child.name}</label>)}</div>:null}</div>)}</div>
    <h3>Custom format scores</h3><div className="score-grid">{formats.map(format=><label key={format.id}>{format.name}<input type="number" value={selected.formatItems?.find(item=>item.format===format.id)?.score||0} onChange={event=>change(p=>{p.formatItems=p.formatItems||[];const found=p.formatItems.find(item=>item.format===format.id);if(found)found.score=Number(event.target.value)||0;else p.formatItems.push({format:format.id,score:Number(event.target.value)||0});})}/></label>)}</div>
    <div className="form-grid three">{([['minFormatScore','Minimum format score'],['cutoffFormatScore','Upgrade cutoff score'],['minUpgradeFormatScore','Minimum upgrade score']] as const).map(([field,label])=><label key={field}>{label}<input type="number" value={selected[field]??(field==='minUpgradeFormatScore'?1:0)} onChange={event=>change(p=>{p[field]=Number(event.target.value)||0;})}/></label>)}</div>
    <div className="form-actions"><button className="primary" type="submit">Save profile</button></div>
   </form>}</section>
  </div>}
  <details className="panel quality-size-panel"><summary><div><h2>Quality size limits</h2><p className="muted">Adjust engine-native MB/min limits.</p></div></summary><div className="quality-size-list">{definitions.map((definition,index)=><div className="quality-size-row" key={definition.id}><strong>{definition.title||definition.quality?.name||definition.name}</strong><div className="quality-number-fields">{(['minSize','preferredSize','maxSize'] as const).map(field=><label key={field}>{field==='minSize'?'Min':field==='preferredSize'?'Preferred':'Max'}<input type="number" min={limits.min} max={limits.max} step=".1" value={definition[field]??''} onChange={event=>updateSize(index,field,event.target.value)}/></label>)}</div></div>)}</div><div className="form-actions"><button className="primary" type="button" onClick={()=>void saveSizes()}>Save limits to engine</button></div></details>
 </div>;
}
