export interface ReeltrackListItem {
  mediaId?:number|string;
  title:string;
  type:string;
  year?:number|null;
  source:string;
  externalId:string;
  tmdbId?:number|null;
  posterUrl?:string|null;
  overview?:string|null;
  rank?:number|null;
  domain:'movie'|'tv';
  library?:{id:string|number;title:string;status:'available'|'pending';canView:boolean}|null;
  canRequest:boolean;
  requestBlockReason?:string|null;
}
export interface ReeltrackList {
  id:string|number;
  name:string;
  description?:string|null;
  kind?:string;
  items?:ReeltrackListItem[];
  imported?:boolean;
  automation?:{
    enabled:boolean;
    plexLibraryKey?:string;
    plexMovieLibraryKey?:string;
    plexTvLibraryKey?:string;
    splitLibraryMode?:boolean;
    plexMoviePlaceholderLibraryKey?:string;
    plexTvPlaceholderLibraryKey?:string;
    moviePlaceholderHostRoot?:string;
    tvPlaceholderHostRoot?:string;
    movieMediaDestinationId?:string;
    tvMediaDestinationId?:string;
    plexTrailerPath?:string;
    plexLibraryLocations?:{movie?:string;tv?:string};
    movieHostRoot?:string;
    tvHostRoot?:string;
    collectionName?:string;
    collectionPosterTemplate?:import("./poster-overlays-types").OverlayTemplate|null;
    titleOverlayTemplate?:import("./poster-overlays-types").OverlayTemplate|null;
    realTitleOverlayTemplate?:import("./poster-overlays-types").OverlayTemplate|null;
    intervalMinutes?:number;
    status?:'scheduled'|'ready'|'error'|'disabled';
    error?:string|null;
    libraryErrors?:string[];
    lastRunAt?:string|null;
    nextRunAt?:string|null;
    summary?:{providerTitles:number;managedTitles:number;placeholders:number;downloaded:number;removed:number;failed?:number;realMatches:number;libraryAdded?:number;libraryExisting?:number;libraryFailed?:number;collectionPosters?:number;collectionPosterFailures?:number;collectionPosterErrors?:string[];titlePosters?:number;titlePosterFailures?:number;titlePosterErrors?:string[]};
  }|null;
}
export interface ReeltrackListsMountOptions {
  request:<T=unknown>(path:string,options?:RequestInit)=>Promise<T>;
  notify:(message:string,tone?:string)=>void;
  administrator:boolean;
  initialSection?:'titles'|'automation';
}
