import {useMemo,useState} from 'react';
import './react-rename-preview.css';

export interface RenameFilePreview {id?:number;existingPath?:string;newPath?:string;outsideLibraryFolder?:boolean;renameAfterFolderMove?:boolean;size?:number;quality?:string;languages?:string[];videoCodec?:string;audioCodec?:string;resolution?:string;dateAdded?:string;seasonNumber?:number;episodeNumbers?:number[]}
export interface RenamePreviewRecord {previewId?:string;expiresAt?:string;domain:'movie'|'tv';mediaId:number;title?:string;currentPath?:string;destinationPath?:string;rootFolderPath?:string;folderChange?:boolean;refreshStatus?:string;files?:RenameFilePreview[]}
export interface RenameSelection {moveFolder:boolean;fileIds:number[]}
export interface RenamePreviewProps {preview:RenamePreviewRecord;busy?:boolean;onClose:()=>void;onApply:(selection:RenameSelection)=>Promise<unknown>|unknown;onDelete?:(file:RenameFilePreview)=>Promise<unknown>|unknown}
const path=(value?:string)=>String(value||'Not reported').replaceAll('\\','/');
const filename=(value?:string)=>path(value).split('/').filter(Boolean).at(-1)||'Unknown file';
const size=(value?:number)=>value?`${(value/1073741824).toFixed(value>=1073741824?2:3)} GB`:'Size unavailable';

export function RenamePreview({preview,busy=false,onClose,onApply,onDelete}:RenamePreviewProps){
  const files=preview.files||[],fileChanges=files.filter(file=>file.renameAfterFolderMove||path(file.existingPath)!==path(file.newPath)),changeCount=fileChanges.length+Number(Boolean(preview.folderChange));
  const initialIds=useMemo(()=>fileChanges.filter(file=>!file.outsideLibraryFolder).map(file=>Number(file.id)).filter(Number.isFinite),[preview.previewId]);
  const [selected,setSelected]=useState<Set<number>>(()=>new Set(initialIds));
  const [deleting,setDeleting]=useState<number>();
  const [moveFolder,setMoveFolder]=useState(Boolean(preview.folderChange));
  const toggle=(id:number)=>setSelected(current=>{const next=new Set(current);next.has(id)?next.delete(id):next.add(id);return next;});
  const remove=async(file:RenameFilePreview)=>{const id=Number(file.id);if(!Number.isFinite(id)||!onDelete||!window.confirm(`Permanently delete ${filename(file.existingPath)} from disk?\n\nThis cannot be undone.`))return;setDeleting(id);try{await onDelete(file);setSelected(current=>{const next=new Set(current);next.delete(id);return next;});}finally{setDeleting(undefined);}};
  const selectedChanges=fileChanges.filter(file=>selected.has(Number(file.id))).length,totalSelected=selectedChanges+Number(moveFolder&&preview.folderChange);
  return <dialog open className="vynode-rename-dialog" aria-label={`Rename preview for ${preview.title||'media'}`}>
    <div className="rename-preview-heading"><div><span className="eyebrow">RENAME PREVIEW</span><h2>{preview.title||'Media organization'}</h2><p>{changeCount?`${changeCount} proposed ${changeCount===1?'change':'changes'}`:'Everything already matches the naming configuration'}</p></div><button className="secondary" disabled={busy} onClick={onClose}>Close</button></div>
    <section className={`rename-folder-preview ${preview.folderChange?'changed':'unchanged'}`}><label className="rename-choice"><input type="checkbox" disabled={!preview.folderChange||busy} checked={moveFolder&&Boolean(preview.folderChange)} onChange={event=>setMoveFolder(event.target.checked)}/><span>{preview.folderChange?'Rename folder':'Folder already matches'}</span></label><div><span>Current library folder</span><strong>{path(preview.currentPath)}</strong></div><i aria-hidden="true">→</i><div><span>{preview.folderChange?'Proposed library folder':'Library folder'}</span><strong>{path(preview.destinationPath)}</strong></div></section>
    <div className="rename-preview-summary"><span className={`badge ${changeCount?'amber':'green'}`}>{changeCount?`${changeCount} changes`:'Already organized'}</span><p>{preview.refreshStatus==='completed'?'File associations were refreshed before this preview. ':preview.refreshStatus==='timed-out'?'The engine refresh is still running; verify the paths before applying changes. ':preview.refreshStatus==='unavailable'?'The engine could not refresh file associations; verify the paths before applying changes. ':''}Select only the folder and files you want changed. VynodeArr uses the naming rules configured in the {preview.domain==='movie'?'movie':'television'} engine.</p></div>
    <section className="rename-file-section"><div className="panel-heading"><div><span className="eyebrow">FILES</span><h3>{fileChanges.length?`${fileChanges.length} files can be renamed`:'No file renames required'}</h3></div><span>{files.length} evaluated</span></div>
      {fileChanges.length?<><div className="rename-file-tools"><label className="check"><input type="checkbox" checked={selectedChanges===fileChanges.length} ref={node=>{if(node)node.indeterminate=selectedChanges>0&&selectedChanges<fileChanges.length;}} onChange={event=>setSelected(new Set(event.target.checked?initialIds:[]))}/> Select all files</label><span>{selectedChanges} of {fileChanges.length} selected</span></div><div className="rename-file-list">{fileChanges.map((file,index)=>{const id=Number(file.id),details=[file.quality,file.resolution,file.videoCodec,file.audioCodec,file.languages?.join(', '),size(file.size)].filter(Boolean);return <article key={`${file.id??index}:${file.existingPath}`} className={selected.has(id)?'selected':''}><label className="rename-choice"><input type="checkbox" disabled={busy||!Number.isFinite(id)} checked={selected.has(id)} onChange={()=>toggle(id)}/><span>{preview.domain==='tv'?'Rename episode file':'Rename file'}</span></label><div><small>Current file</small><strong title={filename(file.existingPath)}>{filename(file.existingPath)}</strong><code title={path(file.existingPath)}>{path(file.existingPath)}</code><p className="file-metadata">{details.join(' · ')}</p>{file.dateAdded?<p className="file-metadata">Added {new Date(file.dateAdded).toLocaleString()}</p>:null}</div><i aria-hidden="true">→</i><div><small>{file.renameAfterFolderMove?'Rename after folder move':'Proposed file name'}</small>{file.renameAfterFolderMove?<><strong>Recalculate using the active movie naming format</strong><code>The media engine will rename this file immediately after moving the folder.</code></>:<><strong title={filename(file.newPath)}>{filename(file.newPath)}</strong><code title={path(file.newPath)}>{path(file.newPath)}</code></>}</div>{onDelete?<button className="danger rename-delete" disabled={busy||deleting===id} onClick={()=>void remove(file)}>{deleting===id?'Deleting…':'Delete file'}</button>:null}</article>;})}</div></>:<div className="empty compact"><p>The current file names already match the configured format.</p></div>}
    </section>
    <footer className="rename-preview-actions"><span>{totalSelected} selected change{totalSelected===1?'':'s'}</span><button className="secondary" disabled={busy} onClick={onClose}>Cancel</button><button className="primary" disabled={busy||!totalSelected} onClick={()=>void onApply({moveFolder,fileIds:Array.from(selected)})}>{busy?'Applying changes…':totalSelected?'Apply selected changes':'Select changes'}</button></footer>
  </dialog>;
}
