import {useCallback,useEffect,useState} from 'react';
import type {Directory,DownloadFolders,RootFolder,RootFoldersMountOptions,StorageDomain} from './root-folders-types';

const clean=(value:string)=>value==='/'?'/':value.replace(/\/+$/,'')||'/';
const parent=(value:string)=>clean(value).split('/').slice(0,-1).join('/')||'/';
const size=(bytes=0)=>{const gb=bytes/1073741824;return gb>=1024?`${(gb/1024).toFixed(gb>=10240?0:1)} TB`:`${Math.round(gb)} GB`;};
const message=(reason:unknown)=>reason instanceof Error?reason.message:'Storage settings are unavailable.';
const Tabs=()=> <nav className="settings-tabs"><a className="active" href="#service/root-folders">Root Folders</a><a href="#service/media-management">Media Management</a><a href="#service/profiles">Quality Profiles</a><a href="#service/custom-formats">Custom Formats</a><a href="#service/release-profiles">Release Profiles</a><a href="#service/indexers">Indexers</a><a href="#service/download-clients">Download Clients</a><a href="#service/discover">Discover</a><a href="#management">Advanced</a></nav>;

export function RootFoldersView({options}:{options:RootFoldersMountOptions}){
  const [domain,setDomain]=useState<StorageDomain>('movie'),[roots,setRoots]=useState<RootFolder[]>([]),[downloads,setDownloads]=useState<DownloadFolders>({}),[rootPath,setRootPath]=useState('/movies'),[downloadPath,setDownloadPath]=useState('/downloads'),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[error,setError]=useState(''),[browser,setBrowser]=useState<null|'root'|'download'>(null),[current,setCurrent]=useState('/'),[directories,setDirectories]=useState<Directory[]>([]),[browseError,setBrowseError]=useState('');
  const load=useCallback(async()=>{setLoading(true);setError('');try{const [rootValue,downloadValue]=await Promise.all([options.request<{result:RootFolder[]}>(`/api/manage/${domain}/rootFolders`),options.request<DownloadFolders>('/api/settings/download-folders')]);setRoots(rootValue.result||[]);setDownloads(downloadValue||{});setDownloadPath(clean(downloadValue?.[domain]?.path||'/downloads'));}catch(reason){setError(message(reason));}finally{setLoading(false);}},[domain,options]);
  useEffect(()=>{setRootPath(domain==='movie'?'/movies':'/tv');void load();},[domain,load]);
  const openBrowser=(target:'root'|'download')=>{const start=target==='root'?rootPath:downloadPath;setBrowser(target);setCurrent(clean(start));};
  useEffect(()=>{if(!browser)return;setBrowseError('');setDirectories([]);void options.request<{result:{directories?:Directory[]}}>(`/api/manage/${domain}/filesystem?path=${encodeURIComponent(current)}&includeFiles=false&allowFoldersWithoutTrailingSlashes=true`).then(value=>setDirectories(value.result?.directories||[])).catch(reason=>setBrowseError(message(reason)));},[browser,current,domain,options]);
  const saveDownload=async()=>{setBusy('download');try{await options.request('/api/settings/download-folders',{method:'PUT',body:JSON.stringify({domain,path:downloadPath})});setDownloads(value=>({...value,[domain]:{path:downloadPath}}));options.notify(`${domain==='movie'?'Movie':'Television'} download folder saved.`);}catch(reason){options.notify(message(reason),'error');}finally{setBusy('');}};
  const addRoot=async()=>{setBusy('root');try{await options.request(`/api/manage/${domain}/rootFolders`,{method:'POST',body:JSON.stringify({path:rootPath})});options.notify('Library folder added.');await load();}catch(reason){options.notify(message(reason),'error');}finally{setBusy('');}};
  const remove=async(root:RootFolder)=>{if(!confirm(`Remove ${root.path} as a library folder? Media files will not be deleted.`))return;setBusy(String(root.id));try{await options.request(`/api/manage/${domain}/rootFolders/${root.id}`,{method:'DELETE'});options.notify('Library folder removed.');await load();}catch(reason){options.notify(message(reason),'error');}finally{setBusy('');}};
  const samePath=clean(rootPath)===clean(downloadPath);
  return <div className="root-folders-react-route"><div className="hero storage-hero"><div><span className="eyebrow">SERVICE SETTINGS</span><h1>Storage Folders</h1><p className="lede">Separate completed downloads from the permanent, organized media library.</p></div></div><Tabs/>
    <section className="storage-engine-bar"><div><span className="eyebrow">CONFIGURING</span><strong>{domain==='movie'?'Movies':'Television'} storage</strong></div><label>Media engine<select value={domain} onChange={event=>setDomain(event.target.value as StorageDomain)}><option value="movie">Movies</option><option value="tv">Television</option></select></label></section>
    {samePath?<div className="notice storage-warning"><strong>Download and library paths match</strong><p>Choose separate paths so completed downloads remain isolated until the engine imports and organizes them.</p></div>:null}
    {error?<div className="panel error-state"><h2>Storage settings unavailable</h2><p>{error}</p><button className="secondary" onClick={()=>void load()}>Try again</button></div>:<div className="storage-config-grid">
      <section className="panel storage-folder-card"><div className="storage-card-heading"><span className="storage-card-icon">↓</span><div><span className="eyebrow">INCOMING MEDIA</span><h2>Download folder</h2><p>The completed-download staging folder this engine reads before import.</p></div><span className="badge green">{downloads[domain]?.path?'Configured':'Required'}</span></div><div className="storage-path-control"><label>Current folder<input readOnly value={downloadPath}/></label><button className="secondary" onClick={()=>openBrowser('download')}>Choose folder</button></div><div className="storage-card-footer"><small>VynodeArr maintains the engine path mapping automatically.</small><button className="primary" disabled={busy==='download'||samePath} onClick={()=>void saveDownload()}>{busy==='download'?'Saving…':'Save download folder'}</button></div></section>
      <section className="panel storage-folder-card"><div className="storage-card-heading"><span className="storage-card-icon">▰</span><div><span className="eyebrow">ORGANIZED MEDIA</span><h2>Library folders</h2><p>Permanent destinations for renamed and organized {domain==='movie'?'movies':'series'}.</p></div><span className="badge">{roots.length}</span></div><div className="storage-add-form"><div className="storage-path-control"><label>New library folder<input readOnly value={rootPath}/></label><button className="secondary" onClick={()=>openBrowser('root')}>Choose folder</button></div><button className="primary" disabled={busy==='root'||samePath} onClick={()=>void addRoot()}>{busy==='root'?'Adding…':'Add library folder'}</button></div><div className="storage-root-list">{loading?<div className="skeleton">Loading folders…</div>:roots.length?roots.map(root=><article className="storage-path-row" key={root.id}><span className={`storage-path-state ${root.accessible?'available':'unavailable'}`}/><div className="storage-path-copy"><strong>{root.path}</strong><small>{root.accessible?'Accessible':'Not accessible'} · {size(root.freeSpace)} free</small>{root.unmappedFolders?.length?<small>{root.unmappedFolders.length} unimported folder{root.unmappedFolders.length===1?'':'s'} ready to review</small>:<small>Library is fully reviewed</small>}</div><div className="storage-path-actions">{root.accessible?<button className="secondary" onClick={()=>options.onScan(domain,root)}>Scan library</button>:null}<button className="text-button" disabled={busy===String(root.id)} onClick={()=>void remove(root)}>Remove</button></div></article>):<div className="empty compact"><h3>No library folders yet</h3><p>Choose a folder above to create the first organized destination.</p></div>}</div></section>
    </div>}
    {browser?<div className="root-folder-browser-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)setBrowser(null);}}><section className="panel root-folder-browser" role="dialog" aria-modal="true" aria-label="Choose a folder"><div className="panel-heading"><div><span className="eyebrow">CHOOSE A FOLDER</span><h2>{current}</h2><p className="muted">Only folders visible to the selected engine are shown.</p></div><button className="secondary" onClick={()=>setBrowser(null)}>Cancel</button></div><div className="folder-browser-actions"><button className="secondary" disabled={current==='/'} onClick={()=>setCurrent(parent(current))}>← Parent</button><button className="primary" onClick={()=>{browser==='root'?setRootPath(current):setDownloadPath(current);setBrowser(null);}}>Use this folder</button></div><div className="folder-browser-list">{browseError?<div className="empty error-state"><p>{browseError}</p></div>:directories.length?directories.map(folder=><button className="folder-row" key={folder.path} onClick={()=>setCurrent(clean(folder.path))}><span className="folder-icon">▰</span><span>{folder.name}</span><small>{folder.path}</small></button>):<div className="empty compact"><p>No subfolders here. You can still use this folder.</p></div>}</div></section></div>:null}
  </div>;
}
