import { useEffect,useMemo,useState } from 'react';
import { createPortal } from 'react-dom';
import type { ApiRecord,CustomFormat,CustomFormatSpecification,NativeField,QualityProfile,ReleaseProfile,SelectionDomain,SelectionRulesMountOptions,SelectionSection } from './selection-rules-types';
import {addCustomFormatsToken,customFormatsToken,namingHasCustomFormatsToken,type NamingSettings} from './custom-format-naming';
import {ServiceTabs,type ServiceSection} from './service-tabs';
import './react-selection-rules.css';

const list=(value:unknown)=>Array.isArray(value)?value.map(String):String(value||'').split(',').map(item=>item.trim()).filter(Boolean);
const numbers=(value:unknown)=>Array.isArray(value)?value.map(Number).filter(Number.isFinite):[];
const errorMessage=(reason:unknown)=>reason instanceof Error?reason.message:'The engine settings could not be updated.';
const releaseResource=(_domain:SelectionDomain)=>'releaseProfiles';
const clone=<T,>(value:T):T=>structuredClone(value);
const labelFor=(value:ApiRecord)=>String(value.label||value.name||value.implementationName||value.implementation||'Condition');
const fieldOptions=(field:NativeField)=>{
  const source=field.selectOptions||field.options;
  return Array.isArray(source)?source as Array<{value:unknown;name?:string;label?:string}>:[];
};
const createCondition=(schema:ApiRecord):CustomFormatSpecification=>{
  const condition=clone(schema) as CustomFormatSpecification;
  delete condition.id;
  condition.name=labelFor(schema);
  condition.negate=Boolean(condition.negate);
  condition.required=Boolean(condition.required);
  condition.fields=Array.isArray(condition.fields)?condition.fields.map(field=>clone(field)):[];
  return condition;
};

function NativeFieldInput({field,onChange}:{field:NativeField;onChange:(value:unknown)=>void}){
  const options=fieldOptions(field),type=String(field.type||'').toLowerCase(),value=field.value??'';
  if(options.length)return <select value={String(value)} onChange={event=>{const option=options.find(item=>String(item.value)===event.target.value);onChange(option?.value??event.target.value);}}>{options.map((option,index)=><option key={`${String(option.value)}-${index}`} value={String(option.value)}>{option.name||option.label||String(option.value)}</option>)}</select>;
  if(type.includes('bool')||typeof value==='boolean')return <input type="checkbox" checked={Boolean(value)} onChange={event=>onChange(event.target.checked)}/>;
  if(Array.isArray(value))return <input value={value.join(', ')} onChange={event=>onChange(list(event.target.value))}/>;
  if(type.includes('int')||type.includes('number')||typeof value==='number')return <input type="number" value={Number(value)} onChange={event=>onChange(event.target.value===''?'':Number(event.target.value))}/>;
  return <input value={String(value)} onChange={event=>onChange(event.target.value)}/>;
}

export function SelectionRulesView({options}:{options:SelectionRulesMountOptions}){
  const [domain,setDomain]=useState<SelectionDomain>('movie'),[section,setSection]=useState<SelectionSection>(options.section),[profiles,setProfiles]=useState<QualityProfile[]>([]),[formats,setFormats]=useState<CustomFormat[]>([]),[releases,setReleases]=useState<ReleaseProfile[]>([]),[schemas,setSchemas]=useState<ApiRecord[]>([]),[tags,setTags]=useState<ApiRecord[]>([]),[indexers,setIndexers]=useState<ApiRecord[]>([]),[naming,setNaming]=useState<NamingSettings>({}),[loading,setLoading]=useState(true),[busy,setBusy]=useState(''),[loadError,setLoadError]=useState(''),[editingFormat,setEditingFormat]=useState<number|null>(null),[editingRelease,setEditingRelease]=useState<number|null>(null);
  const formatNames=useMemo(()=>new Map(formats.map(format=>[Number(format.id),format.name||`Format ${format.id}`])),[formats]);
  const load=async()=>{setLoading(true);setLoadError('');try{
    if(section==='custom-formats'){
      const [profileValue,formatValue,schemaValue,namingValue]=await Promise.all([
        options.request<{result:QualityProfile[]}>(`/api/manage/${domain}/profiles`),
        options.request<{result:CustomFormat[]}>(`/api/manage/${domain}/customFormats`),
        options.request<{result:ApiRecord[]}>(`/api/manage/${domain}/customFormatSchemas`),
        options.request<{result:NamingSettings}>(`/api/manage/${domain}/naming`)
      ]);
      setProfiles(profileValue.result||[]);setFormats(formatValue.result||[]);setSchemas(schemaValue.result||[]);setNaming(namingValue.result||{});
    }else{
      const releaseValue=await options.request<{result:ReleaseProfile[]}>(`/api/manage/${domain}/${releaseResource(domain)}`);
      const [tagValue,indexerValue]=await Promise.all([
        options.request<{result:ApiRecord[]}>(`/api/manage/${domain}/tags`).catch(()=>({result:[]})),
        options.request<{result:ApiRecord[]}>(`/api/manage/${domain}/indexers`).catch(()=>({result:[]}))
      ]);
      setReleases(releaseValue.result||[]);setTags(tagValue.result||[]);setIndexers(indexerValue.result||[]);
    }
  }catch(reason){setLoadError(errorMessage(reason));}finally{setLoading(false);}};
  useEffect(()=>{setEditingFormat(null);setEditingRelease(null);void load();},[domain,section]);
  const updateFormat=(index:number,change:(format:CustomFormat)=>CustomFormat)=>setFormats(current=>current.map((format,i)=>i===index?change(format):format));
  const saveFormat=async(format:CustomFormat,isNew=false)=>{setBusy(`format-${format.id||'new'}`);try{await options.request(`/api/manage/${domain}/customFormats${isNew?'':`/${format.id}`}`,{method:isNew?'POST':'PUT',body:JSON.stringify(format)});options.notify('Custom format saved to the engine.');setEditingFormat(null);await load();}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const ensureNamingToken=async()=>{if(!window.confirm(`Add ${customFormatsToken} to the active ${domain==='movie'?'movie':'TV episode'} filename formats?`))return;setBusy('naming-token');try{const updated=addCustomFormatsToken(domain,naming);await options.request(`/api/manage/${domain}/naming`,{method:'PUT',body:JSON.stringify(updated)});setNaming(updated);options.notify(`${customFormatsToken} added to ${domain==='movie'?'movie':'TV episode'} naming formats.`);}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const removeFormat=async(format:CustomFormat,index:number)=>{if(!format.id){setFormats(current=>current.filter((_,i)=>i!==index));return;}if(!confirm(`Delete ${format.name}?`))return;try{await options.request(`/api/manage/${domain}/customFormats/${format.id}`,{method:'DELETE'});options.notify('Custom format deleted.');await load();}catch(reason){options.notify(errorMessage(reason),'error');}};
  const saveProfile=async(profile:QualityProfile)=>{setBusy(`profile-${profile.id}`);try{await options.request(`/api/manage/${domain}/profiles/${profile.id}`,{method:'PUT',body:JSON.stringify(profile)});options.notify(`${profile.name} scores saved to the engine.`);await load();}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const score=(profile:QualityProfile,formatId:number)=>profile.formatItems?.find(item=>Number(item.format)===formatId)?.score||0;
  const setScore=(profileId:number,formatId:number,value:number)=>setProfiles(current=>current.map(profile=>{if(profile.id!==profileId)return profile;const items=[...(profile.formatItems||[])],index=items.findIndex(item=>Number(item.format)===formatId);if(index>=0)items[index]={...items[index],score:value};else items.push({format:formatId,name:formatNames.get(formatId),score:value});return{...profile,formatItems:items};}));
  const updateRelease=(index:number,change:Partial<ReleaseProfile>)=>setReleases(current=>current.map((profile,i)=>i===index?{...profile,...change}:profile));
  const saveRelease=async(profile:ReleaseProfile,isNew=false)=>{setBusy(`release-${profile.id||'new'}`);try{await options.request(`/api/manage/${domain}/${releaseResource(domain)}${isNew?'':`/${profile.id}`}`,{method:isNew?'POST':'PUT',body:JSON.stringify(profile)});options.notify('Release profile saved to the engine.');setEditingRelease(null);await load();}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const removeRelease=async(profile:ReleaseProfile,index:number)=>{if(!profile.id){setReleases(current=>current.filter((_,i)=>i!==index));return;}if(!confirm(`Delete ${profile.name}?`))return;try{await options.request(`/api/manage/${domain}/${releaseResource(domain)}/${profile.id}`,{method:'DELETE'});options.notify('Release profile deleted.');await load();}catch(reason){options.notify(errorMessage(reason),'error');}};
  const closeRelease=(profile:ReleaseProfile,index:number)=>{if(!profile.id)setReleases(current=>current.filter((_,i)=>i!==index));setEditingRelease(null);};
  const closeFormat=(format:CustomFormat,index:number)=>{if(!format.id)setFormats(current=>current.filter((_,i)=>i!==index));setEditingFormat(null);};
  const toggleId=(values:number[]|undefined,id:number)=>values?.includes(id)?values.filter(value=>value!==id):[...(values||[]),id];
  return <div className="selection-rules-route">
    <div className="hero"><div><span className="eyebrow">RELEASE SELECTION</span><h1>Selection rules</h1><p className="lede">Configure the connected engines’ native matching, scoring, and release rules.</p></div></div>
    <ServiceTabs active={section} onNavigate={(next:ServiceSection)=>{if(next==='custom-formats'||next==='release-profiles')setSection(next);}}/>
    <div className="management-toolbar"><label>Library<select value={domain} onChange={event=>setDomain(event.target.value as SelectionDomain)}><option value="movie">Movies</option><option value="tv">Television</option></select></label><div className="selection-rule-explainer"><strong>{section==='custom-formats'?'Native scored matching':'Native release-title rules'}</strong><span>{section==='custom-formats'?`${schemas.length} condition types supplied by the selected engine.`:'Rules are written directly to the selected engine.'}</span></div></div>
    {loading?<div className="panel skeleton">Loading engine rules…</div>:loadError?<div className="panel selection-rule-error"><h2>{section==='custom-formats'?'Custom formats':'Release profiles'} unavailable</h2><p>{loadError}</p><button className="primary" onClick={()=>void load()}>Try again</button></div>:section==='custom-formats'?<div className="selection-rule-stack">
      <section className="panel selection-rule-intro"><div><h2>Custom formats</h2><p>Build formats from the exact condition schemas reported by the connected engine.</p></div><div className="rule-summary-actions"><a className="secondary" href={`#service/guide-templates/${domain==='tv'?'tv:':''}customFormat,customFormatGroup`}>Browse TRaSH templates</a><button className="primary" onClick={()=>{setFormats(current=>[{name:'New custom format',includeCustomFormatWhenRenaming:false,specifications:[]},...current]);setEditingFormat(0);}}>New custom format</button></div></section>
      {formats.length?<div className="rule-summary-grid">{formats.map((format,index)=><article className="rule-summary-card" key={format.id||`summary-${index}`}><div><span className="rule-kind">CUSTOM FORMAT</span><h3>{format.name||'Unnamed format'}</h3><p>{format.specifications?.length||0} native conditions</p></div><div className="rule-summary-actions">{format.includeCustomFormatWhenRenaming?<span className="rule-chip">Used in renaming</span>:null}<button className="secondary" onClick={()=>setEditingFormat(index)}>Edit</button></div></article>)}</div>:null}
      {!formats.length?<div className="empty panel"><h2>No custom formats</h2><p>Create one here or in the connected engine.</p></div>:null}
      {editingFormat!==null&&formats[editingFormat]?createPortal((()=>{const format=formats[editingFormat],formatIndex=editingFormat;return <div className="template-review-backdrop"><form className="template-review panel standard-format-review" role="dialog" aria-modal="true" aria-label={`Edit ${format.name||'custom format'}`} onSubmit={event=>{event.preventDefault();void saveFormat(format,!format.id);}}>
        <header className="template-review-header"><div className="template-review-title"><span className="eyebrow">CUSTOM FORMAT</span><h2>{format.name||'New custom format'}</h2></div><button type="button" className="icon-button" aria-label="Close custom format editor" onClick={()=>closeFormat(format,formatIndex)}>×</button></header>
        <section className="template-customizer standard-format-basics"><label>Name<small>The name shown in Custom Formats and profile scoring.</small><input required value={format.name||''} onChange={event=>updateFormat(formatIndex,item=>({...item,name:event.target.value}))}/></label><label className="check"><input type="checkbox" checked={Boolean(format.includeCustomFormatWhenRenaming)} onChange={event=>updateFormat(formatIndex,item=>({...item,includeCustomFormatWhenRenaming:event.target.checked}))}/><span>Include when renaming<small>Add this custom-format name to renamed files.</small></span></label>{format.includeCustomFormatWhenRenaming&&!namingHasCustomFormatsToken(domain,naming)?<div className="notice warning naming-token-warning"><div><strong>Naming token required</strong><p>Your active {domain==='movie'?'movie':'TV episode'} filename formats do not contain <code>{customFormatsToken}</code>. This custom-format name will not appear in renamed files until the token is added.</p></div><button type="button" className="secondary" disabled={busy==='naming-token'} onClick={()=>void ensureNamingToken()}>{busy==='naming-token'?'Adding…':'Add to naming formats'}</button></div>:null}<div className="customizer-heading"><div><h3>Matching conditions</h3><p className="control-help">Conditions describe how the engine recognizes a release.</p></div>{format.id?<button type="button" className="danger-secondary" onClick={()=>void removeFormat(format,formatIndex)}>Delete format</button>:null}</div>
          <div className="condition-list">{(format.specifications||[]).map((condition,conditionIndex)=><article className="editable-condition standard-editable-condition" key={`${condition.implementation}-${conditionIndex}`}>
            <div className="condition-type"><span>Condition type</span><strong>{condition.implementationName||condition.implementation||'Condition'}</strong></div><label>Name<small>A readable label for this condition.</small><input value={condition.name||''} onChange={event=>updateFormat(formatIndex,item=>{const specifications=clone(item.specifications||[]);specifications[conditionIndex]={...specifications[conditionIndex],name:event.target.value};return{...item,specifications};})}/></label><div className="condition-switches"><label className="check" title="The condition's final result must pass"><input type="checkbox" checked={Boolean(condition.required)} onChange={event=>updateFormat(formatIndex,item=>{const specifications=clone(item.specifications||[]);specifications[conditionIndex]={...specifications[conditionIndex],required:event.target.checked};return{...item,specifications};})}/> Required</label><label className="check" title="Reverse the condition's match result"><input type="checkbox" checked={Boolean(condition.negate)} onChange={event=>updateFormat(formatIndex,item=>{const specifications=clone(item.specifications||[]);specifications[conditionIndex]={...specifications[conditionIndex],negate:event.target.checked};return{...item,specifications};})}/> Negated</label></div><p className="control-help condition-help"><strong>Required:</strong> this rule must pass. <strong>Negated:</strong> reverses the rule. When both are selected, the specified value must be absent.</p><details><summary>Advanced matching values</summary><p className="control-help">Engine-native values such as regular expressions, language IDs, or quality IDs.</p><div className="native-field-grid">{(condition.fields||[]).map((field,fieldIndex)=><label key={`${field.name}-${fieldIndex}`}>{field.label||field.name}{field.helpText?<small>{String(field.helpText)}</small>:null}<NativeFieldInput field={field} onChange={value=>updateFormat(formatIndex,item=>{const specifications=clone(item.specifications||[]),fields=clone(specifications[conditionIndex].fields||[]);fields[fieldIndex]={...fields[fieldIndex],value};specifications[conditionIndex]={...specifications[conditionIndex],fields};return{...item,specifications};})}/></label>)}</div></details><button type="button" className="text-button remove-condition" onClick={()=>updateFormat(formatIndex,item=>({...item,specifications:(item.specifications||[]).filter((_,i)=>i!==conditionIndex)}))}>Remove condition</button>
          </article>)}</div>
          <label className="add-condition">Add native condition<select value="" onChange={event=>{const schema=schemas[Number(event.target.value)];if(schema)updateFormat(formatIndex,item=>({...item,specifications:[...(item.specifications||[]),createCondition(schema)]}));}}><option value="">Choose condition…</option>{schemas.map((schema,index)=><option key={`${schema.implementation}-${index}`} value={index}>{labelFor(schema)}</option>)}</select></label>
        </section>
        <footer className="template-review-footer"><div><strong>Save directly to the {domain==='movie'?'Movie':'TV'} engine</strong><small>The engine remains the source of truth. Media files are not altered.</small></div><button type="button" className="secondary" onClick={()=>closeFormat(format,formatIndex)}>Cancel</button><button className="primary" disabled={busy===`format-${format.id||'new'}`}>{busy===`format-${format.id||'new'}`?'Saving…':'Save custom format'}</button></footer>
      </form></div>})(),document.body):null}
      <section className="panel scoring-panel"><div><h2>Quality profile scores</h2><p>Set each native format’s score and all score thresholds for each quality profile.</p></div>{profiles.map(profile=>{const available=formats.filter(format=>format.id),scored=available.filter(format=>score(profile,Number(format.id))!==0),unscored=available.filter(format=>score(profile,Number(format.id))===0),fields=(items:CustomFormat[])=><div className="format-score-grid">{items.map(format=><label key={format.id}>{format.name}<input type="number" value={score(profile,Number(format.id))} onChange={event=>setScore(Number(profile.id),Number(format.id),Number(event.target.value))}/></label>)}</div>;return <form key={profile.id} onSubmit={event=>{event.preventDefault();void saveProfile(profile);}}><header><div className="profile-score-heading"><strong>{profile.name}</strong><small>{scored.length} scored format{scored.length===1?'':'s'} · {available.length} available</small></div><div className="score-thresholds"><label>Minimum custom format score<input type="number" value={profile.minFormatScore||0} onChange={event=>setProfiles(current=>current.map(item=>item.id===profile.id?{...item,minFormatScore:Number(event.target.value)}:item))}/></label><label>Upgrade until custom format score<input type="number" value={profile.cutoffFormatScore||0} onChange={event=>setProfiles(current=>current.map(item=>item.id===profile.id?{...item,cutoffFormatScore:Number(event.target.value)}:item))}/></label><label>Minimum custom format score increment<input type="number" value={profile.minUpgradeFormatScore||0} onChange={event=>setProfiles(current=>current.map(item=>item.id===profile.id?{...item,minUpgradeFormatScore:Number(event.target.value)}:item))}/></label></div></header>{scored.length?<section className="format-score-section"><h3>Configured scores</h3>{fields(scored)}</section>:<p className="format-score-empty">No custom-format scores are configured for this profile.</p>}{unscored.length?<details className="unscored-formats"><summary>Unscored formats <span>{unscored.length}</span></summary><p>These formats are available but currently have no effect on this profile.</p>{fields(unscored)}</details>:null}<button className="secondary" disabled={busy===`profile-${profile.id}`}>{busy===`profile-${profile.id}`?'Saving…':'Save quality profile scores'}</button></form>})}</section>
    </div>:<div className="selection-rule-stack">
      <section className="panel selection-rule-intro"><div><h2>Release profiles</h2><p>{domain==='movie'?'Movie restriction fields':'Television release-profile fields'} are preserved and saved natively.</p></div><button className="primary" onClick={()=>{setReleases(current=>[{name:'New release profile',enabled:true,required:[],ignored:[],indexerId:0,tags:[],excludedTags:[],...(domain==='tv'?{preferred:[],includePreferredWhenRenaming:false,airDateRestriction:'always',airDateGracePeriod:0,allowSeasonPackWithoutAllEpisodesAired:false}:{})},...current]);setEditingRelease(0);}}>New release profile</button></section>
      {releases.some(profile=>profile.id)?<div className="rule-summary-grid">{releases.map((profile,index)=>profile.id?<article className="rule-summary-card" key={profile.id}><div><span className="rule-kind">RELEASE PROFILE</span><h3>{profile.name||'Unnamed profile'}</h3><p>{list(profile.required).length} required · {list(profile.ignored).length} blocked · {numbers(profile.tags).length} tags</p></div><div className="rule-summary-actions"><span className={`rule-chip ${profile.enabled===false?'muted':''}`}>{profile.enabled===false?'Disabled':'Enabled'}</span><button className="secondary" onClick={()=>setEditingRelease(index)}>Edit</button></div></article>:null)}</div>:null}
      {!releases.length?<div className="empty panel"><h2>No release profiles</h2><p>Create one here or in the connected engine.</p></div>:releases.map((profile,index)=><form className="panel release-profile-card" key={profile.id||`new-${index}`} onSubmit={event=>{event.preventDefault();void saveRelease(profile,!profile.id);}}>
        <div className="editor-heading"><div className="editor-title"><span className="rule-kind">RELEASE PROFILE EDITOR</span><h2>{profile.name||'New release profile'}</h2></div><button type="button" className="secondary editor-close" onClick={()=>closeRelease(profile,index)}>Close</button><label>Name<input required value={profile.name||''} onChange={event=>updateRelease(index,{name:event.target.value})}/></label><label className="check"><input type="checkbox" checked={profile.enabled!==false} onChange={event=>updateRelease(index,{enabled:event.target.checked})}/> Enabled</label>{profile.id?<button className="danger-secondary" type="button" onClick={()=>void removeRelease(profile,index)}>Delete</button>:<span className="editor-action-spacer" aria-hidden="true"/>}</div>
        <div className="native-field-grid"><label>Must contain<small>One term per line</small><textarea value={list(profile.required).join('\n')} onChange={event=>updateRelease(index,{required:event.target.value.split(/\r?\n/).map(value=>value.trim()).filter(Boolean)})}/></label><label>Must not contain<small>One term per line</small><textarea value={list(profile.ignored).join('\n')} onChange={event=>updateRelease(index,{ignored:event.target.value.split(/\r?\n/).map(value=>value.trim()).filter(Boolean)})}/></label><label>Indexer<select value={profile.indexerId||0} onChange={event=>updateRelease(index,{indexerId:Number(event.target.value)})}><option value={0}>All indexers</option>{indexers.map(indexer=><option key={indexer.id} value={indexer.id}>{indexer.name}</option>)}</select></label></div>
        {domain==='tv'?<section className="preferred-editor"><div className="preferred-heading"><div><strong>Preferred terms</strong><small>The television engine adds these scores when a release title matches.</small></div><label className="check"><input type="checkbox" checked={Boolean(profile.includePreferredWhenRenaming)} onChange={event=>updateRelease(index,{includePreferredWhenRenaming:event.target.checked})}/> Include preferred term when renaming</label><button type="button" className="secondary" onClick={()=>updateRelease(index,{preferred:[...(profile.preferred||[]),{key:'',value:0}]})}>Add preferred term</button></div>{(profile.preferred||[]).map((preferred,preferredIndex)=><div className="preferred-row" key={preferredIndex}><label>Term<input value={preferred.key||''} onChange={event=>updateRelease(index,{preferred:(profile.preferred||[]).map((item,i)=>i===preferredIndex?{...item,key:event.target.value}:item)})}/></label><label>Score<input type="number" value={preferred.value||0} onChange={event=>updateRelease(index,{preferred:(profile.preferred||[]).map((item,i)=>i===preferredIndex?{...item,value:Number(event.target.value)}:item)})}/></label><button type="button" className="text-button" onClick={()=>updateRelease(index,{preferred:(profile.preferred||[]).filter((_,i)=>i!==preferredIndex)})}>Remove</button></div>)}</section>:null}
        <div className="tag-fields"><fieldset><legend>Tags</legend>{tags.length?tags.map(tag=><label className="tag-option" key={tag.id}><input type="checkbox" checked={numbers(profile.tags).includes(Number(tag.id))} onChange={()=>updateRelease(index,{tags:toggleId(numbers(profile.tags),Number(tag.id))})}/><span>{String(tag.label||tag.name)}</span></label>):<p className="field-note">No tags exist in this engine. Create one in the engine, then reload this page.</p>}</fieldset>{domain==='tv'&&('excludedTags' in profile)?<fieldset><legend>Excluded tags</legend>{tags.length?tags.map(tag=><label className="tag-option" key={tag.id}><input type="checkbox" checked={numbers(profile.excludedTags).includes(Number(tag.id))} onChange={()=>updateRelease(index,{excludedTags:toggleId(numbers(profile.excludedTags),Number(tag.id))})}/><span>{String(tag.label||tag.name)}</span></label>):<p className="field-note">No tags are available.</p>}</fieldset>:null}</div>
        {domain==='tv'?<div className="native-field-grid television-release-fields"><label>Apply restriction<select value={profile.airDateRestriction||'always'} onChange={event=>updateRelease(index,{airDateRestriction:event.target.value})}><option value="always">Always</option><option value="afterAirDate">After air date</option><option value="beforeAirDate">Before air date</option></select></label><label>Air-date grace period (hours)<input type="number" min="0" value={profile.airDateGracePeriod||0} onChange={event=>updateRelease(index,{airDateGracePeriod:Number(event.target.value)})}/></label><label className="check"><input type="checkbox" checked={Boolean(profile.allowSeasonPackWithoutAllEpisodesAired)} onChange={event=>updateRelease(index,{allowSeasonPackWithoutAllEpisodesAired:event.target.checked})}/> Allow season pack before all episodes air</label></div>:null}
        <div className="editor-actions"><span>Changes are applied directly to the {domain==='movie'?'movie':'television'} engine.</span><button className="primary" disabled={busy===`release-${profile.id||'new'}`}>{busy===`release-${profile.id||'new'}`?'Saving…':'Save release profile'}</button></div>
      </form>).filter((_,index)=>index===editingRelease)}
    </div>}
  </div>;
}
