import { useEffect,useMemo,useState } from 'react';
import type { ApiRecord,CustomFormat,QualityProfile,ReleaseProfile,SelectionDomain,SelectionRulesMountOptions,SelectionSection } from './selection-rules-types';
import './react-selection-rules.css';

const array=(value:unknown)=>Array.isArray(value)?value.map(String):String(value||'').split(',').map(item=>item.trim()).filter(Boolean);
const errorMessage=(reason:unknown)=>reason instanceof Error?reason.message:'The engine settings could not be updated.';
const resource=(domain:SelectionDomain)=>domain==='movie'?'restrictions':'releaseProfiles';

export function SelectionRulesView({options}:{options:SelectionRulesMountOptions}){
  const [domain,setDomain]=useState<SelectionDomain>('movie'),[section,setSection]=useState<SelectionSection>(options.section),[profiles,setProfiles]=useState<QualityProfile[]>([]),[formats,setFormats]=useState<CustomFormat[]>([]),[releases,setReleases]=useState<ReleaseProfile[]>([]),[schemas,setSchemas]=useState<ApiRecord[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
  const formatNames=useMemo(()=>new Map(formats.map(format=>[Number(format.id),format.name||`Format ${format.id}`])),[formats]);
  const load=async()=>{setLoading(true);try{const [profileValue,formatValue,releaseValue,schemaValue]=await Promise.all([
    options.request<{result:QualityProfile[]}>(`/api/manage/${domain}/profiles`),
    options.request<{result:CustomFormat[]}>(`/api/manage/${domain}/customFormats`),
    options.request<{result:ReleaseProfile[]}>(`/api/manage/${domain}/${resource(domain)}`),
    options.request<{result:ApiRecord[]}>(`/api/manage/${domain}/customFormatSchemas`).catch(()=>({result:[]}))
  ]);setProfiles(profileValue.result||[]);setFormats(formatValue.result||[]);setReleases(releaseValue.result||[]);setSchemas(schemaValue.result||[]);}catch(reason){options.notify(errorMessage(reason),'error');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[domain]);
  const saveProfile=async(profile:QualityProfile)=>{setBusy(`profile-${profile.id}`);try{await options.request(`/api/manage/${domain}/profiles/${profile.id}`,{method:'PUT',body:JSON.stringify(profile)});options.notify(`${profile.name} selection scores saved to the ${domain==='movie'?'movie':'television'} engine.`);await load();}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const score=(profile:QualityProfile,formatId:number)=>profile.formatItems?.find(item=>Number(item.format)===formatId)?.score||0;
  const setScore=(profileId:number,formatId:number,value:number)=>setProfiles(current=>current.map(profile=>{if(profile.id!==profileId)return profile;const items=[...(profile.formatItems||[])],index=items.findIndex(item=>Number(item.format)===formatId);if(index>=0)items[index]={...items[index],score:value};else items.push({format:formatId,name:formatNames.get(formatId),score:value});return{...profile,formatItems:items};}));
  const createEnglishOnly=async()=>{const existing=formats.find(format=>format.name==='Language: Not English');if(existing){options.notify('The non-English custom format already exists.');return;}const language=schemas.find(schema=>String(schema.implementation||'')==='LanguageSpecification');if(!language){options.notify('This engine did not provide its language custom-format schema.','error');return;}const fields=Array.isArray(language.fields)?structuredClone(language.fields) as ApiRecord[]:[],valueField=fields.find(field=>field.name==='value');if(valueField)valueField.value=1;const exceptField=fields.find(field=>field.name==='exceptLanguage');if(exceptField)exceptField.value=false;const specification={...structuredClone(language),name:'Not English language',negate:true,required:false,fields};setBusy('english');try{await options.request(`/api/manage/${domain}/customFormats`,{method:'POST',body:JSON.stringify({name:'Language: Not English',includeCustomFormatWhenRenaming:false,specifications:[specification]})});options.notify('Non-English custom format created. Assign -10000 and keep the profile minimum at 0 to reject matching releases.');await load();}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const removeFormat=async(format:CustomFormat)=>{if(!confirm(`Delete ${format.name}? Remove it from quality profiles first if the engine requires it.`))return;try{await options.request(`/api/manage/${domain}/customFormats/${format.id}`,{method:'DELETE'});options.notify('Custom format deleted.');await load();}catch(reason){options.notify(errorMessage(reason),'error');}};
  const saveRelease=async(profile:ReleaseProfile,isNew=false)=>{setBusy(`release-${profile.id||'new'}`);try{await options.request(`/api/manage/${domain}/${resource(domain)}${isNew?'':`/${profile.id}`}`,{method:isNew?'POST':'PUT',body:JSON.stringify(profile)});options.notify('Release profile saved to the engine.');await load();}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const removeRelease=async(profile:ReleaseProfile)=>{if(!confirm(`Delete ${profile.name}?`))return;try{await options.request(`/api/manage/${domain}/${resource(domain)}/${profile.id}`,{method:'DELETE'});options.notify('Release profile deleted.');await load();}catch(reason){options.notify(errorMessage(reason),'error');}};
  return <div className="selection-rules-route">
    <div className="hero"><div><span className="eyebrow">RELEASE SELECTION</span><h1>Selection rules</h1><p className="lede">Use the engines’ native profiles and matching rules to accept, prefer, or reject releases.</p></div></div>
    <nav className="settings-tabs"><a href="#service/root-folders">Root Folders</a><a href="#service/media-management">Media Management</a><a href="#service/profiles">Quality Profiles</a><a className={section==='custom-formats'?'active':''} href="#service/custom-formats" onClick={()=>setSection('custom-formats')}>Custom Formats</a><a className={section==='release-profiles'?'active':''} href="#service/release-profiles" onClick={()=>setSection('release-profiles')}>Release Profiles</a><a href="#service/indexers">Indexers</a><a href="#service/download-clients">Download Clients</a><a href="#service/discover">Discover</a></nav>
    <div className="management-toolbar"><label>Library<select value={domain} onChange={event=>setDomain(event.target.value as SelectionDomain)}><option value="movie">Movies</option><option value="tv">Television</option></select></label><div className="selection-rule-explainer"><strong>{section==='custom-formats'?'Scored matching':'Hard release-title rules'}</strong><span>{section==='custom-formats'?'A total score below the quality profile minimum is rejected.':'Must contain and must not contain rules are enforced directly by the selected engine.'}</span></div></div>
    {loading?<div className="panel skeleton">Loading engine rules…</div>:section==='custom-formats'?<div className="selection-rule-stack">
      <section className="panel selection-rule-intro"><div><h2>Custom formats</h2><p>Formats describe releases. Quality Profiles decide what each match is worth and the minimum acceptable total.</p></div><button className="primary" disabled={busy==='english'} onClick={()=>void createEnglishOnly()}>{busy==='english'?'Creating…':'Add English-only preset'}</button></section>
      {!formats.length?<div className="empty panel"><h2>No custom formats</h2><p>Create the English-only preset or configure formats in the engine.</p></div>:formats.map(format=><section className="panel custom-format-card" key={format.id}><header><div><h2>{format.name}</h2><p>{format.specifications?.map(spec=>String(spec.name||spec.implementation||'Condition')).join(' · ')||'No conditions reported'}</p></div><button className="text-button" onClick={()=>void removeFormat(format)}>Delete</button></header><div className="format-profile-grid">{profiles.map(profile=><form key={profile.id} onSubmit={event=>{event.preventDefault();void saveProfile(profile);}}><strong>{profile.name}</strong><label>Format score<input type="number" value={score(profile,Number(format.id))} onChange={event=>setScore(Number(profile.id),Number(format.id),Number(event.target.value))}/></label><label>Minimum total<input type="number" value={profile.minFormatScore||0} onChange={event=>setProfiles(current=>current.map(item=>item.id===profile.id?{...item,minFormatScore:Number(event.target.value)}:item))}/></label><button className="secondary" disabled={busy===`profile-${profile.id}`}>{busy===`profile-${profile.id}`?'Saving…':'Save profile'}</button></form>)}</div></section>)}
      <div className="notice"><strong>To block unwanted languages</strong><p>Give “Language: Not English” a score of <code>-10000</code> in every applicable quality profile and leave Minimum Total at <code>0</code>. Automatic grabs below the minimum are rejected; Interactive Search still explains the rejection.</p></div>
    </div>:<div className="selection-rule-stack">
      <section className="panel selection-rule-intro"><div><h2>Release profiles</h2><p>Use comma-separated terms. “Must not contain” is the simplest hard block for release-title markers such as ITA or ITALIAN.</p></div><button className="primary" onClick={()=>setReleases(current=>[{name:'New release profile',enabled:true,required:[],ignored:[],indexerId:0,tags:[],excludedTags:[]},...current])}>New release profile</button></section>
      {releases.map((profile,index)=><form className="panel release-profile-card" key={profile.id||`new-${index}`} onSubmit={event=>{event.preventDefault();void saveRelease(profile,!profile.id);}}><div className="panel-heading"><label>Name<input value={profile.name||''} onChange={event=>setReleases(current=>current.map((item,i)=>i===index?{...item,name:event.target.value}:item))}/></label><label className="check"><input type="checkbox" checked={profile.enabled!==false} onChange={event=>setReleases(current=>current.map((item,i)=>i===index?{...item,enabled:event.target.checked}:item))}/> Enabled</label>{profile.id?<button className="text-button" type="button" onClick={()=>void removeRelease(profile)}>Delete</button>:null}</div><div className="form-grid"><label>Must contain<input value={array(profile.required).join(', ')} placeholder="Required terms" onChange={event=>setReleases(current=>current.map((item,i)=>i===index?{...item,required:array(event.target.value)}:item))}/></label><label>Must not contain<input value={array(profile.ignored).join(', ')} placeholder="ITA, ITALIAN" onChange={event=>setReleases(current=>current.map((item,i)=>i===index?{...item,ignored:array(event.target.value)}:item))}/></label></div><div className="form-actions"><button className="primary" disabled={busy===`release-${profile.id||'new'}`}>{busy===`release-${profile.id||'new'}`?'Saving…':'Save to engine'}</button></div></form>)}
    </div>}
  </div>;
}
