import { useEffect,useMemo,useState } from 'react';
import type { ApiRecord,CustomFormat,CustomFormatSpecification,NativeField,QualityProfile,ReleaseProfile,SelectionDomain,SelectionRulesMountOptions,SelectionSection } from './selection-rules-types';
import './react-selection-rules.css';

const list=(value:unknown)=>Array.isArray(value)?value.map(String):String(value||'').split(',').map(item=>item.trim()).filter(Boolean);
const numbers=(value:unknown)=>Array.isArray(value)?value.map(Number).filter(Number.isFinite):[];
const errorMessage=(reason:unknown)=>reason instanceof Error?reason.message:'The engine settings could not be updated.';
const releaseResource=(domain:SelectionDomain)=>domain==='movie'?'restrictions':'releaseProfiles';
const clone=<T,>(value:T):T=>structuredClone(value);
const labelFor=(value:ApiRecord)=>String(value.label||value.name||value.implementationName||value.implementation||'Condition');
const fieldOptions=(field:NativeField)=>{
  const source=field.selectOptions||field.options;
  return Array.isArray(source)?source as Array<{value:unknown;name?:string;label?:string}>:[];
};
const createCondition=(schema:ApiRecord):CustomFormatSpecification=>{
  const condition=clone(schema) as CustomFormatSpecification;
  delete condition.id;
  condition.name=labelFor(schema);
  condition.negate=Boolean(condition.negate);
  condition.required=Boolean(condition.required);
  condition.fields=Array.isArray(condition.fields)?condition.fields.map(field=>clone(field)):[];
  return condition;
};

function NativeFieldInput({field,onChange}:{field:NativeField;onChange:(value:unknown)=>void}){
  const options=fieldOptions(field),type=String(field.type||'').toLowerCase(),value=field.value??'';
  if(options.length)return <select value={String(value)} onChange={event=>{const option=options.find(item=>String(item.value)===event.target.value);onChange(option?.value??event.target.value);}}>{options.map((option,index)=><option key={`${String(option.value)}-${index}`} value={String(option.value)}>{option.name||option.label||String(option.value)}</option>)}</select>;
  if(type.includes('bool')||typeof value==='boolean')return <input type="checkbox" checked={Boolean(value)} onChange={event=>onChange(event.target.checked)}/>;
  if(Array.isArray(value))return <input value={value.join(', ')} onChange={event=>onChange(list(event.target.value))}/>;
  if(type.includes('int')||type.includes('number')||typeof value==='number')return <input type="number" value={Number(value)} onChange={event=>onChange(event.target.value===''?'':Number(event.target.value))}/>;
  return <input value={String(value)} onChange={event=>onChange(event.target.value)}/>;
}

export function SelectionRulesView({options}:{options:SelectionRulesMountOptions}){
  const [domain,setDomain]=useState<SelectionDomain>('movie'),[section,setSection]=useState<SelectionSection>(options.section),[profiles,setProfiles]=useState<QualityProfile[]>([]),[formats,setFormats]=useState<CustomFormat[]>([]),[releases,setReleases]=useState<ReleaseProfile[]>([]),[schemas,setSchemas]=useState<ApiRecord[]>([]),[tags,setTags]=useState<ApiRecord[]>([]),[indexers,setIndexers]=useState<ApiRecord[]>([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState('');
  const formatNames=useMemo(()=>new Map(formats.map(format=>[Number(format.id),format.name||`Format ${format.id}`])),[formats]);
  const load=async()=>{setLoading(true);try{
    const safe=<T,>(path:string)=>options.request<{result:T}>(path).catch(()=>({result:[] as T}));
    const [profileValue,formatValue,releaseValue,schemaValue,tagValue,indexerValue]=await Promise.all([
      options.request<{result:QualityProfile[]}>(`/api/manage/${domain}/profiles`),
      options.request<{result:CustomFormat[]}>(`/api/manage/${domain}/customFormats`),
      options.request<{result:ReleaseProfile[]}>(`/api/manage/${domain}/${releaseResource(domain)}`),
      safe<ApiRecord[]>(`/api/manage/${domain}/customFormatSchemas`),
      safe<ApiRecord[]>(`/api/manage/${domain}/tags`),
      safe<ApiRecord[]>(`/api/manage/${domain}/indexers`)
    ]);
    setProfiles(profileValue.result||[]);setFormats(formatValue.result||[]);setReleases(releaseValue.result||[]);setSchemas(schemaValue.result||[]);setTags(tagValue.result||[]);setIndexers(indexerValue.result||[]);
  }catch(reason){options.notify(errorMessage(reason),'error');}finally{setLoading(false);}};
  useEffect(()=>{void load();},[domain]);
  const updateFormat=(index:number,change:(format:CustomFormat)=>CustomFormat)=>setFormats(current=>current.map((format,i)=>i===index?change(format):format));
  const saveFormat=async(format:CustomFormat,isNew=false)=>{setBusy(`format-${format.id||'new'}`);try{await options.request(`/api/manage/${domain}/customFormats${isNew?'':`/${format.id}`}`,{method:isNew?'POST':'PUT',body:JSON.stringify(format)});options.notify('Custom format saved to the engine.');await load();}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const removeFormat=async(format:CustomFormat,index:number)=>{if(!format.id){setFormats(current=>current.filter((_,i)=>i!==index));return;}if(!confirm(`Delete ${format.name}?`))return;try{await options.request(`/api/manage/${domain}/customFormats/${format.id}`,{method:'DELETE'});options.notify('Custom format deleted.');await load();}catch(reason){options.notify(errorMessage(reason),'error');}};
  const saveProfile=async(profile:QualityProfile)=>{setBusy(`profile-${profile.id}`);try{await options.request(`/api/manage/${domain}/profiles/${profile.id}`,{method:'PUT',body:JSON.stringify(profile)});options.notify(`${profile.name} scores saved to the engine.`);await load();}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const score=(profile:QualityProfile,formatId:number)=>profile.formatItems?.find(item=>Number(item.format)===formatId)?.score||0;
  const setScore=(profileId:number,formatId:number,value:number)=>setProfiles(current=>current.map(profile=>{if(profile.id!==profileId)return profile;const items=[...(profile.formatItems||[])],index=items.findIndex(item=>Number(item.format)===formatId);if(index>=0)items[index]={...items[index],score:value};else items.push({format:formatId,name:formatNames.get(formatId),score:value});return{...profile,formatItems:items};}));
  const updateRelease=(index:number,change:Partial<ReleaseProfile>)=>setReleases(current=>current.map((profile,i)=>i===index?{...profile,...change}:profile));
  const saveRelease=async(profile:ReleaseProfile,isNew=false)=>{setBusy(`release-${profile.id||'new'}`);try{await options.request(`/api/manage/${domain}/${releaseResource(domain)}${isNew?'':`/${profile.id}`}`,{method:isNew?'POST':'PUT',body:JSON.stringify(profile)});options.notify('Release profile saved to the engine.');await load();}catch(reason){options.notify(errorMessage(reason),'error');}finally{setBusy('');}};
  const removeRelease=async(profile:ReleaseProfile,index:number)=>{if(!profile.id){setReleases(current=>current.filter((_,i)=>i!==index));return;}if(!confirm(`Delete ${profile.name}?`))return;try{await options.request(`/api/manage/${domain}/${releaseResource(domain)}/${profile.id}`,{method:'DELETE'});options.notify('Release profile deleted.');await load();}catch(reason){options.notify(errorMessage(reason),'error');}};
  const toggleId=(values:number[]|undefined,id:number)=>values?.includes(id)?values.filter(value=>value!==id):[...(values||[]),id];
  return <div className="selection-rules-route">
    <div className="hero"><div><span className="eyebrow">RELEASE SELECTION</span><h1>Selection rules</h1><p className="lede">Configure the connected engines’ native matching, scoring, and release rules.</p></div></div>
    <nav className="settings-tabs"><a href="#service/root-folders">Root Folders</a><a href="#service/media-management">Media Management</a><a href="#service/profiles">Quality Profiles</a><a className={section==='custom-formats'?'active':''} href="#service/custom-formats" onClick={()=>setSection('custom-formats')}>Custom Formats</a><a className={section==='release-profiles'?'active':''} href="#service/release-profiles" onClick={()=>setSection('release-profiles')}>Release Profiles</a><a href="#service/indexers">Indexers</a><a href="#service/download-clients">Download Clients</a><a href="#service/discover">Discover</a></nav>
    <div className="management-toolbar"><label>Library<select value={domain} onChange={event=>setDomain(event.target.value as SelectionDomain)}><option value="movie">Movies</option><option value="tv">Television</option></select></label><div className="selection-rule-explainer"><strong>{section==='custom-formats'?'Native scored matching':'Native release-title rules'}</strong><span>{section==='custom-formats'?`${schemas.length} condition types supplied by the selected engine.`:'Rules are written directly to the selected engine.'}</span></div></div>
    {loading?<div className="panel skeleton">Loading engine rules…</div>:section==='custom-formats'?<div className="selection-rule-stack">
      <section className="panel selection-rule-intro"><div><h2>Custom formats</h2><p>Build formats from the exact condition schemas reported by the connected engine.</p></div><button className="primary" onClick={()=>setFormats(current=>[{name:'New custom format',includeCustomFormatWhenRenaming:false,specifications:[]},...current])}>New custom format</button></section>
      {!formats.length?<div className="empty panel"><h2>No custom formats</h2><p>Create one here or in the connected engine.</p></div>:formats.map((format,formatIndex)=><form className="panel custom-format-editor" key={format.id||`new-${formatIndex}`} onSubmit={event=>{event.preventDefault();void saveFormat(format,!format.id);}}>
        <header className="editor-heading"><label>Name<input required value={format.name||''} onChange={event=>updateFormat(formatIndex,item=>({...item,name:event.target.value}))}/></label><label className="check"><input type="checkbox" checked={Boolean(format.includeCustomFormatWhenRenaming)} onChange={event=>updateFormat(formatIndex,item=>({...item,includeCustomFormatWhenRenaming:event.target.checked}))}/> Include when renaming</label><button type="button" className="danger-secondary" onClick={()=>void removeFormat(format,formatIndex)}>Delete</button></header>
        <div className="condition-list">{(format.specifications||[]).map((condition,conditionIndex)=><section className="condition-card" key={`${condition.implementation}-${conditionIndex}`}>
          <div className="condition-heading"><strong>{condition.implementationName||condition.implementation||'Condition'}</strong><label>Name<input value={condition.name||''} onChange={event=>updateFormat(formatIndex,item=>{const specifications=clone(item.specifications||[]);specifications[conditionIndex]={...specifications[conditionIndex],name:event.target.value};return{...item,specifications};})}/></label><label className="check"><input type="checkbox" checked={Boolean(condition.negate)} onChange={event=>updateFormat(formatIndex,item=>{const specifications=clone(item.specifications||[]);specifications[conditionIndex]={...specifications[conditionIndex],negate:event.target.checked};return{...item,specifications};})}/> Negate</label><label className="check"><input type="checkbox" checked={Boolean(condition.required)} onChange={event=>updateFormat(formatIndex,item=>{const specifications=clone(item.specifications||[]);specifications[conditionIndex]={...specifications[conditionIndex],required:event.target.checked};return{...item,specifications};})}/> Required</label><button type="button" className="text-button" onClick={()=>updateFormat(formatIndex,item=>({...item,specifications:(item.specifications||[]).filter((_,i)=>i!==conditionIndex)}))}>Remove</button></div>
          <div className="native-field-grid">{(condition.fields||[]).map((field,fieldIndex)=><label key={`${field.name}-${fieldIndex}`}>{field.label||field.name}{field.helpText?<small>{String(field.helpText)}</small>:null}<NativeFieldInput field={field} onChange={value=>updateFormat(formatIndex,item=>{const specifications=clone(item.specifications||[]),fields=clone(specifications[conditionIndex].fields||[]);fields[fieldIndex]={...fields[fieldIndex],value};specifications[conditionIndex]={...specifications[conditionIndex],fields};return{...item,specifications};})}/></label>)}</div>
        </section>)}</div>
        <div className="editor-actions"><label>Add native condition<select value="" onChange={event=>{const schema=schemas[Number(event.target.value)];if(schema)updateFormat(formatIndex,item=>({...item,specifications:[...(item.specifications||[]),createCondition(schema)]}));}}><option value="">Choose condition…</option>{schemas.map((schema,index)=><option key={`${schema.implementation}-${index}`} value={index}>{labelFor(schema)}</option>)}</select></label><button className="primary" disabled={busy===`format-${format.id||'new'}`}>{busy===`format-${format.id||'new'}`?'Saving…':'Save custom format'}</button></div>
      </form>)}
      <section className="panel scoring-panel"><div><h2>Quality profile scores</h2><p>Set each native format’s score and all score thresholds for each quality profile.</p></div>{profiles.map(profile=><form key={profile.id} onSubmit={event=>{event.preventDefault();void saveProfile(profile);}}><header><strong>{profile.name}</strong><div className="score-thresholds"><label>Minimum custom format score<input type="number" value={profile.minFormatScore||0} onChange={event=>setProfiles(current=>current.map(item=>item.id===profile.id?{...item,minFormatScore:Number(event.target.value)}:item))}/></label><label>Upgrade until custom format score<input type="number" value={profile.cutoffFormatScore||0} onChange={event=>setProfiles(current=>current.map(item=>item.id===profile.id?{...item,cutoffFormatScore:Number(event.target.value)}:item))}/></label><label>Minimum custom format score increment<input type="number" value={profile.minUpgradeFormatScore||0} onChange={event=>setProfiles(current=>current.map(item=>item.id===profile.id?{...item,minUpgradeFormatScore:Number(event.target.value)}:item))}/></label></div></header><div className="format-score-grid">{formats.filter(format=>format.id).map(format=><label key={format.id}>{format.name}<input type="number" value={score(profile,Number(format.id))} onChange={event=>setScore(Number(profile.id),Number(format.id),Number(event.target.value))}/></label>)}</div><button className="secondary" disabled={busy===`profile-${profile.id}`}>{busy===`profile-${profile.id}`?'Saving…':'Save quality profile scores'}</button></form>)}</section>
    </div>:<div className="selection-rule-stack">
      <section className="panel selection-rule-intro"><div><h2>Release profiles</h2><p>{domain==='movie'?'Movie restriction fields':'Television release-profile fields'} are preserved and saved natively.</p></div><button className="primary" onClick={()=>setReleases(current=>[{name:'New release profile',enabled:true,required:[],ignored:[],indexerId:0,tags:[],excludedTags:[],...(domain==='tv'?{preferred:[],includePreferredWhenRenaming:false,airDateRestriction:'always',airDateGracePeriod:0,allowSeasonPackWithoutAllEpisodesAired:false}:{})},...current])}>New release profile</button></section>
      {!releases.length?<div className="empty panel"><h2>No release profiles</h2><p>Create one here or in the connected engine.</p></div>:releases.map((profile,index)=><form className="panel release-profile-card" key={profile.id||`new-${index}`} onSubmit={event=>{event.preventDefault();void saveRelease(profile,!profile.id);}}>
        <div className="editor-heading"><label>Name<input required value={profile.name||''} onChange={event=>updateRelease(index,{name:event.target.value})}/></label><label className="check"><input type="checkbox" checked={profile.enabled!==false} onChange={event=>updateRelease(index,{enabled:event.target.checked})}/> Enabled</label><button className="danger-secondary" type="button" onClick={()=>void removeRelease(profile,index)}>Delete</button></div>
        <div className="native-field-grid"><label>Must contain<small>One term per line</small><textarea value={list(profile.required).join('\n')} onChange={event=>updateRelease(index,{required:event.target.value.split(/\r?\n/).map(value=>value.trim()).filter(Boolean)})}/></label><label>Must not contain<small>One term per line</small><textarea value={list(profile.ignored).join('\n')} onChange={event=>updateRelease(index,{ignored:event.target.value.split(/\r?\n/).map(value=>value.trim()).filter(Boolean)})}/></label><label>Indexer<select value={profile.indexerId||0} onChange={event=>updateRelease(index,{indexerId:Number(event.target.value)})}><option value={0}>All indexers</option>{indexers.map(indexer=><option key={indexer.id} value={indexer.id}>{indexer.name}</option>)}</select></label></div>
        {domain==='tv'?<section className="preferred-editor"><div className="preferred-heading"><div><strong>Preferred terms</strong><small>The television engine adds these scores when a release title matches.</small></div><label className="check"><input type="checkbox" checked={Boolean(profile.includePreferredWhenRenaming)} onChange={event=>updateRelease(index,{includePreferredWhenRenaming:event.target.checked})}/> Include preferred term when renaming</label><button type="button" className="secondary" onClick={()=>updateRelease(index,{preferred:[...(profile.preferred||[]),{key:'',value:0}]})}>Add preferred term</button></div>{(profile.preferred||[]).map((preferred,preferredIndex)=><div className="preferred-row" key={preferredIndex}><label>Term<input value={preferred.key||''} onChange={event=>updateRelease(index,{preferred:(profile.preferred||[]).map((item,i)=>i===preferredIndex?{...item,key:event.target.value}:item)})}/></label><label>Score<input type="number" value={preferred.value||0} onChange={event=>updateRelease(index,{preferred:(profile.preferred||[]).map((item,i)=>i===preferredIndex?{...item,value:Number(event.target.value)}:item)})}/></label><button type="button" className="text-button" onClick={()=>updateRelease(index,{preferred:(profile.preferred||[]).filter((_,i)=>i!==preferredIndex)})}>Remove</button></div>)}</section>:null}
        {tags.length?<div className="tag-fields"><fieldset><legend>Tags</legend>{tags.map(tag=><label className="check" key={tag.id}><input type="checkbox" checked={numbers(profile.tags).includes(Number(tag.id))} onChange={()=>updateRelease(index,{tags:toggleId(numbers(profile.tags),Number(tag.id))})}/>{tag.name}</label>)}</fieldset>{domain==='tv'&&('excludedTags' in profile)?<fieldset><legend>Excluded tags</legend>{tags.map(tag=><label className="check" key={tag.id}><input type="checkbox" checked={numbers(profile.excludedTags).includes(Number(tag.id))} onChange={()=>updateRelease(index,{excludedTags:toggleId(numbers(profile.excludedTags),Number(tag.id))})}/>{tag.name}</label>)}</fieldset>:null}</div>:null}
        {domain==='tv'?<div className="native-field-grid television-release-fields"><label>Apply restriction<select value={profile.airDateRestriction||'always'} onChange={event=>updateRelease(index,{airDateRestriction:event.target.value})}><option value="always">Always</option><option value="afterAirDate">After air date</option><option value="beforeAirDate">Before air date</option></select></label><label>Air-date grace period (hours)<input type="number" min="0" value={profile.airDateGracePeriod||0} onChange={event=>updateRelease(index,{airDateGracePeriod:Number(event.target.value)})}/></label><label className="check"><input type="checkbox" checked={Boolean(profile.allowSeasonPackWithoutAllEpisodesAired)} onChange={event=>updateRelease(index,{allowSeasonPackWithoutAllEpisodesAired:event.target.checked})}/> Allow season pack before all episodes air</label></div>:null}
        <div className="editor-actions"><span>Changes are applied directly to the {domain==='movie'?'movie':'television'} engine.</span><button className="primary" disabled={busy===`release-${profile.id||'new'}`}>{busy===`release-${profile.id||'new'}`?'Saving…':'Save release profile'}</button></div>
      </form>)}
    </div>}
  </div>;
}
