import type {SetupCenterMountOptions} from './setup-center-types';
import {SetupNav} from './setup-nav';
import './setup-center.css';

const steps=[
  {number:'1',title:'Media engines',description:'Choose the built-in engines or connect the compatible movie and television instances you already use.',href:'#setup/engines',action:'Review media engines'},
  {number:'2',title:'Storage & destinations',description:'Tell VynodeArr where downloads arrive and where finished movies and shows belong. Set a default destination for each library.',href:'#setup/storage',action:'Configure storage'},
  {number:'3',title:'Quality preferences',description:'Choose the qualities you accept and whether existing files should be upgraded. The included templates provide safe starting points.',href:'#service/profiles',action:'Review quality profiles'},
  {number:'4',title:'Search & downloads',description:'Connect at least one indexer and one download client, then test both connections before requesting media.',href:'#setup/search',action:'Configure searching'},
  {number:'5',title:'Optional integrations',description:'Connect TMDB, Plex, and Reeltrack only when you want their discovery, library, artwork, or list features.',href:'#setup/integrations',action:'Review integrations'},
  {number:'6',title:'Health check',description:'Run the final checks. VynodeArr links every problem directly to the setting that resolves it.',href:'#setup/health',action:'Check installation'},
];

function Overview(){return <><section className="setup-intro panel"><div><span className="eyebrow">START HERE</span><h2>Set up the essentials in order</h2><p>VynodeArr needs an engine, accessible media folders, a quality profile, an indexer, and a download client. Plex, TMDB, Reeltrack, overlays, and advanced rules are optional and can be added later.</p></div><div className="setup-intro-note"><strong>Nothing here moves existing media automatically.</strong><p>VynodeArr validates connections and paths before using them. Existing detailed settings remain available under Service Settings.</p></div></section><div className="setup-step-grid">{steps.map(step=><article className="setup-step-card panel" key={step.number}><span className="setup-step-number">{step.number}</span><div><h2>{step.title}</h2><p>{step.description}</p><a className="button-link secondary" href={step.href}>{step.action}</a></div></article>)}</div></>}

function SearchAndDownloads(){return <div className="setup-choice-grid"><section className="panel setup-guidance-card"><span className="eyebrow">SEARCH SOURCES</span><h2>1. Add an indexer</h2><p>Indexers tell an engine which releases are available. Configure at least one for Movies and one for Television, then use its test button before saving.</p><ul><li>Use credentials supplied by your indexer.</li><li>Enable automatic and interactive search as needed.</li><li>External-engine indexers remain separated by instance.</li></ul><a className="primary button-link" href="#service/indexers">Configure indexers</a></section><section className="panel setup-guidance-card"><span className="eyebrow">DOWNLOAD HANDOFF</span><h2>2. Add a download client</h2><p>The download client receives an accepted release. Its completed-download folder must represent the same host folder that VynodeArr sees.</p><ul><li>Test the client connection.</li><li>Confirm its category and completed-download handling.</li><li>Use Storage &amp; Destinations when container paths differ.</li></ul><a className="primary button-link" href="#service/download-clients">Configure download clients</a></section><section className="notice setup-next-step"><strong>Then verify the complete path</strong><p>After both connections test successfully, run Health Check. It detects missing providers, unavailable roots, and incompatible download paths.</p><a className="secondary button-link" href="#setup/health">Run health check</a></section></div>}

function Integrations(){return <div className="setup-integration-grid"><section className="panel setup-guidance-card"><span className="eyebrow">DISCOVERY · OPTIONAL</span><h2>TMDB</h2><p>Add a TMDB read-access token for live Discover results, cast information, artwork, and trailers. Media-engine management continues to work without it.</p><a className="secondary button-link" href="#service/discover">Connect TMDB</a></section><section className="panel setup-guidance-card"><span className="eyebrow">MEDIA SERVER · OPTIONAL</span><h2>Plex</h2><p>Connect Plex for library matching, poster management, overlays, and managed list collections. Plex is not required to search or download media.</p><a className="secondary button-link" href="#service/poster-overlays">Connect Plex &amp; overlays</a></section><section className="panel setup-guidance-card"><span className="eyebrow">LISTS · OPTIONAL</span><h2>Reeltrack and import lists</h2><p>Import and review titles first. Plex synchronization, trailers, collections, and list artwork remain off until you configure them separately.</p><div className="setup-card-actions"><a className="secondary button-link" href="#lists">Review list titles</a><a className="secondary button-link" href="#lists/automation">Configure list automation</a></div></section></div>}

export function SetupCenterView({options}:{options:SetupCenterMountOptions}){
 const section=options.section;
 return <div className="react-setup-center"><div className="hero"><div><span className="eyebrow">INSTALLATION SETUP</span><h1>{section==='overview'?'Setup overview':section==='search'?'Search & downloads':'Integrations'}</h1><p className="lede">{section==='overview'?'A clear path from a new installation to the first successful request.':section==='search'?'Connect the services that find releases and receive downloads.':'Add optional services when you are ready for their features.'}</p></div>{section!=='overview'?<a className="secondary button-link" href="#setup">Back to setup overview</a>:null}</div><SetupNav active={section}/>{section==='overview'?<Overview/>:section==='search'?<SearchAndDownloads/>:<Integrations/>}</div>;
}
