import { useEffect, useState, type FormEvent } from "react";
import type { MediaExpansionOptions } from "./media-expansion-types";
type Definition={id:string;name:string;description:string;capabilities:string[];fields:Array<{key:string;label:string;type:"text"|"password"|"url"|"checkbox";required?:boolean;help?:string;placeholder?:string;defaultValue?:boolean}>};
const message=(error:unknown)=>error instanceof Error?error.message:"The request could not be completed.";
export default function SubtitleProviderForm({options,onSave}:{options:MediaExpansionOptions;onSave:()=>void}){
 const[catalog,setCatalog]=useState<Definition[]>([]),[selected,setSelected]=useState("opensubtitles"),[busy,setBusy]=useState(false);
 useEffect(()=>{void options.request<{providers:Definition[]}>("/api/subtitles/provider-catalog").then(value=>setCatalog(value.providers)).catch(error=>options.notify(message(error),"error"));},[options]);
 const definition=catalog.find(item=>item.id===selected)||catalog[0];
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);const form=event.currentTarget;try{const input=Object.fromEntries(new FormData(form).entries());await options.request("/api/subtitles/providers",{method:"POST",body:JSON.stringify({...input,implementation:selected,priority:Number(input.priority)||25,enabled:true})});form.reset();options.notify(`${definition?.name||"Subtitle provider"} connected.`);onSave();}catch(error){options.notify(message(error),"error");}finally{setBusy(false);}}
 return <form className="panel expansion-provider-form subtitle-provider-editor" onSubmit={submit}><div><span className="eyebrow">PROVIDER CATALOG</span><h2>Add subtitle source</h2><p className="muted">Each source asks only for the connection details it needs.</p></div><div className="subtitle-provider-choices">{catalog.map(item=><button className={item.id===selected?"selected":""} key={item.id} type="button" onClick={()=>setSelected(item.id)}><strong>{item.name}</strong><small>{item.description}</small></button>)}</div>{definition&&<><div className="provider-definition"><strong>{definition.name}</strong><span className="muted">{definition.capabilities.join(" · ")}</span></div><div className="form-grid"><label>Connection name<input name="name" required defaultValue={definition.name}/></label>{definition.fields.map(field=>field.type==="checkbox"?<label className="check" key={field.key}><input name={field.key} type="checkbox" defaultChecked={field.defaultValue}/>{field.label}</label>:<label key={field.key}>{field.label}<input name={field.key} type={field.type} required={field.required} placeholder={field.placeholder} autoComplete={field.type==="password"?"new-password":undefined}/>{field.help&&<small>{field.help}</small>}</label>)}<label>Priority<input name="priority" type="number" min="1" max="100" defaultValue="25"/></label></div></>}<button className="primary" disabled={busy||!definition}>{busy?"Connecting…":"Save and connect"}</button></form>;
}
