import {useEffect,useState} from "react";
import type {PerformanceReport,PerformanceSettings,SystemDomain,SystemMountOptions} from "./system-types";

const domains:SystemDomain[]=["movie","tv"];
const errorText=(reason:unknown)=>reason instanceof Error?reason.message:"System recovery could not be completed.";

export default function SystemPerformancePanel({report,options,reload}:{report:PerformanceReport;options:SystemMountOptions;reload:()=>void}){
  const [settings,setSettings]=useState<PerformanceSettings>(report.settings),[busy,setBusy]=useState(false),[recovery,setRecovery]=useState("");
  useEffect(()=>setSettings(report.settings),[report]);
  const mib=(value=0)=>`${(value/1048576).toFixed(0)} MB`,field=(key:keyof PerformanceSettings,label:string,min:number,max:number)=><label>{label}<input type="number" min={min} max={max} value={Number(settings[key]||0)} onChange={event=>setSettings(current=>({...current,[key]:Number(event.target.value)}))}/></label>;
  async function save(){setBusy(true);try{await options.request("/api/system/performance/settings",{method:"PUT",body:JSON.stringify(settings)});options.notify("Resource controls updated.");reload();}catch(reason){options.notify(errorText(reason),"error");}finally{setBusy(false);}}
  async function recover(domain:SystemDomain,action:"retry"|"rebuild"){
    if(action==="rebuild"&&!confirm(`Rebuild the ${domain==="movie"?"Movies":"Television"} catalog from its engine? The current catalog remains available unless a complete engine response succeeds.`))return;
    setRecovery(`${domain}:${action}`);try{await options.request("/api/system/catalog/recovery",{method:"POST",body:JSON.stringify({domain,action})});options.notify(action==="rebuild"?"Catalog rebuilt and verified.":"Failed work retried.");reload();}catch(reason){options.notify(errorText(reason),"error");}finally{setRecovery("");}
  }
  return <>
    <div className="system-domain-grid performance-summary">
      <section className="panel"><span className="eyebrow">APPLICATION PROCESS</span><h2>{mib(report.process.rss)} resident memory</h2><p>{mib(report.process.heapUsed)} JavaScript heap used · uptime {Math.floor(report.process.uptimeSeconds/3600)}h</p></section>
      <section className="panel"><span className="eyebrow">LOCAL CATALOG</span><h2>{Number(report.catalog.movie||0)+Number(report.catalog.tv||0)} titles</h2><p>{report.activity?.catalogReads||0} database reads · {report.activity?.engineReads||0} engine reads</p></section>
      <section className="panel"><span className="eyebrow">ARTWORK CACHE</span><h2>{report.artwork.memory?.items||0} memory items</h2><p>{mib(report.artwork.memory?.bytes||0)} memory · {mib(report.artwork.disk?.bytes||0)} indexed on disk</p></section>
    </div>
    <section className="panel performance-controls"><div className="panel-heading"><div><span className="eyebrow">RESOURCE CONTROLS</span><h2>Performance limits</h2></div><button className="primary" disabled={busy} onClick={()=>void save()}>{busy?"Saving…":"Save limits"}</button></div><p>Bound background work so browsing remains responsive while the local catalog stays current.</p><div className="performance-field-grid">{field("pageSize","Library page size",20,250)}{field("eventConcurrency","Event workers",1,4)}{field("artworkFetchConcurrency","Artwork downloads",1,8)}{field("artworkWriteConcurrency","Artwork disk writes",1,4)}{field("integrityIntervalMinutes","Integrity check (minutes)",30,1440)}</div></section>
    <div className="system-domain-grid">{domains.map(domain=>{const state=report.sync?.[domain],integrity=report.catalog.integrity?.[domain],open=state?.circuit?.state==="open";return <section className="panel" key={domain}><div className="panel-heading"><div><span className="eyebrow">{domain==="movie"?"MOVIE ENGINE":"TELEVISION ENGINE"}</span><h2>{open?"Recovering":state?.status||"Unknown"}</h2></div><span className={`badge ${integrity?.healthy?"green":""}`}>{integrity?.healthy?"Catalog healthy":"Review needed"}</span></div><div className="data-row"><span><strong>Local catalog</strong><small>{integrity?.itemCount||0} titles</small></span><span>{integrity?.lastSuccess?new Date(integrity.lastSuccess).toLocaleString():"Never synchronized"}</span></div><div className="data-row"><span><strong>Engine circuit</strong><small>{state?.circuit?.failures||0} consecutive failures</small></span><span>{state?.circuit?.state||"not reported"}</span></div><div className="data-row"><span><strong>Background queue</strong><small>{state?.workQueue?.active?.label||"Idle"}</small></span><span>{state?.workQueue?.depth||0} waiting</span></div>{integrity?.issues?.length?<div className="notice"><strong>Integrity findings</strong><p>{integrity.issues.join(" · ")}</p></div>:null}{state?.safeError?<p className="form-error">{state.safeError}</p>:null}<div className="button-row"><button className="secondary" disabled={Boolean(recovery)} onClick={()=>void recover(domain,"retry")}>{recovery===`${domain}:retry`?"Retrying…":"Retry failed work"}</button><button className="secondary" disabled={Boolean(recovery)} onClick={()=>void recover(domain,"rebuild")}>{recovery===`${domain}:rebuild`?"Rebuilding…":"Rebuild catalog"}</button></div></section>;})}</div>
    <section className="panel"><div className="panel-heading"><h2>Most expensive API routes</h2><span className="badge">{report.requests.length}</span></div>{report.requests.slice(0,15).map(item=><div className="data-row" key={item.path}><span><strong>{item.path}</strong><small>{item.count} requests</small></span><span>{item.averageMs} ms avg · {item.maxMs} ms max</span></div>)}</section>
  </>;
}
