import { useCallback,useEffect,useMemo,useRef,useState,type ReactNode } from 'react';
import type { ApplicationUpdate,DiskSpace,SystemDomain,SystemMountOptions,SystemRecord,SystemView } from './system-types';
import './react-system.css';

const domains:SystemDomain[]=['movie','tv'],label=(domain:SystemDomain)=>domain==='movie'?'Movies':'Television',errorText=(reason:unknown)=>reason instanceof Error?reason.message:'System information could not be loaded.';
const date=(value?:string)=>value?new Intl.DateTimeFormat(undefined,{dateStyle:'medium',timeStyle:'short'}).format(new Date(value)):'Never';
const size=(value=0)=>value<1048576?`${Math.max(1,Math.round(value/1024))} KB`:`${(value/1048576).toFixed(1)} MB`;
const storageSize=(bytes=0)=>bytes>=1099511627776?`${(bytes/1099511627776).toFixed(1)} TB`:`${Math.round(bytes/1073741824)} GB`;
const cadence=(minutes=0)=>!minutes?'Automatic schedule unavailable':minutes%10080===0?`Every ${minutes/10080} week${minutes===10080?'':'s'}`:minutes%1440===0?`Every ${minutes/1440} day${minutes===1440?'':'s'}`:minutes%60===0?`Every ${minutes/60} hour${minutes===60?'':'s'}`:`Every ${minutes} minute${minutes===1?'':'s'}`;

function DomainSection({domain,count,children}:{domain:SystemDomain;count:number;children:ReactNode}){
  return <section className="system-domain-section"><div className="panel-heading"><div><span className="eyebrow">{domain==='movie'?'MOVIE ENGINE':'TELEVISION ENGINE'}</span><h2>{label(domain)}</h2></div><span className="badge">{count}</span></div>{children}</section>;
}
function Status({disks}:{disks:Record<SystemDomain,DiskSpace[]>}){
  return <div className="system-domain-grid">{domains.map(domain=>{const items=disks[domain]||[],primary=items.find(item=>item.path===(domain==='movie'?'/movies':'/tv'))||items[0],free=Number(primary?.freeSpace||0),total=Number(primary?.totalSpace||0),used=Math.max(0,total-free),percent=total?Math.round(used/total*100):0;return <DomainSection domain={domain} count={items.length} key={domain}><div className="storage-summary"><div><strong>{storageSize(free)}</strong><small>free of {storageSize(total)}</small></div><div><strong>{storageSize(used)}</strong><small>used · {percent}%</small></div></div><div className="storage-meter"><span style={{width:`${percent}%`}}/></div>{items.map(item=><div className="data-row" key={item.path}><span><strong>{item.path}</strong><small>{storageSize(item.freeSpace)} free of {storageSize(item.totalSpace)}</small></span><span className={item.freeSpace>10737418240?'status-path-state healthy':'status-path-state warning'}>{item.freeSpace>10737418240?'Available':'Low space'}</span></div>)}</DomainSection>;})}</div>;
}
function Tasks({items,run}:{items:SystemRecord[];run:(item:SystemRecord)=>void}){
  return <><div className="notice"><strong>Automatic schedules are active</strong><p>Run now starts an additional execution without changing the recurring schedule.</p></div><div className="system-domain-grid">{domains.map(domain=>{const records=items.filter(item=>item.domain===domain);return <DomainSection domain={domain} count={records.length} key={domain}>{records.map(item=><div className="data-row task-row" key={`${domain}:${item.taskName}`}><span><strong>{item.name||item.taskName}</strong><small>{cadence(item.interval)}</small><small>Last {date(item.lastExecution)} · Next {date(item.nextExecution)}</small></span><button className="secondary" onClick={()=>run(item)}>Run now</button></div>)}</DomainSection>;})}</div></>;
}
function Backups({items,options,reload}:{items:SystemRecord[];options:SystemMountOptions;reload:()=>void}){
  const inputs=useRef<Record<string,HTMLInputElement|null>>({});
  async function restore(item:SystemRecord){if(!confirm(`Restore this ${label(item.domain)} backup? The engine will restart and its current configuration will be replaced.`))return;try{await options.request(`/api/system/backups/${item.domain}/${item.id}/restore`,{method:'POST',body:'{}'});options.notify(`${label(item.domain)} backup restored successfully.`);reload();}catch(reason){options.notify(errorText(reason),'error');}}
  async function upload(domain:SystemDomain,file?:File){if(!file||!confirm(`Upload and restore ${label(domain)} from ${file.name}? The engine will restart and its current configuration will be replaced.`))return;const form=new FormData();form.append('file',file);try{await options.request(`/api/system/backups/${domain}/upload`,{method:'POST',body:form});options.notify(`${label(domain)} backup uploaded and restored successfully.`);reload();}catch(reason){options.notify(errorText(reason),'error');}}
  async function create(){try{await Promise.all(domains.map(domain=>options.request(`/api/manage/${domain}/commands`,{method:'POST',body:JSON.stringify({name:'Backup'})})));options.notify('Backup commands queued.');}catch(reason){options.notify(errorText(reason),'error');}}
  return <><div className="system-toolbar"><div className="notice"><strong>Keep copies outside the container</strong><p>Download backups before removing application data or Docker volumes.</p></div><button className="primary" onClick={()=>void create()}>Create both backups</button></div><div className="system-domain-grid">{domains.map(domain=>{const records=items.filter(item=>item.domain===domain);return <DomainSection domain={domain} count={records.length} key={domain}><input ref={node=>{inputs.current[domain]=node;}} hidden type="file" accept=".zip,.db,.xml" onChange={event=>{void upload(domain,event.target.files?.[0]);event.target.value='';}}/><button className="secondary system-upload" onClick={()=>inputs.current[domain]?.click()}>Upload & restore</button>{records.map(item=><div className="data-row" key={`${domain}:${item.id}`}><span><strong>{label(domain)} configuration backup</strong><small>{date(item.time)} · {item.type||'manual'} · {size(item.size)}</small></span><div><a className="secondary button-link" href={`/api/system/backups/${domain}/${item.id}/download`}>Download</a><button className="secondary" onClick={()=>void restore(item)}>Restore</button></div></div>)}</DomainSection>;})}</div></>;
}
function Events({items}:{items:SystemRecord[]}){
  const [level,setLevel]=useState('all'),[query,setQuery]=useState(''),filtered=useMemo(()=>items.filter(item=>(level==='all'||String(item.level||'info').toLowerCase().includes(level))&&`${item.message||''} ${item.exception||''}`.toLowerCase().includes(query.toLowerCase())),[items,level,query]);
  return <><div className="event-toolbar"><label>Level<select value={level} onChange={event=>setLevel(event.target.value)}><option value="all">All levels</option><option value="error">Errors</option><option value="warning">Warnings</option><option value="info">Information</option></select></label><label>Find events<input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search messages"/></label></div><div className="system-domain-grid">{domains.map(domain=>{const records=filtered.filter(item=>item.domain===domain);return <DomainSection domain={domain} count={records.length} key={domain}>{records.slice(0,200).map((item,index)=><article className={`event-row event-${String(item.level||'info').toLowerCase()}`} key={`${domain}:${item.time}:${index}`}><div><strong>{item.message||item.exception||'Event'}</strong><span className="event-level">{item.level||'info'}</span></div><time>{date(item.time)}</time></article>)}</DomainSection>;})}</div></>;
}

export function SystemView({options}:{options:SystemMountOptions}){
  const [view,setView]=useState<SystemView>('status'),[loading,setLoading]=useState(true),[error,setError]=useState(''),[records,setRecords]=useState<SystemRecord[]>([]),[disks,setDisks]=useState<Record<SystemDomain,DiskSpace[]>>({movie:[],tv:[]}),[update,setUpdate]=useState<ApplicationUpdate|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{if(view==='status'){const values=await Promise.all(domains.map(async domain=>({domain,value:await options.request<{result:DiskSpace[]}>(`/api/manage/${domain}/diskSpace`)})));setDisks(Object.fromEntries(values.map(item=>[item.domain,item.value.result])) as Record<SystemDomain,DiskSpace[]>);}else if(view==='updates')setUpdate(await options.request<ApplicationUpdate>('/api/system/application-update'));else{const values=await Promise.all(domains.map(async domain=>({domain,value:await options.request<{result:SystemRecord[]|{records:SystemRecord[]}}>(`/api/manage/${domain}/${view}?page=1&pageSize=200&sortKey=time&sortDirection=descending`)})));setRecords(values.flatMap(({domain,value})=>(Array.isArray(value.result)?value.result:value.result?.records||[]).map(item=>({...item,domain}))));}setError('');}catch(reason){setError(errorText(reason));}finally{setLoading(false);}},[options,view]);
  useEffect(()=>{void load();},[load]);
  async function sync(){try{await options.request('/api/system/sync',{method:'POST'});options.notify('Synchronization completed.');setView('status');await load();}catch(reason){options.notify(errorText(reason),'error');}}
  async function run(item:SystemRecord){try{await options.request(`/api/manage/${item.domain}/commands`,{method:'POST',body:JSON.stringify({name:item.taskName})});options.notify(`${label(item.domain)} task queued.`);}catch(reason){options.notify(errorText(reason),'error');}}
  return <div className="react-system"><div className="hero"><div><span className="eyebrow">SYSTEM</span><h1>System</h1><p className="lede">Storage, scheduled tasks, backups, updates, and engine events.</p></div><button className="primary" disabled={loading} onClick={()=>void sync()}>Synchronize now</button></div><div className="settings-tabs system-tabs">{(['status','tasks','backups','updates','events'] as SystemView[]).map(item=><button className={view===item?'wanted-tab active':'wanted-tab'} onClick={()=>setView(item)} key={item}>{item}</button>)}</div>{loading?<div className="panel skeleton">Loading system information…</div>:error?<div className="panel error-state"><h2>System information unavailable</h2><p>{error}</p><button className="secondary" onClick={()=>void load()}>Try again</button></div>:view==='status'?<Status disks={disks}/>:view==='tasks'?<Tasks items={records} run={item=>void run(item)}/>:view==='backups'?<Backups items={records} options={options} reload={()=>void load()}/>:view==='events'?<Events items={records}/>:update?<div className="panel"><div className="application-update"><div><span className="eyebrow">VYNODEARR APPLICATION</span><h2>Version {update.installedVersion}</h2><p className="muted">{update.channel} · {update.mechanism}</p></div><span className="badge green">Installed</span></div><div className="notice"><strong>VynodeArr updates</strong><p>{update.message}</p><a className="secondary button-link" href={update.repository} target="_blank" rel="noreferrer">View releases</a></div></div>:null}</div>;
}
