import { useCallback,useEffect,useState,type CSSProperties,type FormEvent } from 'react';
import type { TvDetail,TvDetailMountOptions,TvEpisode,TvSeason } from './tv-detail-types';
import './react-tv-detail.css';

const message=(reason:unknown)=>reason instanceof Error?reason.message:'The operation failed.';
type RawSeries=Record<string,unknown>&{monitored?:boolean;qualityProfileId?:number;path?:string;seriesType?:string;seasonFolder?:boolean;seasons?:Array<{seasonNumber:number;monitored:boolean}>};
type Option={id:number;name?:string;path?:string};

export function TvDetailView({options}:{options:TvDetailMountOptions}){
  const engineId=Number(options.publicId.replace(/^series_/,''));
  const [item,setItem]=useState<TvDetail|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[releases,setReleases]=useState<{title:string;items:Record<string,unknown>[]}|null>(null),[editing,setEditing]=useState<{series:RawSeries;profiles:Option[];roots:Option[]}|null>(null);
  const load=useCallback(async()=>{setLoading(true);try{const value=await options.request<{item:TvDetail}>(`/api/media/tv/${encodeURIComponent(options.publicId)}`);setItem(value.item);setError('');}catch(reason){setError(message(reason));}finally{setLoading(false);}},[options]);
  useEffect(()=>{void load();},[load]);
  const run=async(name:string,work:()=>Promise<unknown>,notice:string,reload=false)=>{setBusy(name);try{await work();options.notify(notice);if(reload)await load();}catch(reason){options.notify(message(reason),'error');}finally{setBusy('');}};
  const command=(name:string,payload:Record<string,unknown>={})=>run(name,()=>options.request('/api/manage/tv/commands',{method:'POST',body:JSON.stringify({name,...payload})}),name==='SeriesSearch'?'Series search queued.':'Refresh and folder scan queued.');
  const toggleSeries=()=>run('monitor-series',async()=>{const value=await options.request<{result:RawSeries}>(`/api/manage/tv/library/${engineId}`),raw=value.result;raw.monitored=!raw.monitored;await options.request(`/api/manage/tv/library/${engineId}`,{method:'PUT',body:JSON.stringify(raw)});},item?.monitoring==='none'?'Series monitored.':'Series unmonitored.',true);
  const rename=()=>run('rename',()=>options.request('/api/media-files/rename',{method:'POST',body:JSON.stringify({domain:'tv',mediaId:engineId})}),`Rename and organization queued for ${item?.title}.`);
  const toggleSeason=(season:TvSeason)=>run(`season-${season.seasonNumber}`,async()=>{const value=await options.request<{result:RawSeries}>(`/api/manage/tv/library/${engineId}`),raw=value.result,target=raw.seasons?.find(entry=>Number(entry.seasonNumber)===season.seasonNumber);if(!target)throw new Error('This season is no longer available.');target.monitored=!season.monitored;await options.request(`/api/manage/tv/library/${engineId}`,{method:'PUT',body:JSON.stringify(raw)});},`Season ${season.seasonNumber} ${season.monitored?'unmonitored':'monitored'}.`,true);
  const toggleEpisode=(episode:TvEpisode)=>run(`episode-${episode.id}`,async()=>{const id=episode.id.replace(/^episode_/,'');const value=await options.request<{result:Record<string,unknown>}>(`/api/manage/tv/episodes/${id}`),raw=value.result;raw.monitored=!episode.monitored;await options.request(`/api/manage/tv/episodes/${id}`,{method:'PUT',body:JSON.stringify(raw)});},episode.monitored?'Episode unmonitored.':'Episode monitored.',true);
  const autoEpisode=(episode:TvEpisode)=>run(`auto-${episode.id}`,()=>options.request('/api/manage/tv/automaticSearch',{method:'POST',body:JSON.stringify({episodeId:Number(episode.id.replace(/^episode_/,''))})}),'Best available episode release selected.');
  const interactive=async(episode:TvEpisode)=>{setBusy(`interactive-${episode.id}`);try{const value=await options.request<{result:Record<string,unknown>[] }>(`/api/manage/tv/releases?episodeId=${episode.id.replace(/^episode_/,'')}`);setReleases({title:`${item?.title} · ${episode.episodeNumber}. ${episode.title}`,items:(value.result||[]).slice(0,200)});}catch(reason){options.notify(message(reason),'error');}finally{setBusy('');}};
  const grab=(release:Record<string,unknown>)=>run('grab',async()=>{await options.request('/api/manage/tv/releases',{method:'POST',body:JSON.stringify(release)});setReleases(null);},'Release sent to the download client.');
  const edit=async()=>{setBusy('edit');try{const [series,profiles,roots]=await Promise.all([options.request<{result:RawSeries}>(`/api/manage/tv/library/${engineId}`),options.request<{result:Option[]}>('/api/manage/tv/profiles'),options.request<{result:Option[]}>('/api/manage/tv/rootFolders')]);setEditing({series:series.result,profiles:profiles.result||[],roots:roots.result||[]});}catch(reason){options.notify(message(reason),'error');}finally{setBusy('');}};
  const saveEdit=async(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();if(!editing)return;const form=new FormData(event.currentTarget),root=String(form.get('rootFolderPath')||''),current=String(editing.series.path||''),leaf=current.replace(/\\/g,'/').split('/').filter(Boolean).at(-1)||item?.title||'';const payload={...editing.series,monitored:form.get('monitored')==='on',qualityProfileId:Number(form.get('qualityProfileId')),rootFolderPath:root,path:`${root.replace(/[\\/]+$/,'')}/${leaf}`,seriesType:String(form.get('seriesType')||'standard'),seasonFolder:form.get('seasonFolder')==='on'};await run('save-edit',async()=>{await options.request(`/api/manage/tv/library/${engineId}?moveFiles=true`,{method:'PUT',body:JSON.stringify(payload)});setEditing(null);},'Library settings saved.',true);};
  const remove=async()=>{if(!item||!window.confirm(`Remove ${item.title} from the library? Files will be kept.`))return;await run('delete',async()=>{await options.request(`/api/manage/tv/library/${engineId}?deleteFiles=false`,{method:'DELETE'});location.hash='#tv';},`${item.title} removed.`);};
  if(loading)return <div className="detail-skeleton skeleton"/>;
  if(error||!item)return <div className="empty error-state"><h2>Television details unavailable</h2><p>{error}</p></div>;
  const facts=[['Network',item.network||'Not specified'],['Status',item.status||'Unknown'],['Monitoring',item.monitoring||'Unknown'],['Episodes',item.episodeProgress||'Not reported'],['Missing',item.missingEpisodes||0],['Next',item.nextEpisode?.airDateUtc?new Date(item.nextEpisode.airDateUtc).toLocaleDateString():'Complete']];
  return <div className="react-tv-detail" role="dialog" aria-modal="true" aria-label={`${item.title} television details`}>
    <div className="vynode-detail-surface">
    {item.backdrop?.url?<div className="detail-backdrop"><img src={item.backdrop.url} alt="" aria-hidden="true"/></div>:null}<a className="back-link" href="#tv">← Back to Television</a>
    <section className="detail-hero"><div className="detail-art">{item.artwork?.url?<img src={item.artwork.url} alt=""/>:<span className="art-fallback">TV</span>}</div><div className="detail-copy"><span className="eyebrow">TV SERIES</span><h1>{item.title}</h1><p className="lede">{item.overview}</p><span className="badge green">{item.monitoring||'Unknown'}</span><div className="detail-actions"><button className="primary" disabled={Boolean(busy)} onClick={()=>void command('SeriesSearch',{seriesId:engineId})}>Automatic search</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void toggleSeries()}>{item.monitoring==='none'?'Monitor':'Unmonitor'}</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void rename()}>Rename & organize</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void command('RefreshSeries',{seriesId:engineId})}>Refresh & scan</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void edit()}>Edit</button><button className="danger" disabled={Boolean(busy)} onClick={()=>void remove()}>Delete</button></div></div></section>
    <div className="fact-grid">{facts.map(([label,value])=><div key={label}><small>{label}</small><strong>{value}</strong></div>)}</div>
    <section className="panel season-panel"><div className="panel-heading"><div><span className="eyebrow">EPISODES</span><h2>Seasons</h2></div><span className="muted">{item.genres?.join(' · ')}</span></div>{item.seasons.map(season=><details style={{'--season-progress':`${season.episodeCount?Math.round(season.episodeFileCount/season.episodeCount*100):0}%`} as CSSProperties} className={`series-season availability-${!season.monitored?'unmonitored':season.episodeFileCount>=season.episodeCount?'complete':season.episodeFileCount?'partial':'missing'}`} key={season.seasonNumber}><summary><strong>Season {season.seasonNumber}</strong><span>{season.episodeFileCount}/{season.episodeCount}</span><button type="button" className="secondary" disabled={Boolean(busy)} onClick={event=>{event.preventDefault();void toggleSeason(season);}}>{season.monitored?'Unmonitor':'Monitor'}</button></summary><div className="season-episodes">{season.episodes.map(episode=><article className={`episode availability-${!episode.monitored?'unmonitored':episode.hasFile?'complete':'missing'}`} key={episode.id}><div><strong>{episode.episodeNumber}. {episode.title}</strong><small>{episode.hasFile?'Available':'Missing'} · {episode.monitored?'Monitored':'Unmonitored'}{episode.quality?` · ${episode.quality}`:''}</small></div><div className="episode-actions"><button className="secondary" disabled={Boolean(busy)} onClick={()=>void toggleEpisode(episode)}>{episode.monitored?'Unmonitor':'Monitor'}</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void autoEpisode(episode)}>Automatic search</button><button className="secondary" disabled={Boolean(busy)} onClick={()=>void interactive(episode)}>Interactive search</button></div></article>)}</div></details>)}</section>
    {editing?<dialog open className="react-tv-dialog react-tv-editor"><form onSubmit={event=>void saveEdit(event)}><div className="panel-heading"><h2>Edit {item.title}</h2><button type="button" className="secondary" onClick={()=>setEditing(null)}>Close</button></div><label className="check"><input name="monitored" type="checkbox" defaultChecked={Boolean(editing.series.monitored)}/> Monitored</label><label>Quality profile<select name="qualityProfileId" defaultValue={editing.series.qualityProfileId}>{editing.profiles.map(profile=><option value={profile.id} key={profile.id}>{profile.name}</option>)}</select></label><label>Root folder<select name="rootFolderPath" defaultValue={editing.roots.find(root=>editing.series.path?.startsWith(String(root.path)))?.path}>{editing.roots.map(root=><option value={root.path} key={root.id}>{root.path}</option>)}</select></label><label>Series type<select name="seriesType" defaultValue={editing.series.seriesType||'standard'}><option value="standard">Standard</option><option value="daily">Daily</option><option value="anime">Anime</option></select></label><label className="check"><input name="seasonFolder" type="checkbox" defaultChecked={Boolean(editing.series.seasonFolder)}/> Use season folders</label><div className="form-actions"><button type="button" className="secondary" onClick={()=>setEditing(null)}>Cancel</button><button className="primary" disabled={busy==='save-edit'}>Save changes</button></div></form></dialog>:null}
    {releases?<dialog open className="react-tv-dialog"><div className="panel-heading"><div><span className="eyebrow">INTERACTIVE SEARCH</span><h2>{releases.title}</h2></div><button className="secondary" onClick={()=>setReleases(null)}>Close</button></div><div className="wanted-release-list">{releases.items.map((release,index)=><article className="release-row" key={index}><div className="release-title"><strong>{String(release.title||'Unknown release')}</strong><small>{String(release.indexer||release.protocol||'Unknown source')}</small></div><span>{String((release.quality as {quality?:{name?:string}})?.quality?.name||'Unknown')}</span><span>{(Number(release.size||0)/1073741824).toFixed(2)} GB</span><span>{String(release.seeders??'—')} seeders</span><button className="primary" onClick={()=>void grab(release)}>Grab</button></article>)}</div></dialog>:null}
    </div>
  </div>;
}
