import {useState} from 'react';
import type {RootFoldersMountOptions,StorageDomain,UnraidStorageMapping} from './root-folders-types';
import {ModalPortal} from './modal-portal';

export interface UnraidMappingDraft{name:string;hostPath:string;containerPath:string}
export function UnraidMappingEditor({domain,value,options,onChange,onClose,onSaved}:{domain:StorageDomain;value:UnraidMappingDraft;options:RootFoldersMountOptions;onChange:(value:UnraidMappingDraft)=>void;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [busy,setBusy]=useState(false);const save=async()=>{setBusy(true);try{await options.request('/api/unraid/storage-mappings',{method:'POST',body:JSON.stringify({...value,domain})});options.notify('Template updated. In Unraid, edit VynodeArr and click Apply.');await onSaved();}catch(reason){options.notify(reason instanceof Error?reason.message:'The mapping could not be saved.','error');}finally{setBusy(false);}};
  return <ModalPortal><div className="root-folder-browser-backdrop" role="presentation" onMouseDown={event=>{if(event.target===event.currentTarget)onClose();}}><form className="panel unraid-mapping-editor" role="dialog" aria-modal="true" onSubmit={event=>{event.preventDefault();void save();}}>
    <div className="panel-heading"><div><span className="eyebrow">UNRAID STORAGE MAPPING</span><h2>Map another library folder</h2><p className="muted">This adds one Path entry to VynodeArr&apos;s own saved Unraid template. Every other container setting is preserved.</p></div><button type="button" className="secondary" onClick={onClose}>Close</button></div>
    <label>Friendly name<input required maxLength={80} value={value.name} placeholder={domain==='movie'?'4K Movies':'Anime TV'} onChange={event=>onChange({...value,name:event.target.value})}/><small className="field-help">The label users will see when choosing where new media goes.</small></label>
    <label>Unraid host path<input required value={value.hostPath} placeholder="/mnt/user/Movies-4K" onChange={event=>onChange({...value,hostPath:event.target.value})}/><small className="field-help">The real share or folder on your Unraid server. It must begin with /mnt/, for example /mnt/user/Movies-4K.</small></label>
    <label>Container path<input required value={value.containerPath} placeholder={domain==='movie'?'/movies-4k':'/tv-anime'} onChange={event=>onChange({...value,containerPath:event.target.value})}/><small className="field-help">A unique path VynodeArr and the bundled engine will use inside this container. Do not reuse /movies, /tv, /downloads, or /config.</small></label>
    <div className="notice storage-warning"><strong>Unraid must apply the change</strong><p>Saving validates the complete XML and atomically adds only this mapping. Then open the VynodeArr container in Unraid, choose Edit, and click Apply. A normal restart alone is not enough.</p></div>
    <div className="form-actions"><button type="button" className="secondary" onClick={onClose}>Cancel</button><button className="primary" disabled={busy}>{busy?'Validating…':'Validate and save mapping'}</button></div>
  </form></div></ModalPortal>;
}

export function PendingUnraidMappings({domain,items,options,onCompleted}:{domain:StorageDomain;items:UnraidStorageMapping[];options:RootFoldersMountOptions;onCompleted:()=>Promise<void>}){
  const [busy,setBusy]=useState('');const complete=async(item:UnraidStorageMapping)=>{setBusy(item.id);try{await options.request(`/api/unraid/storage-mappings/${item.id}/complete`,{method:'POST',body:'{}'});options.notify(`${item.name} is visible and registered with the ${item.domain==='movie'?'movie':'television'} engine.`);await onCompleted();}catch(reason){options.notify(reason instanceof Error?reason.message:'The mapping could not be completed.','error');}finally{setBusy('');}};
  const pending=items.filter(item=>item.domain===domain&&item.status!=='ready');if(!pending.length)return null;
  return <section className="panel pending-mappings"><div className="panel-heading"><div><span className="eyebrow">UNRAID ACTION REQUIRED</span><h2>Finish storage mappings</h2><p className="muted">The saved template is ready. In Unraid, open the VynodeArr container, click Edit, then Apply. Return here after the container starts.</p></div></div>{pending.map(item=><article className="storage-path-row" key={item.id}><span className={`storage-path-state ${item.accessible?'available':'unavailable'}`}/><div className="storage-path-copy"><strong>{item.name}</strong><small>{item.hostPath} → {item.containerPath}</small><small>{item.accessible?'Mapping detected; finish engine registration.':'Waiting for Unraid to apply the updated container configuration.'}</small></div><button className="primary" disabled={!item.accessible||busy===item.id} onClick={()=>void complete(item)}>{busy===item.id?'Checking…':'Verify and finish'}</button></article>)}</section>;
}

export function DestinationFolderActions({available,domain,name,onVisible,onMap}:{available:boolean;domain:StorageDomain;name:string;onVisible:()=>void;onMap:(value:UnraidMappingDraft)=>void}){
  return <><div className="destination-folder-actions"><button type="button" className="secondary" onClick={onVisible}>Use visible folder</button><button type="button" className="secondary" disabled={!available} onClick={()=>onMap({name,hostPath:'/mnt/user/',containerPath:domain==='movie'?'/movies-4k':'/tv-anime'})}>Map Unraid folder</button></div><small>{available?'Choose a folder already visible to the container, or safely add a new Unraid host-to-container mapping.':'Automatic Unraid mapping is unavailable. Update the container from the current template once to enable guarded template access.'}</small></>;
}
