import { useCallback,useEffect,useMemo,useState } from 'react';
import type { SearchJob,WantedDomain,WantedItem,WantedLibraryItem,WantedMountOptions,WantedView } from './wanted-types';
import './react-wanted.css';

const message=(reason:unknown)=>reason instanceof Error?reason.message:'The request could not be completed.';
export function WantedView({options}:{options:WantedMountOptions}){
  const [domain,setDomain]=useState<WantedDomain>('movie'),[view,setView]=useState<WantedView>('wantedMissing'),[items,setItems]=useState<WantedItem[]>([]),[library,setLibrary]=useState<WantedLibraryItem[]>([]);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[job,setJob]=useState<SearchJob|null>(null),[releases,setReleases]=useState<Record<string,unknown>[]|null>(null),[releaseTitle,setReleaseTitle]=useState('');
  const load=useCallback(async()=>{setLoading(true);try{const query=`page=1&pageSize=1000&sortKey=title&sortDirection=ascending${domain==='tv'&&view==='wantedMissing'?'&monitored=true':''}`;const [wantedValue,libraryValue]=await Promise.all([options.request<{result:{records?:WantedItem[]}|WantedItem[]}>(`/api/manage/${domain}/${view}?${query}`),options.request<{result:WantedLibraryItem[]}>((`/api/manage/${domain}/library`))]);const result=wantedValue.result;setItems(Array.isArray(result)?result:result.records||[]);setLibrary(libraryValue.result||[]);setError('');}catch(reason){setError(message(reason));}finally{setLoading(false);}},[domain,view,options]);
  const pollJobs=useCallback(async()=>{try{const value=await options.request<{items:SearchJob[]}>('/api/search-jobs');setJob(value.items.filter(item=>item.domain===domain).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]||null);}catch{}},[domain,options]);
  useEffect(()=>{void load();void pollJobs();},[load,pollJobs]);
  useEffect(()=>{if(!job||!['queued','running','canceling'].includes(job.status))return;const timer=window.setTimeout(()=>void pollJobs(),1500);return()=>window.clearTimeout(timer);},[job,pollJobs]);
  const libraryById=useMemo(()=>new Map(library.map(item=>[Number(item.id),item])),[library]);
  const command=async(name:string,payload:Record<string,unknown>,notice:string)=>{setBusy(name+JSON.stringify(payload));try{await options.request(`/api/manage/${domain}/commands`,{method:'POST',body:JSON.stringify({name,...payload})});options.notify(notice);}catch(reason){options.notify(message(reason),'error');}finally{setBusy('');}};
  const automatic=(item:WantedItem)=>command(domain==='movie'?'MoviesSearch':'EpisodeSearch',domain==='movie'?{movieIds:[Number(item.id)]}:{episodeIds:[Number(item.id)]},'Automatic search queued.');
  const interactive=async(item:WantedItem)=>{const title=item.title||item.series?.title||item.movie?.title||'Wanted item';setReleaseTitle(title);setReleases([]);try{const query=domain==='movie'?`movieId=${item.id}`:`episodeId=${item.id}`,value=await options.request<{result:Record<string,unknown>[] }>(`/api/manage/${domain}/releases?${query}`);setReleases(value.result||[]);}catch(reason){setReleases(null);options.notify(message(reason),'error');}};
  const grab=async(release:Record<string,unknown>)=>{try{await options.request(`/api/manage/${domain}/releases`,{method:'POST',body:JSON.stringify(release)});options.notify('Release sent to the download client.');setReleases(null);}catch(reason){options.notify(message(reason),'error');}};
  const startAll=async()=>{setBusy('all');try{await options.request('/api/search-jobs',{method:'POST',body:JSON.stringify({domain})});options.notify(`${domain==='movie'?'Movie':'Television'} missing search started.`);void pollJobs();}catch(reason){options.notify(message(reason),'error');}finally{setBusy('');}};
  const active=job&&['queued','running','canceling'].includes(job.status),done=(job?.completed||0)+(job?.failed||0);
  const groups=useMemo(()=>{const result=new Map<number,{title:string;tvdbId:number;seasons:Map<number,WantedItem[]>}>();for(const item of items){const seriesId=Number(item.seriesId),series=item.series||libraryById.get(seriesId)||{},entry=result.get(seriesId)||{title:series.title||`Series ${seriesId}`,tvdbId:Number(series.tvdbId||0),seasons:new Map()};const season=Number(item.seasonNumber||0);entry.seasons.set(season,[...(entry.seasons.get(season)||[]),item]);result.set(seriesId,entry);}return result;},[items,libraryById]);
  const actions=(item:WantedItem)=><div className="wanted-actions"><button className="secondary" disabled={Boolean(busy)} onClick={()=>void automatic(item)}>Automatic search</button><button className="secondary" onClick={()=>void interactive(item)}>Interactive search</button></div>;
  return <div className="react-wanted"><div className="hero"><div><span className="eyebrow">ATTENTION</span><h1>Wanted</h1><p className="lede">Missing items and quality-cutoff gaps across monitored libraries.</p></div><div className="hero-actions"><button className="primary" disabled={Boolean(active)||busy==='all'} onClick={()=>void startAll()}>{active?'Search running…':'Search all missing'}</button><button className="secondary" onClick={()=>void load()}>Refresh</button></div></div>
  {job?<div className="panel wanted-search-progress"><div className="panel-heading"><div><strong>{job.label} missing search</strong><small>{job.currentTitle||job.status} · {done}/{job.total}</small></div>{active?<button className="secondary" onClick={()=>void options.request(`/api/search-jobs/${job.id}`,{method:'DELETE'}).then(pollJobs)}>{job.status==='canceling'?'Canceling…':'Cancel'}</button>:null}</div><div className="import-job-meter"><span style={{width:`${Math.round(done/Math.max(1,job.total)*100)}%`}}/></div>{job.failed?<p className="form-error">{job.failed} items could not be queued.</p>:null}</div>:null}
  <div className="wanted-controls"><div className="settings-tabs wanted-domain-tabs">{(['movie','tv'] as WantedDomain[]).map(value=><button className={domain===value?'active':''} onClick={()=>setDomain(value)} key={value}>{value==='movie'?'Movies':'Television'}</button>)}</div><div className="settings-tabs">{([['wantedMissing','Missing'],['wantedCutoff','Cutoff unmet']] as [WantedView,string][]).map(([value,label])=><button className={view===value?'active':''} onClick={()=>setView(value)} key={value}>{label}</button>)}</div></div>
  {loading?<div className="panel skeleton">Loading…</div>:error?<div className="panel error-state"><p>{error}</p></div>:!items.length?<div className="panel empty"><h2>Nothing wanted</h2><p>This monitored library has no items in this view.</p></div>:domain==='movie'?<div className="panel">{items.map(item=>{const movie=item.movie||libraryById.get(Number(item.id))||item,title=item.title||movie.title||'Untitled movie';return <article className="wanted-row wanted-movie-row" key={item.id}><span className="wanted-art movie"><img src={`/api/artwork/movie/movie_${item.id}/poster`} alt={`${title} poster`} loading="lazy"/></span><span className="wanted-copy"><strong>{title}</strong><small>{item.qualityProfile?.name||item.status||'Missing'}</small></span>{actions(item)}</article>})}</div>:<div className="panel react-wanted-shows">{[...groups].map(([seriesId,group])=><details className="wanted-show" key={seriesId}><summary><span className="wanted-art show"><img src={`/api/artwork/tv/series_${seriesId}/fanart`} alt="" loading="lazy"/></span><span className="wanted-copy"><strong>{group.title}</strong><small>{[...group.seasons.values()].reduce((sum,value)=>sum+value.length,0)} wanted</small></span></summary><div className="wanted-group-actions"><button className="secondary" onClick={()=>void command('SeriesSearch',{seriesId},'Search for the entire show queued.')}>Search entire show</button></div>{[...group.seasons].map(([season,episodes])=><details className="wanted-season" key={season}><summary><span className="wanted-copy"><strong>Season {season}</strong><small>{episodes.length} wanted</small></span></summary><div className="wanted-group-actions"><button className="secondary" onClick={()=>void command('SeasonSearch',{seriesId,seasonNumber:season},`Season ${season} search queued.`)}>Search entire season</button></div>{episodes.map(item=><article className="wanted-row wanted-episode-row" key={item.id}><span className="wanted-copy"><strong>E{item.episodeNumber??'–'} · {item.title||'Untitled episode'}</strong><small>{item.qualityProfile?.name||item.status||'Missing'}</small></span>{actions(item)}</article>)}</details>)}</details>)}</div>}
  {releases!==null?<dialog open className="react-wanted-dialog"><div className="release-browser"><div className="panel-heading"><div><h2>Interactive search · {releaseTitle}</h2><p className="muted">{releases.length} releases found</p></div><button className="secondary" onClick={()=>setReleases(null)}>Close</button></div><div className="wanted-release-list">{releases.map((release,index)=><article className="release-row" key={index}><div className="release-title"><strong>{String(release.title||'Unknown release')}</strong><small>{String(release.indexer||'Unknown source')}</small></div><span>{String((release.quality as {quality?:{name?:string}})?.quality?.name||'Unknown quality')}</span><span>{(Number(release.size||0)/1073741824).toFixed(2)} GB</span><span>{String(release.seeders??'—')} seeders</span><button className="primary" onClick={()=>void grab(release)}>Grab</button></article>)}</div></div></dialog>:null}</div>;
}
