import { useCallback,useEffect,useMemo,useState } from 'react';
import type { SearchJob,WantedDomain,WantedItem,WantedLibraryItem,WantedMountOptions,WantedView } from './wanted-types';
import './react-wanted.css';
type DomainFilter='all'|WantedDomain;
const message=(reason:unknown)=>reason instanceof Error?reason.message:'The request could not be completed.';
const records=(result:{records?:WantedItem[]}|WantedItem[])=>Array.isArray(result)?result:result.records||[];
export function WantedView({options}:{options:WantedMountOptions}){
  const [domain,setDomain]=useState<DomainFilter>('all'),[view,setView]=useState<WantedView>('wantedMissing'),[items,setItems]=useState<WantedItem[]>([]),[library,setLibrary]=useState<WantedLibraryItem[]>([]);
  const [loading,setLoading]=useState(true),[error,setError]=useState(''),[busy,setBusy]=useState(''),[jobs,setJobs]=useState<SearchJob[]>([]),[releases,setReleases]=useState<Record<string,unknown>[]|null>(null),[releaseTitle,setReleaseTitle]=useState(''),[releaseDomain,setReleaseDomain]=useState<WantedDomain>('movie');
  const domains:WantedDomain[]=domain==='all'?['movie','tv']:[domain];
  const load=useCallback(async()=>{setLoading(true);try{const values=await Promise.all(domains.flatMap(value=>[options.request<{result:{records?:WantedItem[]}|WantedItem[]}>(`/api/manage/${value}/${view}?page=1&pageSize=1000&sortKey=title&sortDirection=ascending${value==='tv'&&view==='wantedMissing'?'&monitored=true':''}`),options.request<{result:WantedLibraryItem[]}>(`/api/manage/${value}/library`)]));const nextItems:WantedItem[]=[],nextLibrary:WantedLibraryItem[]=[];domains.forEach((value,index)=>{nextItems.push(...records((values[index*2] as {result:{records?:WantedItem[]}|WantedItem[]}).result).map(item=>({...item,domain:value})));nextLibrary.push(...((values[index*2+1] as {result:WantedLibraryItem[]}).result||[]).map(item=>({...item,domain:value})));});const attributionValues=await Promise.all(domains.map(value=>options.request<{items:Record<string,Array<{id:string;name:string;username:string;requestedAt?:string|null}>>}>(`/api/request-attribution?domain=${value}&mediaIds=${nextItems.filter(item=>item.domain===value).map(item=>value==='tv'?item.seriesId||item.id:item.id).join(',')}`))),attributions=Object.assign({},...attributionValues.map(value=>value.items));setItems(nextItems.map(item=>({...item,requesters:attributions[`${item.domain}:${item.domain==='tv'?item.seriesId||item.id:item.id}`]||[]})));setLibrary(nextLibrary);setError('');}catch(reason){setError(message(reason));}finally{setLoading(false);}},[domain,view,options]);
  const pollJobs=useCallback(async()=>{try{const value=await options.request<{items:SearchJob[]}>('/api/search-jobs');setJobs(domains.map(target=>value.items.filter(item=>item.domain===target).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))[0]).filter((item):item is SearchJob=>Boolean(item)));}catch{}},[domain,options]);
  useEffect(()=>{void load();void pollJobs();},[load,pollJobs]);const activeJobs=jobs.filter(job=>['queued','running','canceling'].includes(job.status));
  useEffect(()=>{if(!activeJobs.length)return;const timer=window.setTimeout(()=>void pollJobs(),1500);return()=>window.clearTimeout(timer);},[jobs,pollJobs]);
  const libraryByKey=useMemo(()=>new Map(library.map(item=>[`${item.domain}:${Number(item.id)}`,item])),[library]);
  const command=async(target:WantedDomain,name:string,payload:Record<string,unknown>,notice:string)=>{setBusy(name+JSON.stringify(payload));try{await options.request(`/api/manage/${target}/commands`,{method:'POST',body:JSON.stringify({name,...payload})});options.notify(notice);}catch(reason){options.notify(message(reason),'error');}finally{setBusy('');}};
  const automatic=(item:WantedItem)=>command(item.domain,item.domain==='movie'?'MoviesSearch':'EpisodeSearch',item.domain==='movie'?{movieIds:[item.id]}:{episodeIds:[item.id]},'Automatic search queued.');
  const interactive=async(item:WantedItem)=>{const target=item.domain,title=item.title||item.series?.title||item.movie?.title||'Wanted item';setReleaseDomain(target);setReleaseTitle(title);setReleases([]);try{const query=target==='movie'?`movieId=${item.id}`:`episodeId=${item.id}`,value=await options.request<{result:Record<string,unknown>[] }>(`/api/manage/${target}/releases?${query}`);setReleases(value.result||[]);}catch(reason){setReleases(null);options.notify(message(reason),'error');}};
  const grab=async(release:Record<string,unknown>)=>{try{await options.request(`/api/manage/${releaseDomain}/releases`,{method:'POST',body:JSON.stringify(release)});options.notify('Release sent to the download client.');setReleases(null);}catch(reason){options.notify(message(reason),'error');}};
  const startAll=async()=>{setBusy('all');try{await Promise.all(domains.map(target=>options.request('/api/search-jobs',{method:'POST',body:JSON.stringify({domain:target})})));options.notify(domain==='all'?'Movie and television missing searches started.':`${domain==='movie'?'Movie':'Television'} missing search started.`);void pollJobs();}catch(reason){options.notify(message(reason),'error');}finally{setBusy('');}};
  const movieItems=items.filter(item=>item.domain==='movie'),tvItems=items.filter(item=>item.domain==='tv');
  const groups=useMemo(()=>{const result=new Map<number,{title:string;seasons:Map<number,WantedItem[]>}>();for(const item of tvItems){const seriesId=Number(item.seriesId),series=item.series||libraryByKey.get(`tv:${seriesId}`)||{},entry=result.get(seriesId)||{title:series.title||`Series ${seriesId}`,seasons:new Map()};const season=Number(item.seasonNumber||0);entry.seasons.set(season,[...(entry.seasons.get(season)||[]),item]);result.set(seriesId,entry);}return result;},[tvItems,libraryByKey]);
  const actions=(item:WantedItem)=><div className="wanted-actions"><button className="secondary" disabled={Boolean(busy)} onClick={()=>void automatic(item)}>Automatic search</button><button className="secondary" onClick={()=>void interactive(item)}>Interactive search</button></div>;
  const movies=<section className="react-wanted-domain"><h2>Movies <span>{movieItems.length}</span></h2><div className="wanted-card-grid">{movieItems.map(item=>{const movie=item.movie||libraryByKey.get(`movie:${item.id}`)||item,title=item.title||movie.title||'Untitled movie',year='year'in movie?movie.year:undefined,genres='genres'in movie?movie.genres:undefined,studio='studio'in movie?movie.studio:undefined,runtime=Number(item.runtime||('runtime'in movie?movie.runtime:0)||0),profile=item.qualityProfile?.name||('qualityProfile'in movie&&typeof movie.qualityProfile==='string'?movie.qualityProfile:'')||'Not reported';return <article className="wanted-card" key={item.id}>
    <span className="wanted-card-art"><img src={`/api/artwork/movie/movie_${item.id}/poster`} alt="" loading="lazy"/></span>
    <div className="wanted-card-copy"><div className="wanted-card-heading"><div><strong>{title}</strong><small>{[year,studio].filter(Boolean).join(' · ')||'Movie'}</small></div><span className={`badge ${view==='wantedMissing'?'warm':''}`}>{view==='wantedMissing'?'Missing':'Cutoff unmet'}</span></div>
      <div className="wanted-card-facts"><span><b>Profile</b>{profile}</span><span><b>Status</b>{item.status||'Released'}</span><span><b>Runtime</b>{runtime?`${runtime} min`:'Unknown'}</span></div>
      {genres?.length?<p>{genres.slice(0,3).join(' · ')}</p>:null}{item.requesters?.length?<p className="requester-attribution">Requested by {item.requesters.map(user=>user.name).join(', ')}</p>:null}{actions(item)}
    </div>
  </article>})}</div></section>;
  const television=<section className="react-wanted-domain"><h2>Television <span>{tvItems.length}</span></h2><div className="panel react-wanted-shows">{[...groups].map(([seriesId,group])=>{const requesters=tvItems.find(item=>Number(item.seriesId)===seriesId)?.requesters||[];return <details className="wanted-show" key={seriesId}><summary><span className="wanted-art show"><img src={`/api/artwork/tv/series_${seriesId}/fanart`} alt="" loading="lazy"/></span><span className="wanted-copy"><strong>{group.title}</strong><small>{[...group.seasons.values()].reduce((sum,value)=>sum+value.length,0)} wanted</small>{requesters.length?<small className="requester-attribution">Requested by {requesters.map(user=>user.name).join(', ')}</small>:null}</span></summary><div className="wanted-group-actions"><button className="secondary" onClick={()=>void command('tv','SeriesSearch',{seriesId},'Search for the entire show queued.')}>Search entire show</button></div>{[...group.seasons].map(([season,episodes])=><details className="wanted-season" key={season}><summary><span className="wanted-copy"><strong>Season {season}</strong><small>{episodes.length} wanted</small></span></summary><div className="wanted-group-actions"><button className="secondary" onClick={()=>void command('tv','SeasonSearch',{seriesId,seasonNumber:season},`Season ${season} search queued.`)}>Search entire season</button></div>{episodes.map(item=><article className="wanted-row wanted-episode-row" key={item.id}><span className="wanted-copy"><strong>E{item.episodeNumber??'–'} · {item.title||'Untitled episode'}</strong><small>{item.qualityProfile?.name||item.status||'Missing'}</small></span>{actions(item)}</article>)}</details>)}</details>})}</div></section>;
  return <div className="react-wanted"><div className="hero"><div><span className="eyebrow">ATTENTION</span><h1>Wanted</h1><p className="lede">Missing items and quality-cutoff gaps across monitored libraries.</p></div><div className="hero-actions"><button className="primary" disabled={Boolean(activeJobs.length)||busy==='all'} onClick={()=>void startAll()}>{activeJobs.length?'Search running…':domain==='all'?'Search all missing':'Search missing'}</button><button className="secondary" onClick={()=>void load()}>Refresh</button></div></div>
  {jobs.map(job=>{const done=job.completed+job.failed,active=['queued','running','canceling'].includes(job.status);return <div className="panel wanted-search-progress" key={job.id}><div className="panel-heading"><div><strong>{job.label} missing search</strong><small>{job.currentTitle||job.status} · {done}/{job.total}</small></div>{active?<button className="secondary" onClick={()=>void options.request(`/api/search-jobs/${job.id}`,{method:'DELETE'}).then(pollJobs)}>Cancel</button>:null}</div><div className="import-job-meter"><span style={{width:`${Math.round(done/Math.max(1,job.total)*100)}%`}}/></div></div>})}
  <div className="wanted-controls"><div className="wanted-segment wanted-domain-tabs">{([['all','All'],['movie','Movies'],['tv','Television']] as [DomainFilter,string][]).map(([value,label])=><button className={domain===value?'active':''} onClick={()=>setDomain(value)} key={value}>{label}</button>)}</div><div className="wanted-segment">{([['wantedMissing','Missing'],['wantedCutoff','Cutoff unmet']] as [WantedView,string][]).map(([value,label])=><button className={view===value?'active':''} onClick={()=>setView(value)} key={value}>{label}</button>)}</div></div>
  {loading?<div className="panel skeleton">Loading…</div>:error?<div className="panel error-state"><p>{error}</p></div>:!items.length?<div className="panel empty"><h2>Nothing wanted</h2><p>This monitored library has no items in this view.</p></div>:<>{movieItems.length?movies:null}{tvItems.length?television:null}</>}
  {releases!==null?<dialog open className="react-wanted-dialog"><div className="release-browser"><div className="panel-heading"><div><h2>Interactive search · {releaseTitle}</h2><p className="muted">{releases.length} releases found</p></div><button className="secondary" onClick={()=>setReleases(null)}>Close</button></div><div className="wanted-release-list">{releases.map((release,index)=><article className="release-row" key={index}><div className="release-title"><strong>{String(release.title||'Unknown release')}</strong><small>{String(release.indexer||'Unknown source')}</small></div><span>{String((release.quality as {quality?:{name?:string}})?.quality?.name||'Unknown quality')}</span><span>{(Number(release.size||0)/1073741824).toFixed(2)} GB</span><span>{String(release.seeders??'—')} seeders</span><button className="primary" onClick={()=>void grab(release)}>Grab</button></article>)}</div></div></dialog>:null}</div>;
}
