import { randomUUID } from 'node:crypto';

const text=(value,max=240)=>String(value??'').trim().slice(0,max);
const now=()=>new Date().toISOString();
const publicProvider=provider=>({id:provider.id,name:provider.name,type:provider.type,implementation:provider.implementation,enabled:provider.enabled,priority:provider.priority,categories:provider.categories||[],capabilities:provider.capabilities||[],configured:Boolean(provider.endpoint)});

export class MusicService {
  constructor({store,indexerTester=null,downloadClientTester=null,searcher=null,grabber=null}){this.store=store;this.indexerTester=indexerTester;this.downloadClientTester=downloadClientTester;this.searcher=searcher;this.grabber=grabber;}
  async snapshot(){const state=await this.store.read();return{artists:state.artists||[],albums:state.albums||[],tracks:state.tracks||[],jobs:state.jobs||[],indexers:(state.indexers||[]).map(publicProvider),downloadClients:(state.downloadClients||[]).map(publicProvider)};}
  async saveProvider(type,input){if(!['indexer','downloadClient'].includes(type))throw new TypeError('Unsupported music provider type');const key=type==='indexer'?'indexers':'downloadClients',record={id:text(input.id)||`${type}_${randomUUID()}`,name:text(input.name,80),type,implementation:text(input.implementation,40)||'torznab',endpoint:text(input.endpoint,500),apiKey:text(input.apiKey,500),username:text(input.username,160),password:text(input.password,500),enabled:input.enabled!==false,priority:Math.max(1,Math.min(100,Number(input.priority)||25)),categories:Array.isArray(input.categories)?input.categories.map(value=>text(value,40)).filter(Boolean):[],capabilities:Array.isArray(input.capabilities)?input.capabilities.map(value=>text(value,40)).filter(Boolean):[],updatedAt:now()};if(!record.name||!record.endpoint)throw new TypeError('Provider name and endpoint are required');await this.store.update(state=>{state[key]||=[];const index=state[key].findIndex(item=>item.id===record.id);if(index>=0){const previous=state[key][index];state[key][index]={...previous,...record,apiKey:record.apiKey||previous.apiKey,password:record.password||previous.password};}else state[key].push(record);state.updatedAt=record.updatedAt;});return publicProvider(record);}
  async removeProvider(type,id){const key=type==='indexer'?'indexers':type==='downloadClient'?'downloadClients':null;if(!key)throw new TypeError('Unsupported music provider type');return this.store.update(state=>{const before=(state[key]||[]).length;state[key]=(state[key]||[]).filter(item=>item.id!==id);return before!==state[key].length;});}
  async testProvider(type,input){const tester=type==='indexer'?this.indexerTester:this.downloadClientTester;if(!tester)return{reachable:false,compatible:false,message:'No connector is installed for this provider implementation.'};const started=Date.now(),result=await tester(input);return{reachable:result?.reachable!==false,compatible:result?.compatible!==false,capabilities:result?.capabilities||[],latencyMs:Date.now()-started,message:result?.message||'Connection successful.'};}
  async saveArtist(input){const artist={id:text(input.id)||`artist_${randomUUID()}`,name:text(input.name,160),sortName:text(input.sortName||input.name,160),foreignArtistId:text(input.foreignArtistId,120)||null,overview:text(input.overview,2000),genres:Array.isArray(input.genres)?input.genres.map(value=>text(value,80)).filter(Boolean):[],monitored:input.monitored!==false,monitorMode:['all','future','missing','none'].includes(input.monitorMode)?input.monitorMode:'all',qualityProfile:text(input.qualityProfile,100)||'Any',path:text(input.path,500)||null,artwork:text(input.artwork,1000)||null,addedAt:input.addedAt||now(),updatedAt:now()};if(!artist.name)throw new TypeError('Artist name is required');await this.store.update(state=>{state.artists||=[];const index=state.artists.findIndex(item=>item.id===artist.id);if(index>=0)state.artists[index]={...state.artists[index],...artist};else state.artists.push(artist);state.updatedAt=artist.updatedAt;});return artist;}
  async saveAlbum(input){const album={id:text(input.id)||`album_${randomUUID()}`,artistId:text(input.artistId),title:text(input.title,240),releaseDate:input.releaseDate||null,releaseType:text(input.releaseType,40)||'album',monitored:input.monitored!==false,trackCount:Math.max(0,Number(input.trackCount)||0),availableTrackCount:Math.max(0,Number(input.availableTrackCount)||0),quality:text(input.quality,100)||null,artwork:text(input.artwork,1000)||null,updatedAt:now()};if(!album.artistId||!album.title)throw new TypeError('Album artist and title are required');await this.store.update(state=>{state.albums||=[];const index=state.albums.findIndex(item=>item.id===album.id);if(index>=0)state.albums[index]={...state.albums[index],...album};else state.albums.push(album);});return album;}
  async search(query){const state=await this.store.read(),indexers=(state.indexers||[]).filter(item=>item.enabled!==false).sort((a,b)=>a.priority-b.priority);if(!indexers.length)return{items:[],warnings:['Configure and enable at least one music indexer.']};if(!this.searcher)return{items:[],warnings:['No search connector is installed for the configured indexers.']};const raw=await this.searcher({query,indexers});const items=(raw||[]).map(item=>({...item,score:Number(item.score||0),reasons:Array.isArray(item.reasons)?item.reasons:[]})).sort((a,b)=>b.score-a.score);return{items,warnings:[]};}
  async grab(input){const state=await this.store.read(),client=(state.downloadClients||[]).filter(item=>item.enabled!==false).sort((a,b)=>a.priority-b.priority)[0];if(!client)throw new Error('Configure and enable a music download client before grabbing releases');if(!this.grabber)throw new Error('No grab connector is installed for the configured download client');const job={id:`music_job_${randomUUID()}`,kind:'grab',title:text(input.title,240)||'Music release',artistId:text(input.artistId)||null,albumId:text(input.albumId)||null,status:'queued',downloadClientId:client.id,createdAt:now(),updatedAt:now()};await this.store.update(value=>{value.jobs||=[];value.jobs.unshift(job);});try{const result=await this.grabber({release:input,client});job.status='sent';job.externalId=text(result?.id,160)||null;job.updatedAt=now();}catch(error){job.status='failed';job.error=text(error?.message||error,500);job.updatedAt=now();throw error;}finally{await this.store.update(value=>{const index=(value.jobs||[]).findIndex(item=>item.id===job.id);if(index>=0)value.jobs[index]=job;});}return job;}
}
