import { randomUUID } from 'node:crypto';

const text=(value,max=500)=>String(value??'').trim().slice(0,max);
const now=()=>new Date().toISOString();
const normalizeLanguages=values=>[...new Set((Array.isArray(values)?values:[]).map(value=>text(value,20).toLowerCase()).filter(Boolean))];
const publicProvider=value=>({id:value.id,name:value.name,implementation:value.implementation,enabled:value.enabled,priority:value.priority,capabilities:value.capabilities||[],configured:Boolean(value.endpoint)});

export class SubtitleService {
  constructor({store,providerTester=null,searcher=null,downloader=null}){this.store=store;this.providerTester=providerTester;this.searcher=searcher;this.downloader=downloader;}
  async snapshot(){const state=await this.store.read();return{providers:(state.providers||[]).map(publicProvider),profiles:state.profiles||[],assignments:state.assignments||[],items:state.items||[],jobs:state.jobs||[],history:state.history||[]};}
  async saveProvider(input){const record={id:text(input.id)||`subtitle_provider_${randomUUID()}`,name:text(input.name,80),implementation:text(input.implementation,60)||'opensubtitles',endpoint:text(input.endpoint,500),apiKey:text(input.apiKey,500),username:text(input.username,160),password:text(input.password,500),enabled:input.enabled!==false,priority:Math.max(1,Math.min(100,Number(input.priority)||25)),capabilities:Array.isArray(input.capabilities)?input.capabilities.map(value=>text(value,40)):[],updatedAt:now()};if(!record.name||!record.endpoint)throw new TypeError('Provider name and endpoint are required');await this.store.update(state=>{state.providers||=[];const index=state.providers.findIndex(item=>item.id===record.id);if(index>=0){const previous=state.providers[index];state.providers[index]={...previous,...record,apiKey:record.apiKey||previous.apiKey,password:record.password||previous.password};}else state.providers.push(record);});return publicProvider(record);}
  async removeProvider(id){return this.store.update(state=>{const before=(state.providers||[]).length;state.providers=(state.providers||[]).filter(item=>item.id!==id);return before!==state.providers.length;});}
  async testProvider(input){if(!this.providerTester)return{reachable:false,compatible:false,message:'No connector is installed for this subtitle provider.'};const started=Date.now(),result=await this.providerTester(input);return{reachable:result?.reachable!==false,compatible:result?.compatible!==false,languages:normalizeLanguages(result?.languages),latencyMs:Date.now()-started,message:result?.message||'Connection successful.'};}
  async saveProfile(input){const profile={id:text(input.id)||`subtitle_profile_${randomUUID()}`,name:text(input.name,100),languages:normalizeLanguages(input.languages),forced:normalizeLanguages(input.forced),hearingImpaired:['prefer','include','exclude'].includes(input.hearingImpaired)?input.hearingImpaired:'include',upgradeUntilScore:Number(input.upgradeUntilScore)||null,enabled:input.enabled!==false,updatedAt:now()};if(!profile.name||!profile.languages.length)throw new TypeError('Profile name and at least one language are required');await this.store.update(state=>{state.profiles||=[];const index=state.profiles.findIndex(item=>item.id===profile.id);if(index>=0)state.profiles[index]=profile;else state.profiles.push(profile);});return profile;}
  async assign(input){const assignment={id:text(input.id)||`subtitle_assignment_${randomUUID()}`,domain:['movie','series','season','episode'].includes(input.domain)?input.domain:'series',mediaId:text(input.mediaId,180),profileId:text(input.profileId,180),enabled:input.enabled!==false,updatedAt:now()};if(!assignment.mediaId||!assignment.profileId)throw new TypeError('Media and subtitle profile are required');await this.store.update(state=>{state.assignments||=[];const index=state.assignments.findIndex(item=>item.domain===assignment.domain&&item.mediaId===assignment.mediaId);if(index>=0)state.assignments[index]={...state.assignments[index],...assignment};else state.assignments.push(assignment);});return assignment;}
  async reconcile(input){const item={id:`${input.domain}_${text(input.mediaId,160)}`,domain:input.domain,mediaId:text(input.mediaId,160),seriesId:text(input.seriesId,160)||null,seasonNumber:Number.isFinite(Number(input.seasonNumber))?Number(input.seasonNumber):null,episodeNumber:Number.isFinite(Number(input.episodeNumber))?Number(input.episodeNumber):null,title:text(input.title,240),filePath:text(input.filePath,1000)||null,embedded:normalizeLanguages(input.embedded),external:normalizeLanguages(input.external),updatedAt:now()};await this.store.update(state=>{state.items||=[];const index=state.items.findIndex(value=>value.id===item.id);if(index>=0)state.items[index]={...state.items[index],...item};else state.items.push(item);});return item;}
  async status(item){const state=await this.store.read(),assignment=this.#assignment(state,item),profile=(state.profiles||[]).find(value=>value.id===assignment?.profileId),present=new Set([...normalizeLanguages(item.embedded),...normalizeLanguages(item.external)]),required=profile?.languages||[],missing=required.filter(language=>!present.has(language));return{...item,profile:profile||null,requiredLanguages:required,presentLanguages:[...present],missingLanguages:missing,complete:Boolean(profile)&&missing.length===0};}
  #assignment(state,item){const assignments=(state.assignments||[]).filter(value=>value.enabled!==false),keys=[['episode',item.mediaId],['season',item.seriesId&&item.seasonNumber!=null?`${item.seriesId}:season:${item.seasonNumber}`:null],['series',item.seriesId],['movie',item.domain==='movie'?item.mediaId:null]];for(const [domain,id] of keys){const found=assignments.find(value=>value.domain===domain&&value.mediaId===id);if(found)return found;}return null;}
  async search(input){const state=await this.store.read(),item=(state.items||[]).find(value=>value.id===input.itemId);if(!item)throw new Error('Subtitle media item was not found');const status=await this.status(item),providers=(state.providers||[]).filter(value=>value.enabled!==false).sort((a,b)=>a.priority-b.priority);if(!status.profile)return{items:[],warnings:['Assign a subtitle profile to this title or episode.']};if(!providers.length)return{items:[],warnings:['Configure and enable at least one subtitle provider.']};if(!this.searcher)return{items:[],warnings:['No search connector is installed for the configured subtitle providers.']};const results=await this.searcher({item:status,languages:input.languages?.length?normalizeLanguages(input.languages):status.missingLanguages,providers});return{items:(results||[]).sort((a,b)=>Number(b.score||0)-Number(a.score||0)),warnings:[]};}
  async download(input){const state=await this.store.read(),item=(state.items||[]).find(value=>value.id===input.itemId),provider=(state.providers||[]).find(value=>value.id===input.providerId&&value.enabled!==false);if(!item||!provider)throw new Error('Subtitle item or provider was not found');if(!this.downloader)throw new Error('No download connector is installed for the configured subtitle provider');const job={id:`subtitle_job_${randomUUID()}`,itemId:item.id,providerId:provider.id,language:text(input.language,20).toLowerCase(),status:'downloading',createdAt:now(),updatedAt:now()};await this.store.update(value=>{value.jobs||=[];value.jobs.unshift(job);});try{const result=await this.downloader({item,provider,result:input});job.status='completed';job.path=text(result?.path,1000)||null;await this.store.update(value=>{const media=value.items.find(entry=>entry.id===item.id);if(media&&!media.external.includes(job.language))media.external.push(job.language);value.history||=[];value.history.unshift({id:`subtitle_history_${randomUUID()}`,jobId:job.id,itemId:item.id,provider:provider.name,language:job.language,path:job.path,createdAt:now()});});}catch(error){job.status='failed';job.error=text(error?.message||error);throw error;}finally{job.updatedAt=now();await this.store.update(value=>{const index=value.jobs.findIndex(entry=>entry.id===job.id);if(index>=0)value.jobs[index]=job;});}return job;}
  async processMediaArrival(input){const item=await this.reconcile(input),status=await this.status(item);if(!status.missingLanguages.length)return{item:status,queued:[]};const queued=[];for(const language of status.missingLanguages)queued.push({itemId:item.id,language,status:'awaiting-search'});await this.store.update(state=>{state.jobs||=[];for(const job of queued)state.jobs.unshift({id:`subtitle_job_${randomUUID()}`,...job,createdAt:now(),updatedAt:now()});});return{item:status,queued};}
}
